### ISSUE TITLE
React rewrite alpha: target profile page crashes for (some?) antisense RNA ENSGs

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#1015]
It throws `TypeError: Cannot read property 'id' of null` on this line in `src/public/target/Page.js`:
```js
  const uniprotId = proteinAnnotations.id;
```

Contrived example: [ENSG00000180139](https://alpha--platform-app.netlify.app/target/ENSG00000180139).

Seen for [some pseudogene ENSGs](https://alpha--platform-app.netlify.app/target/ENSG00000265018) as well, but not all.

**Comment by andrewhercules** [comment]
Thanks @fedde-s 

I have added this to a list of cases for testing the target profile page functionality

**Comment by d0choa** [comment]
Thanks! Please also note these cases also crash the search results page. Probably, because of the  right panel but I haven't investigated it.

**Comment by forus** [comment]
I'm investigating the issue.

**Comment by mirandaio** [comment]
@fedde-s this has been fixed by @forus PR. Thanks to you both for reporting it and for the PR!

@d0choa made some commits to also fix the search page being broken due to missing protein annotations which was needed to display the `functions` and `accessions` in the right panel. Also added a `BoundaryError` component around the right panel to prevent future errors there that would break the whole page.

**Comment by d0choa** [comment]
Awesome! Thank you all
