### ISSUE TITLE
intracellular targets with Ab tractability assessment

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#1019]
Workshop attendees have brought to our attention that intracellular proteins seem to be predicted to be tractable by Ab as per the outcome of our tractability pipeline.

One example is BRCA1 raised at a workshop in 2019. Chris Radoux (formerly at ChEMBL) has provided this explanation at the time:

<img width="819" alt="Screen Shot 2020-05-11 at 16 27 04" src="https://user-images.githubusercontent.com/6472381/81579634-4b91fe00-93a4-11ea-8688-5eb6307c4219.png">

As per release 20.04, BRCA1 is still deemed tractable by Ab:

<img width="903" alt="Screen Shot 2020-05-11 at 16 28 32" src="https://user-images.githubusercontent.com/6472381/81579823-87c55e80-93a4-11ea-8720-1ebbd7d1f134.png">
<img width="1276" alt="Screen Shot 2020-05-11 at 16 28 49" src="https://user-images.githubusercontent.com/6472381/81579833-8a27b880-93a4-11ea-8bcc-77276616a474.png">

The latest report of this behaviour was done on May 4th at a Sanofi training. I will try to get additional examples to BRCA1 so that we can investigate whether this issue can be addressed.

**Comment by d0choa** [comment]
Thanks @deniseOme. The issue is on the tractability bucket assumption that GO provides correct cellular localisation. I added a screenshot on the rewrite where the data can be seen side-by-side.

<img width="1221" alt="Screenshot 2020-05-11 at 20 51 41" src="https://user-images.githubusercontent.com/5097586/81605415-53b06480-93c9-11ea-869d-15e57c6058e2.png">

We'll report back to the tractability team for them to think more carefully about this assumption. I'll close as it should require no more action in our side.
