### ISSUE TITLE
Identifying lead variants in genetics portal evidence strings

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#1117]
Is there a way to determine lead vs tag variant in the OTP evidence strings from OTG, e.g. [genetics-portal-evidences-2020-03-12.json.gz](https://storage.googleapis.com/open-targets-data-releases/20.04/input/evidence-files/genetics-portal-evidences-2020-03-12.json.gz)?

**Comment by eric-czech** [comment]
I think I've answered my own question in finding that all the variants have genome wide significance (no tag variants).

Is there a dataset on GCS anywhere with L2G scores for tag variants as well?  I'm assuming there is one downstream from [genetics-l2g-scoring](https://github.com/opentargets/genetics-l2g-scoring) and upstream from [evidence_datasource_parsers](https://github.com/opentargets/evidence_datasource_parsers), but I thought I'd ask before digging too much.

**Comment by d0choa** [comment]
Yes your self-answer is correct. As you said, only a fraction of variants with L2G will have tag variants.

This exceeds my understanding of the Genetics GCS data. Perhaps, @mkarmona might be able to help you.

**Comment by eric-czech** [comment]
Thanks @d0choa.  To focus my question a bit more then, are L2G scores even computed for variants that didn't reach genome wide significance in the originating study?  I couldn't tell if the 5e-8 p-value filter was applied before or after genetics-l2g-scoring.

**Comment by mkarmona** [comment]
@eric-czech , we developed two main methods to find the causal variant and gene for a given pair study trait and lead variant. Given the difference between [lead variant](https://genetics-docs.opentargets.org/our-approach/assigning-traits-to-loci) and [tag variant](https://genetics-docs.opentargets.org/our-approach/data-pipeline) (and also [here](https://genetics-docs.opentargets.org/faqs#what-is-the-difference-between-lead-variant-and-tag-variant)), [the way to connect the chain](https://genetics-docs.opentargets.org/our-approach/assigning-traits-to-loci#lead-variant-to-tag-variant-expansion) from a study to a gene needs the intersection of the expanded lead variants to a cluster of significant ones with the variants (tag ones) coming from the functional genomic ones. The former method has some limitations as the weights of the score computation are somehow arbitrary so to overcome this, the method you mentioned, locus to a gene (aka l2g), was conceived to overcome not just the aforementioned limitation but also to include implicit knowledge from the manually curated golden set among other features from other datasets (including functional genomic ones). This allowed us to assign and rank in a systematic way all tuples study-trait to at least one protein-coding gene through a locus. The generated model takes into account [many datasets](https://github.com/opentargets/genetics-l2g-scoring/blob/bcb09dc01f5fa7429480a84dd114d9a56a530413/1_feature_engineering/1_prepare_inputs.py#L24) and the tags (from some datasets) are taken into account as well so the intention is to offer a systematic fine-mapping and protein-coding gene prioritization across all GWAS loci. And from the mention of the file you are pointing to, those evidences are the thresholded ones (where the score is greater than a given value to get rid of the tail). If you want the full input dataset for the genetic evidences before they are thresholded (in order to be included into the OT Platform as evidences) then they [are here](http://ftp.ebi.ac.uk/pub/databases/opentargets/genetics/20022712/l2g/).

Regarding the question _I couldn't tell if the 5e-8 p-value filter was applied before or after genetics-l2g-scoring._ , summary stats are pre-processed before they get into the analysis pipeline (the full pipeline including the merge one are needed as the l2g score needs datasets from many places) and the [significant windows](https://github.com/opentargets/genetics-sumstat-data/blob/master/filters/significant_window_extraction/filter_by_merge.py#L47) are used when the harmonised sum stats [are preprocessed](https://github.com/opentargets/genetics-sumstat-data/blob/master/filters/significant_window_extraction/queue_all.py#L12). As a note, it uses a _p_-value threshold to find the window and all hits are included within the window for the analyses (as fine-mapping and so on); those also overlap each other is more than one is found in there. 

Trying to answer your question _are L2G scores even computed for variants that didn't reach genome-wide significance in the originating study?_ it is not applied to variants that are not genome-wide significance.

I hope this help to clarify somehow your questions, if not, please tell us again otherwise.

**Comment by mkarmona** [comment]
just to clarify a bit further the _p_-value filtering. for the phewas plot, all studies are filtered by simple p-value threshold but for analyses, the significant regions are detected by p-value and then all variants in that window per significant hit are included

**Comment by eric-czech** [comment]
Thanks @mkarmona!  Appreciate the links to the code.

> The generated model takes into account many datasets and the tags

Makes sense, but I'm curious what `toploci` and `credset` datasets are used for then.  Are they only used to generate features for lead variants?  When I saw that I thought that might mean tag variants would get scored too.  It makes sense that they may only be used for features.

> the significant windows are used when the harmonised sum stats are preprocessed.

Perfect, good to know where that lives.

> If you want the full input dataset for the genetic evidences before they are thresholded then they are here.

👍 

My last question then before closing this out would be: was there a reason the choice was made not to compute l2g scores for tag variants as well?

**Comment by DSuveges** [comment]
Hi @eric-czech,

The integrative locus to gene (l2g) score captures effect of all variants in the credible set, so the score is associated with a locus rather a given variant, it's just the lead variant that is chosen to represent the locus. 

You can find a description of the method in this [preprint](https://www.biorxiv.org/content/10.1101/2020.09.16.299271v2.full)

I hope this response address your question, please don't hesitate contacting us if you have further questions.
