### ISSUE TITLE
EVA (ClinVar) improve scoring based on review status + clinical significance

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1138]
Explore and implement an improved scoring scheme for EVA evidences based on review status and/or clinical significance.

**Comment by AsierGonzalez** [comment]
I will ask Kirill and overview of the distribution of those two values so that we can get a better idea of how we should score them.

**Comment by AsierGonzalez** [comment]
Currently, the EVA evidence strings are scored based on their `variant2disease` and `gene2variant` scores, which are both `0.7` for all the evidence strings. As a consequence, the association score is always `6.99E-8`.

This was not the case until 20.04, when we fixed a bug that caused genetic association evidence strings to be scored based on the functional consequence of the variant (see issue #876 and PR [#560](https://github.com/opentargets/data_pipeline/pull/560). Until this fix, the evidence strings were scored using the `variant2disease` score and a score based on the functional consequence of the variant. This is probably a sensible thing to do with this data source given that ClinVar does not provide any scores and the `0.7` value is arbitrary. In fact, until August 2019 only the score for `variant2disease` was provided. For 19.09 EVA replicated the value for `gene2variant` to ensure that it was valid JSON given that the schema version at the time ([1.6.1](https://github.com/opentargets/json_schema/blob/1.6.1/opentargets.json)) required that `gene2variant` had an score. This is not the case since version 1.6.2, meaning that we could ask EVA to remove the `gene2variant` score.

**Comment by iandunham** [comment]
The variant2gene score should have been based on the interpretation of the VEP consequence score as described in this https://www.targetvalidation.org/variants. I suspect that when we ran the gene mapping process,. we also supplied these scores for the variant2gene score field. 

The idea is that the Disease - Variant - Gene score is built up of a D-V component that summarises the confidence that this mutation is related to this disease, and a V - G component that is the strength of the variant effect on disease function (analogous to GWAS). In the full version of the scoring S = fSC, these are the S and C components. f would eb used if we aggregated the score over many observations and is nominally set to 1 here.

So ideally both these (`variant2disease` and `gene2variant`) should vary. We should ask EVA to use the VEP score table for the `gene2variant` part, and think about varying`variant2disease`.

**Comment by AsierGonzalez** [comment]
This is what I mean by scoring "based on the functional consequence of the variant" that was done until 20.04. The only change required to revert back to this is for EVA not to include an score for `gene2variant`, as the pipeline does the scoring based on the functional consequence using the table you mentioned.

**Comment by AsierGonzalez** [comment]
We also want to what to include the review status and the clinical significance in the scoring, which I think that fits better in the D-V component, so it could probably replace the current `variant2disease` score.

**Comment by iandunham** [comment]
Where do they currently derive the `variant2disease` score form? I realise it's always the same. Using the clinical significance in some way would be good. Ultimately we might want to compute across all variants and diseases some confidence that this gene is involved in the disease (similar to the idea behind the Cancer Gene Census scoring, but maybe achieved differently).

**Comment by AsierGonzalez** [comment]
It's hardcoded and last time I checked they did not know where that value came from. I'll ask again.

**Comment by AsierGonzalez** [comment]
Kirill has agreed to remove the gene2variant resource_score. Work can be tracked on [EBIvariation/eva-opentargets#121](https://github.com/EBIvariation/eva-opentargets/issues/121)

**Comment by tskir** [comment]
@DSuveges @AsierGonzalez @iandunham (also copying @tcezard)

I looked into this and can now clarify a few things.

## Current score values

> Currently, the EVA evidence strings are scored based on their variant2disease and gene2variant scores, which are both 0.7 for all the evidence strings. As a consequence, the association score is always 6.99E-8.

Looking at our code, I see that the hardcoded scores for **both** variant2disease and 
gene2variant are actually not 0.7, but **1e-7** (formatted as `1e-07` in the final evidence strings), with the type of "pvalue". This value is present both in the template, and in the final evidence strings which we submit.

I'm not sure where the value 0.7 came from. Maybe this is a result of some sort of conversion from pvalue to score which is done on your side? @AsierGonzalez could you check that?

## Historical changes to the score values

According to the commit history, the variant2disease score with pvalue = 1e-7 was [introduced in April 2016](https://github.com/EBIvariation/eva-opentargets/commit/78850c8979fa03452b78de677bf1286bd7cdfa35#diff-7fb078059570fd424c373936b9c8efdeR52) by the initial developer of the pipeline and never changed since. As far as I can see, this was an arbitrary placeholder value with no justification to it.

The gene2variant score was indeed [added by me in August 2019](https://github.com/EBIvariation/eva-opentargets/commit/7306dc57070feedd8a7e447e49d8f619455adcb7#diff-bfcda823ad83ba7c55272b5478dd6af3R87), just like Asier described above, for compatibility with OT schema version 1.6.1. By similarity, I used the same hardcoded placeholder score with pvalue = 1e-7.

> The variant2gene score should have been based on the interpretation of the VEP consequence score as described in this https://www.targetvalidation.org/variants. I suspect that when we ran the gene mapping process,. we also supplied these scores for the variant2gene score field.

While it sounds sensible, this was never implemented. The scores were always fixed and hardcoded as described above. 

I can also confirm that no such scores were ever provided even when the gene mapping process was run on the Open Targets side. The output results looked something like this (the same way they look now in _our_ gene mapping pipeline):
`10:100749815-100749815:1/A      1       ENSG00000075891 PAX2    missense_variant        0`

Column 2 was always `1`, and column 6 was used for "nearest_gene_five_prime_end" variants, so those ones were not the score.

## Actions to be implemented

I will proceed to remove the gene2variant resource_score section, as we discussed with Asier, in our internal ticket https://github.com/EBIvariation/eva-opentargets/issues/121.

I will keep the variant2disease resource_score at the value of 1e-7 (pvalue), as it has always been.

Please let me know if this sounds sensible to you. I'm also happy to discuss the ways of sensibly computing both of those scores in the future. If we decide how to do it, then this can be done on our side, no problem.

**Comment by d0choa** [comment]
The actions sound good @tskir. 

There seems to be a lot of legacy decisions that look a bit arbitrary when revisiting them. Updating the scoring might obsolete most of them, so let's focus on how to do it right. 

We would definetely want to get you involved on the discussions about the new scoring. I think you're right that we should resolve #1137 #1139 and #1140 and then focus on the scoring.

**Comment by tskir** [comment]
All right then. I'll proceed with the actions and we'll return to this issue once those other ones are resolved

**Comment by AsierGonzalez** [comment]
Assigning this to @DSuveges as he is looking into this data and the best approach to score the evidence based on the new fields.
