### ISSUE TITLE
Adding "last evaluated" date to ClinVar sourced evidences

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1161]
In ClinVar the `last evaluated` date shows "The most recent date that the variant was interpreted, or evaluated, by a submitter." ([link](https://www.ncbi.nlm.nih.gov/clinvar/docs/variation_report/#interpretation)).

The OpenTargets [JSON schema](https://github.com/opentargets/json_schema/tree/ds_eva_changes_2) is updated with the following property of `variant2disease`:

```json
"last_evaluated_date": {
  "type": "string",
  "description": "The most recent date that the variant was interpreted, or evaluated, by a submitter."
}
```

**Comment by AsierGonzalez** [comment]
How does this information differ from the date we currently receive in `.evidence.gene2variant.date_asserted` and `.evidence.variant2disease.date_asserted`? By the way, those two date seem to be the same.

**Comment by DSuveges** [comment]
Not sure about what information the `date_asserted` value captures, but looking at the distribution makes it a bit strange.

```bash
gzcat 20.06_EVA_cttv012-22-05-2020.json.gz | jq -r '"\(.evidence.gene2variant.date_asserted) \(.evidence.date_asserted)"' | sort | uniq -c | sort -nr | column -t
```

```
94463  2019-11-02T00:00:00  null
13250  2019-11-06T00:00:00  null
7750   null                 2019-11-02T00:00:00
3932   2019-12-01T00:00:00  null
1804   2019-11-28T00:00:00  null
804    2019-11-19T00:00:00  null
569    2019-11-30T00:00:00  null
551    2019-11-07T00:00:00  null
186    null                 2019-12-01T00:00:00
166    2019-11-16T00:00:00  null
159    2019-08-25T23:00:00  null
158    2019-11-08T00:00:00  null
139    2019-11-09T00:00:00  null
131    2019-11-12T00:00:00  null
122    null                 2019-11-06T00:00:00
102    2019-11-29T00:00:00  null
96     2019-11-10T00:00:00  null
72     2019-11-26T00:00:00  null
67     2019-11-14T00:00:00  null
50     2019-11-24T00:00:00  null
46     2019-11-17T00:00:00  null
45     null                 2019-11-19T00:00:00
41     2019-08-30T23:00:00  null
40     2019-11-15T00:00:00  null
37     null                 2019-11-07T00:00:00
32     2019-11-21T00:00:00  null
30     null                 2019-11-30T00:00:00
27     2019-11-20T00:00:00  null
26     null                 2019-11-28T00:00:00
24     2019-09-09T23:00:00  null
19     2019-09-10T23:00:00  null
18     2019-10-24T23:00:00  null
16     2019-11-22T00:00:00  null
15     null                 2019-11-29T00:00:00
15     2019-11-25T00:00:00  null
14     2019-10-17T23:00:00  null
14     2019-09-26T23:00:00  null
12     null                 2019-11-08T00:00:00
12     2019-09-16T23:00:00  null
11     2019-09-28T23:00:00  null
10     2019-08-16T23:00:00  null
9      2019-11-18T00:00:00  null
7      2019-11-23T00:00:00  null
7      2019-10-20T23:00:00  null
6      2019-09-20T23:00:00  null
4      null                 2019-08-25T23:00:00
4      2019-10-15T23:00:00  null
4      2019-09-07T23:00:00  null
3      2019-10-10T23:00:00  null
3      2019-09-19T23:00:00  null
2      null                 2019-11-12T00:00:00
2      null                 2019-11-09T00:00:00
2      2019-10-01T23:00:00  null
2      2019-09-03T23:00:00  null
1      null                 2019-11-14T00:00:00
1      2019-10-08T23:00:00  null
1      2019-10-05T23:00:00  null
1      2019-09-17T23:00:00  null
1      2019-09-08T23:00:00  null
1      2019-08-28T23:00:00  null
1      2019-06-16T23:00:00  null
1      2019-03-30T00:00:00  null
```

**Comment by tskir** [comment]
@AsierGonzalez @DSuveges Let me chime in to the discussion.

ClinVar RCV records have three timestamps associated with them:
* `referenceClinVarAssertion/dateCreated` — as expected, a fixed creation date
* `referenceClinVarAssertion/dateLastUpdated` — this appears to track _any_ updates to the record, including purely technical ones which do not concern its clinical significance or interpretation
* `referenceClinVarAssertion/clinicalSignificance/dateLastEvaluated` — this appears to only change when the clinical significance of the record was last (re)evaluated.

Currently `.evidence.gene2variant.date_asserted` and `.evidence.variant2disease.date_asserted` are **both** set to be equal to the `referenceClinVarAssertion/dateLastUpdated`, tracking all, even very minor changes.

What I intend to do is to keep those two attributes the way they currently are, and add a new `variant2disease.last_evaluated_date` field with its corresponding value. Again, since this is inside `variant2disease` block, this will only be possible for `genetic_association` evidence strings.

**Comment by tskir** [comment]
This is now also implemented and undergoing our internal review (https://github.com/EBIvariation/eva-opentargets/pull/150).

This property will only be present for `genetic_association` evidence strings, and only when the clinical assertion is actually present. For example, records with `reviewStatus` = `NO_ASSERTION_PROVIDED` will not contain this property in ClinVar at all, and hence evidence strings will also lack it.

**Comment by AsierGonzalez** [comment]
> Currently `.evidence.gene2variant.date_asserted` and .`evidence.variant2disease.date_asserted` are both set to be equal to the `referenceClinVarAssertion/dateLastUpdated`, tracking all, even very minor changes.

It does not seem right that both parts use the date provided by ClinVar. Based on the definitions you posted, it seems that the ClinVar `referenceClinVarAssertion/dateLastUpdated` applies to `variant2disease`. I imagine that it has been used for the `gene2variant` because the JSON schema required a date there. I can think of two options for the `gene2variant`:

1. Remove the date altogether: I doubt it is being used and it would just require a little change in the schema to make it optional.
2. Use the date when the pipeline to map the variants to the genes was ran: It would be more meaningful but not very much as it would be the same for all the evidence strings (unless you only run the mapping for the variants once, which I doubt it's the case).

> Again, since this is inside `variant2disease` block, this will only be possible for genetic_association evidence strings

As mentioned in [#1140](https://github.com/opentargets/platform/issues/1140#issuecomment-685744145), if you are constrained by the schema this is fine but if you can add the date in the somatic mutations even without it being defined, that would be useful.

> This property will only be present for `genetic_association` evidence strings, and only when the clinical assertion is actually present. For example, records with `reviewStatus` = `NO_ASSERTION_PROVIDED` will not contain this property in ClinVar at all, and hence evidence strings will also lack it.

That makes perfect sense.

**Comment by tskir** [comment]
@AsierGonzalez Thank you for the comments! I've addressed them in the following ways:
* `.evidence.gene2variant.date_asserted` has been removed completely from the evidence strings (option 1 which you suggested)—I agree it does not make sense to just duplicate the value
* `last_evaluated_date` is now added to the `somatic_mutation` evidence strings as well
* I submitted a PR for the schema to reflect those changes accordingly: https://github.com/opentargets/json_schema/pull/99

On our side, the changes have been reviewed & merged.

**Comment by AsierGonzalez** [comment]
PR has been merged

**Comment by andrewhercules** [comment]
Ticket closed as PR has been merged
