### ISSUE TITLE
MONDO_0018797 term has no name attribute

### ISSUE THREAD

**Issue by mirandaio** [opentargets/platform#1211]
MONDO_0018797 does not have a corresponding `name` field in the `diseases_efo.jsonl` file found here `https://storage.googleapis.com/open-targets-data-releases/alpha-rewrite/static/ontology/diseases_efo.jsonl`.

This causes issues in the platform rewrite in the Ontology visualisation.

In addition, the GraphQL API has an internal server error when looking a disease with that id https://tinyurl.com/yxapraxw

**Comment by AsierGonzalez** [comment]
This term seems to have been made obsolote in MONDO (see [mondo/1175](https://github.com/monarch-initiative/mondo/issues/1175)) and [it cannot be found either in EFO or MONDO using OLS](https://www.ebi.ac.uk/ols/search?q=MONDO_0018797&groupField=iri&start=0). I wonder why it is in there in the first place.

**Comment by d0choa** [comment]
To reformulate the problem here, querying an obsoleted disease term (MONDO_0018797) produces an "internal server error":
- [api-beta-dot-open-targets-eu-dev.appspot.com](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20thisdisease%7B%0A%20%20disease(efoId%3A%20%22MONDO_0018797%22)%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%7D%0A%7D&operationName=thisdisease)
- [platform-api-alpha.opentargets.io](https://platform-api-alpha.opentargets.io/api/v4/graphql/browser?query=%7B%0A%20%20disease(efoId%3A%20%22MONDO_0018797%22)%20%7B%0A%20%20%20%20id%0A%20%20%7D%0A%7D%0A)

**Comment by dhimmel** [comment]
Somewhat unrelated question: Is the code that creates `diseases_efo.jsonl` available? Is `diseases_efo.jsonl` derived from `efo_otar_profile.owl`,
`efo_otar_slim.owl`, or something else?

**Comment by d0choa** [comment]
Hi @dhimmel!

The code that generates our current disease index can be found [here](https://github.com/opentargets/data_pipeline/blob/master/mrtarget/modules/EFO.py) but it might be hard to navigate and it has some dependencies, that might be hard to reproduce. The input for this pipeline is `efo_otar_slim.owl` file since November 2019.

@cmalangone is currently refactoring our disease data by converting the OWL to json using the riot tool in [Apache Jena](https://jena.apache.org/download/index.cgi) and processing the data in [Spark](https://github.com/opentargets/platform-etl-backend/blob/cm_disease_hpo/src/main/scala/io/opentargets/etl/backend/Disease.scala). We are also including HPO in a separate index, as well as the disease-phenotype relationships available in HPO and MONDO. We are working on this as we write, but we are getting quite close to having a first version.

<details>
  <summary>Upcoming schema</summary>

```
>>> disease.printSchema()
root
 |-- ancestors: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- children: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- code: string (nullable = true)
 |-- dbXRefs: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- descendants: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- description: string (nullable = true)
 |-- id: string (nullable = true)
 |-- name: string (nullable = true)
 |-- obsoleteTerms: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- ontology: struct (nullable = true)
 |    |-- isTherapeuticArea: boolean (nullable = true)
 |    |-- leaf: boolean (nullable = true)
 |    |-- sources: struct (nullable = true)
 |    |    |-- name: string (nullable = true)
 |    |    |-- url: string (nullable = true)
 |-- parents: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- phenotypes: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- sko: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- synonyms: array (nullable = true)
 |    |-- element: string (containsNull = true)
 |-- synonymsDetails: struct (nullable = true)
 |    |-- hasExactSynonym: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- hasNarrowSynonym: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |    |-- hasRelatedSynonym: array (nullable = true)
 |    |    |-- element: string (containsNull = true)
 |-- therapeuticAreas: array (nullable = true)
 |    |-- element: string (containsNull = true)
 ```

</details>

Let us know if you are interested in this activities and we can keep you in the loop.

**Comment by d0choa** [comment]
The offending term has been removed in EFO OTAR slim v3.26

```
❯ grep MONDO_0018797 efo_otar_slim.owl
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
 ```

**Comment by dhimmel** [comment]
> Let us know if you are interested in this activities and we can keep you in the loop.

Yes @d0choa, super interested in the EFO to disease information pipeline and data!

At @related-sciences, we're currently extracting similar data from the EFO OWL releases via SPARQL queries. Our outputs are parquet tables (that can be used with spark) and an [nxontology](https://github.com/related-sciences/nxontology) graph for performing network operations. This code isn't currently public, but we might move some of it upstream to `nxontology`.

It would be great to compare implementations with OpenTargets. We might even decide we want to derive our EFO datasets from your exports. Do you plan to keep the disease processing code and exports up-to-date with the monthly EFO releases? Will the data outputs be publicly accessible?
