### ISSUE TITLE
Create new Genomics England evidence table in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1234]
On the evidence page in the rewrite, can we please create a new data table that displays the Genomics England evidence data?

**Example GraphQL API query**
[GAA and Glycogen storage disease due to acid maltase deficiency](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_365%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000171298%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22genomics_england%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20resourceScore%0A%20%20%20%20%20%20%20%20resourceScoreType%0A%20%20%20%20%20%20%20%20score%0A%20%20%20%20%20%20%20%20studyId%0A%20%20%20%20%20%20%20%20literature%0A%09%09%09%09confidence%0A%20%20%20%20%20%20%7D%09%09%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

**Data table**

| Data table column | Disease/phenotype | Reported disease/phenotype | Allelic requirement | Genomics England Panel | Confidence | Literature |
| --- | --- | --- | --- | --- | --- | --- |
| **GraphQL API field** | `evidences.rows[x].disease.name` | `evidences.rows[x].diseaseFromSource` | `evidences.rows[x].allelicRequirement` | `evidences.rows[x].studyId` | `evidences.rows[x].confidence` | `evidences.rows[x].literature`
| **Sample data** | Dementia | Dementia | n/a |265 | n/a | 1 publication

Within the data table, can we please do the following?

1. Link the value in the "Disease/phenotype" column to the relevant profile page in the Platform
2. Link the value in the "Genomics England Panel" column to the panel page using the following construct - 
`https://panelapp.genomicsengland.co.uk/panels/` + `evidences.rows[x].studyId` + `/gene/` + evidences.rows[x].target.approvedSymbol (e.g. [302](https://panelapp.genomicsengland.co.uk/panels/302/gene/GAA/))
3. In the "Literature" column, please show the number of publications and link the value to the EuropePMC search results page using the following construct, assuming `evidences.rows[x].literature` returns an array of PubMed IDs - `https://europepmc.org/search?query=` + `EXT_ID:` + `evidences.rows[x].literature[y]` + `EXT_ID:` + `evidences.rows[x].literature[y]` ... and so on (e.g. [7 publications](https://europepmc.org/search?query=EXT_ID%3A16364920%20OR%20EXT_ID%3A25435214%20OR%20EXT_ID%3A15035987%20OR%20EXT_ID%3A20130576%20OR%20EXT_ID%3A20179705%20OR%20EXT_ID%3A25907612%20OR%20EXT_ID%3A20141835))

**Important notes**

- Currently, the values for the "Allelic requirement" and "Confidence" columns are not returned by the GraphQL API, however, this data is currently being prepared for the 20.11 release and will be available shortly - please put `N/A` as a placeholder
- Within the `evidences.rows[x].literature` array, there may be `NA` values - please disregard these values as we are unable to build a relevant link to a publication

**QC checks**

- GAA (ENSG00000171298) and Glycogen storage disease due to acid maltase deficiency (Orphanet_365)
- KCNE3 (ENSG00000175538) and Brugada syndrome (Orphanet_130)
- FOXE1 (ENSG00000178919) and hypothyroidism(EFO_0004705)

**Comment by d0choa** [comment]
@ireneisdoomed can provide more details on how the evidence might change on the upcoming release.

It will be good if in the next release we don't have `NA` values in the literature field.

**Comment by ireneisdoomed** [comment]
After discussions in the daily meeting, the literature field is only added when the publications array is empty. In that case, we don't have to manage any null values.

This is an example of a current evidence string:

`{"type":"genetic_literature","evidence":{"is_associated":true,"date_asserted":"2020-11-04T12:31:39.836571","resource_score":{"type":"probability","value":1,"method":{"description":"Further details in the Genomics England PanelApp.","url":"https://panelapp.genomicsengland.co.uk"}},"provenance_type":{"literature":{"references":[{"lit_id":"http://europepmc.org/abstract/MED/27604308"}]},"database":{"dbxref":{"id":"Genomics England PanelApp","url":"https://panelapp.genomicsengland.co.uk/","version":"2020-11-04T12:31:39.836564"},"id":"Genomics England PanelApp","version":"2020-11-04T12:31:39.836552"}},"evidence_codes":["http://purl.obolibrary.org/obo/ECO_0000205"],"urls":[{"nice_name":"Further details in the Genomics England PanelApp for panel 467 and gene EARS2","url":"https://panelapp.genomicsengland.co.uk/panels/467/EARS2"}]},"access_level":"public","sourceID":"genomics_england","target":{"id":"http://identifiers.org/ensembl/ENSG00000103356","activity":"http://identifiers.org/cttv.activity/predicted_damaging","target_type":"http://identifiers.org/cttv.target/gene_evidence","target_name":"EARS2"},"disease":{"id":"http://www.orpha.net/ORDO/Orphanet_314051","name":"Leukoencephalopathy - thalamus and brainstem anomalies - high lactate","source_name":"Combined oxidative phosphorylation deficiency 12, 614924;Required for mitochondrial gene expression  (Mitochondrial respiratory chain disorders (caused by nuclear variants only));Multiple respiratory chain complex deficiencies (disorders of protein synthesis)"},"unique_association_fields":{"disease_iri":"http://www.orpha.net/ORDO/Orphanet_314051","target_id":"http://identifiers.org/ensembl/ENSG00000103356","panel_id":467,"panel_name":"Inborn errors of metabolism","panel_version":2.22,"original_disease_name":"Combined oxidative phosphorylation deficiency 12, 614924;Required for mitochondrial gene expression  (Mitochondrial respiratory chain disorders (caused by nuclear variants only));Multiple respiratory chain complex deficiencies (disorders of protein synthesis)"},"validated_against_schema_version":"1.6.9"}`

You can easily check it out [here](https://jsonviewer.io/tree). _For those evidences that do not list any publications, the `literature` field is not expected._

**Comment by javfg** [comment]
> @ireneisdoomed can provide more details on how the evidence might change on the upcoming release.
> 
> It will be good if in the next release we don't have `NA` values in the literature field and only nulls

I am filtering out those `NA` for now.

**Comment by AsierGonzalez** [comment]
There shouldn't be any. Sometimes the field will be missing but it should never be `NA`

**Comment by ireneisdoomed** [comment]
I have opened this other issue to address specifically the `Allelic Requirement` field. #1263

**Comment by andrewhercules** [comment]
With the latest iteration of the GraphQL API, can we please make some changes to the Genomics England evidence data table?

Sample query: [GAA and Glycogen storage disease due to acid maltase deficiency](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20assocs%20%7B%0A%20%20disease(efoId%3A%20%22Orphanet_365%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000171298%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22genomics_england%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20cohortPhenotypes%0A%09%09%09%09allelicRequirements%0A%20%20%20%20%20%20%20%20studyOverview%0A%20%20%20%20%20%20%20%20studyId%0A%09%09%09%09confidence%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%7D%09%09%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=assocs)

- [ ] Update "Allelic requirement" column as previously, the field was a string `evidences.rows[x].allelicRequirement`; however, it is now an array called `evidences.rows[x].allelicRequirements` with an "s".  Based on the comments in #1263, can we please show the first word and then show the rest of the string on hover - for example:

Monoallelic ... 

- [ ] Add a column called "Cohort phenotypes" (after the "Reported disease/phenotype") and display the entries in `evidences.rows[x].cohortPhenotypes` array as an unordered list

- [ ] In the "Genomics England Panel" column, instead of showing the `evidence.rows[x].studyId` value, please display the `evidence.rows[x].studyOverview` value and link the text to the Genomics England website using the same link style currently implemented

- [ ] In the "Confidence" column, in addition to showing the `evidence.rows[x].confidence` value, use an icon and colour to provide a visual cue about the two confidence levels ("green" or "amber") from Genomics England

For "green", please display the [FontAwesome check-square](https://fontawesome.com/icons/check-square?style=solid) icon in Genomics England green - `#3fad46`

For "amber", please display the [FontAwesome exclamation-triangle](https://fontawesome.com/icons/exclamation-triangle?style=solid) icon in Genomics England amber - `#f0ad4e` ([sample query](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20evidenceTable%20%7B%0A%20%20disease(efoId%3A%20%22EFO_0000589%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20evidences(ensemblIds%3A%20%5B%22ENSG00000147684%22%5D%2C%20enableIndirect%3A%20true%20datasourceIds%3A%20%5B%22genomics_england%22%5D)%20%7B%0A%20%20%20%20%20%20count%0A%20%20%20%20%20%20rows%7B%0A%20%20%20%20%20%20%20%20disease%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20diseaseFromSource%0A%20%20%20%20%20%20%20%20cohortPhenotypes%0A%09%09%09%09allelicRequirements%0A%20%20%20%20%20%20%20%20studyOverview%0A%20%20%20%20%20%20%20%20studyId%0A%09%09%09%09confidence%0A%20%20%20%20%20%20%20%20literature%0A%20%20%20%20%20%20%7D%09%09%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&operationName=evidenceTable) with "amber" results)

**Comment by d0choa** [comment]
Based on our discussions:
- Add reported disease/phenotype as tooltip in disease column. The tooltip content would be “Reported disease or phenotype:\n{diseaseFromSource}”
- Rename “Cohort Phenotypes” column to “Other phenotypes”. Replace content of the cell with a message “(n-1) other phenotypes” [when n-1 > 0], and a link to open the drawer with all the list of phenotypes. The drawer title could be "n reported phenotypes" and contain the full list of n phenotypes.
