### ISSUE TITLE
Updating ClinGen data source parser to accommodate the new JSON schema 

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1278]

**Comment by AsierGonzalez** [comment]
Code revamp to alig evidence strings with new schema complete (see [ag_clingen_new_schema_1278](https://github.com/opentargets/evidence_datasource_parsers/blob/ag_clingen_new_schema_1278/modules/ClinGen.py) branch). This is the summary of the changes made:

- JSON schema is **NOT** loaded
- Gene symbols are **NOT** mapped to Ensembl
- Evidence strings are stored as dictionaries and serialised as JSON
- The name of Gene Curation Expert Panel (`GCEP` column) is stored in the `studyId` field aking to what is done in Gene2Phenotype or Genomics England PanelApp evidence strings.
- The report url needed to link to ClinGen's website is stored in `urls`. Because the only field in version 2.0.0 of the schema that can store URLs is [clinicalUrls](https://github.com/opentargets/json_schema/blob/2.0.0/opentargets.json#L878-L900), the schema has been updated so that field is called `urls` instead (see PR [#107](https://github.com/opentargets/json_schema/pull/107)).
- Unique association fields have been removed because they are now controlled by the ETL pipeline using the [reference.conf](https://github.com/opentargets/platform-etl-backend/blob/master/src/main/resources/reference.conf) file. That file needs to be updated to include `allelicRequirements` and `diseaseFromSource` in ClinGen's unique association fields.
- The script metadata has been removed from the code
- The scoring based on the classification/confidence has been removed.

The only thing left for now is to add this step to snakemake. The work is being coordinated with @DSuveges.

**Comment by AsierGonzalez** [comment]
ClinGen unique association fields in reference.conf have been updated (see PR [platform-etl-backend/74](https://github.com/opentargets/platform-etl-backend/pull/74))

**Comment by andrewhercules** [comment]
Thanks @AsierGonzalez ! :-) 
Ticket closed as https://github.com/opentargets/platform-etl-backend/pull/74 approved and merged

**Comment by AsierGonzalez** [comment]
Two PRs that contain the migration (https://github.com/opentargets/evidence_datasource_parsers/pull/59 and [evidence_datasource_parsers/61](https://github.com/opentargets/evidence_datasource_parsers/pull/61)) have also been merged. The work to add it into snakemake will be captured in another ticket.

**Comment by AsierGonzalez** [comment]
See [#1343](https://github.com/opentargets/platform/issues/1343) for the snakemake work.
