### ISSUE TITLE
Different optimisations in javascript bundle for rewrite 

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1288]
Including lazy-loading, remove ot-ui dependency, etc.
More details to come from @javfg

**Comment by javfg** [comment]
Here is a summary of the optimizations I've made, in multiple steps:

## Starting point:
Measuring at https://github.com/opentargets/platform-app/commit/9cc1c1c51b9aa0468d62ba6a5f9dfd4b6ab91edd:

#### Build summary (gzipped):
``` 
1.35 MB   build/static/js/2.63e3c11d.chunk.js
424.1 KB  build/static/js/3.bd908a9b.chunk.js
83.51 KB  build/static/js/main.d4f4fde6.chunk.js
18.17 KB  build/static/css/2.9d7733f2.chunk.css
1.6 KB    build/static/css/main.99badbbc.chunk.css
1.18 KB   build/static/js/runtime-main.616029b2.js
756 B     build/static/js/4.30a07714.chunk.js
```
`2.63e3c11d.chunk.js` (1.35MB) is the big chunk loaded in the homepage.

#### Bundle analysis:
![image](https://user-images.githubusercontent.com/6058151/102346622-0fa4c400-3f97-11eb-99d9-acfe0d5bfd0c.png)
Total app size is 7.49MB.

#### local `serve -s build`:

I will be using a local server to avoid inconsistencies with my internet connection.

##### Lighthouse report:
![image](https://user-images.githubusercontent.com/6058151/102346792-57c3e680-3f97-11eb-891c-806039a5844d.png)

##### Home load time:
![image](https://user-images.githubusercontent.com/6058151/102346859-74601e80-3f97-11eb-83e3-b7b165dbf9cf.png)

#### Production:
##### Lighthouse report:
![image](https://user-images.githubusercontent.com/6058151/102351295-184cc880-3f9e-11eb-8680-426211f86a54.png)
##### Home load time:
![image](https://user-images.githubusercontent.com/6058151/102351665-ba6cb080-3f9e-11eb-8353-c99f20478a06.png)



This can be improved with some cleanup and code splitting.

---

## Step 1: Removing `ot-ui`
For this, I moved the following components into `platform-app`:
* DataDownloader
* DownloadSvgPlot
* EmailLink
* Footer
* HeaderMenu
* Link
* ListTooltip
* NavBar
* OtTableRF
* OtUiThemeProvider
* Page
* PlotContainer
* PlotContainerSection

This also allows us to remove the `react-select` dependency. In this step, I've also removed `d3-selection`, which was listed in `package.json` but does not seem to be used anywhere.

#### Build summary (gzipped)
``` 
  938.35 KB  build/static/js/2.2d4ae881.chunk.js
  426.69 KB  build/static/js/3.8e53ac59.chunk.js
  88.12 KB   build/static/js/main.cf4e4d94.chunk.js
  18.24 KB   build/static/css/2.b4f6c2a1.chunk.css
  1.6 KB     build/static/css/main.99badbbc.chunk.css
  1.18 KB    build/static/js/runtime-main.46fb0241.js
  754 B      build/static/js/4.4bd0a219.chunk.js
```

The chunk loaded in homepage is now 938KB, 69% the original size.

#### Bundle analysis:
![image](https://user-images.githubusercontent.com/6058151/102347375-3dd6d380-3f98-11eb-917c-d508287c1b3b.png)
Total app size is now 5.01MB.

#### local `serve -s build`:
##### Lighthouse report:
![image](https://user-images.githubusercontent.com/6058151/102347697-acb42c80-3f98-11eb-92b5-f773396a59f7.png)

##### Home load time:
![image](https://user-images.githubusercontent.com/6058151/102347635-93ab7b80-3f98-11eb-86bb-ba3cd882d519.png)

Already, there is a slight improvement in load time and size for the homepage.

---

## Step 2: Lazy loading `litemol`

As seen in the bundle analysis when we started, `litemol` package, used in target profile page, is huge (1.35MB), and is loaded in the home. Lazy-loading it requires some fiddling, as it is a webcomponent:

```javascript
import React, { useEffect, useState } from 'react';
import 'litemol/dist/css/LiteMol-plugin.css';

function ProtVistaTab({ uniprotId }) {
  const [componentLoaded, setComponentLoaded] = useState(false);

  useEffect(() => {
    async function loadProtVista() {
      const ProtVista = await import('protvista-uniprot');

      window.customElements.define('protvista-uniprot', ProtVista.default);
    }

    if (
      window.customElements &&
      !window.customElements.get('protvista-uniprot')
    ) {
      loadProtVista();
    }
    setComponentLoaded(true);
  }, []);

  return !componentLoaded ? (
    <>Loading...</>
  ) : (
    <protvista-uniprot accession={uniprotId} />
  );
}

export default ProtVistaTab;
```

#### Build summary (gzipped)
```
  555.25 KB (-383.1 KB)  build/static/js/2.df909acd.chunk.js
  426.67 KB (-21 B)      build/static/js/3.1eb53409.chunk.js
  382.43 KB (+381.7 KB)  build/static/js/4.8ff7fab9.chunk.js
  88.17 KB (+52 B)       build/static/js/main.01bd7e1d.chunk.js
  18.2 KB (-44 B)        build/static/css/2.61c47300.chunk.css
  1.56 KB (-44 B)        build/static/css/main.edd9e0e2.chunk.css
  1.15 KB (-31 B)        build/static/js/runtime-main.30912aee.js
  715 B                  build/static/js/5.3c83da58.chunk.js
```

The chunk loaded at home is now 555KB, which is 41% the original size.

#### local `serve -s build`:
##### Lighthouse report:
![image](https://user-images.githubusercontent.com/6058151/102349683-9fe50800-3f9b-11eb-86ba-e6f98b3b0a80.png)

##### Home load time:
![image](https://user-images.githubusercontent.com/6058151/102348464-dd489600-3f99-11eb-9223-620a1d228014.png)

There is a load time improvement, but it is hidden because of the reactome plugin load, which is being done in the home page:
![image](https://user-images.githubusercontent.com/6058151/102348650-1b45ba00-3f9a-11eb-98a4-382e47c857f5.png)

Also, the data tranferred has gone done from 3.2MB to 1.8MB, a 56% of its original size.


---

## Step 3: Lazy loading `reactome` plugin

Similar to step 2, we can take out the reactome plugin from the html template and load it using `react-helmet` in the relevant component (`Pathways` section in target profile page):

```javascript
<Helmet
  script={[
    {
      src:
        'https://www.reactome.org/DiagramJs/diagram/diagram.nocache.js',
    },
  ]}
/>
```

As this package is not bundled, the size stays the same. The load is done asynchronously and the home page usable while reactome loads. But arguably, users and the reactome server will benefit from not tranferring the 600+KB unless it is actually needed.

#### local `serve -s build`:
##### Lighthouse report:
![image](https://user-images.githubusercontent.com/6058151/102350033-2c8fc600-3f9c-11eb-966f-e96ae08750d0.png)

##### Home load time:
![image](https://user-images.githubusercontent.com/6058151/102349797-cdca4c80-3f9b-11eb-8971-59917f37a397.png)
![image](https://user-images.githubusercontent.com/6058151/102349623-8774ed80-3f9b-11eb-9e3e-068bb4a860d2.png)


The improvement is now more obvious, the page takes only ~455ms to load, and the initial transfer size is 1.2MB.


## Step 4: Lazy loading `expression-atlas` CSS

Similar to step 3. Expression atlas component was already lazy loaded, but its CSS is loaded in the home. It is only a 33KB download, but from an external cdn and not needed in home. I am not detailing the improvement because it should be negligible. But it is still a good step in cleaning up the initial load.

## Step 5: Lazy loading `cttv` and `tntvis` components

This requires some more fine tuning, as these are legacy libraries. This improvement generates a big number of new bundles, and does not reduce the size dramatically. Nevertheless, according to lighthouse, the improvement is worth it.

The code for this step is in https://github.com/opentargets/platform-app/commit/3efa985e3174a8db403c57ce42017e5f0df344e0.


#### Build summary (gzipped)
```
  496.35 KB  build/static/js/7.2f790bbd.chunk.js
  426.75 KB  build/static/js/8.c3b32d71.chunk.js
  384.74 KB  build/static/js/11.770e91c1.chunk.js
  89.35 KB   build/static/js/main.579b0b44.chunk.js
  33.03 KB   build/static/js/9.b5c4eff2.chunk.js
  18.19 KB   build/static/css/7.891edd6a.chunk.css
  9.01 KB    build/static/js/10.74503480.chunk.js
  7.28 KB    build/static/js/3.8ae6a9bb.chunk.js
  6.88 KB    build/static/js/0.fdabaca1.chunk.js
  5.86 KB    build/static/js/13.4f8ca1d6.chunk.js
  5.19 KB    build/static/js/2.cc19ddaf.chunk.js
  4.54 KB    build/static/js/4.79701745.chunk.js
  4.17 KB    build/static/js/1.2b37d70b.chunk.js
  2.98 KB    build/static/js/12.26bbd095.chunk.js
  2.03 KB    build/static/js/14.952bc96d.chunk.js
  1.68 KB    build/static/js/15.f4eb9ca8.chunk.js
  1.56 KB    build/static/css/main.edd9e0e2.chunk.css
  1.3 KB     build/static/js/runtime-main.d3efdd39.js
  717 B      build/static/js/16.8ce14616.chunk.js
  108 B      build/static/js/17.01f8b5fd.chunk.js
  108 B      build/static/js/18.64b189c5.chunk.js
  108 B      build/static/js/19.27dc3d3f.chunk.js
  98 B       build/static/js/20.284808c3.chunk.js
```

The big chunk loaded in the home page is now split in two, 496KB + 89KB, the size has not changed much.

#### Bundle analysis:
HERE MISSING
![image](https://user-images.githubusercontent.com/6058151/102353421-e9842180-3fa0-11eb-9bc8-b9a8fd43a527.png)


#### local `serve -s build`:
##### Lighthouse report:
![image](https://user-images.githubusercontent.com/6058151/102351203-f5221900-3f9d-11eb-90a0-d91bfe2b9f02.png)

##### Home load time:
![image](https://user-images.githubusercontent.com/6058151/102351044-b68c5e80-3f9d-11eb-8f17-2182171d2582.png)
![image](https://user-images.githubusercontent.com/6058151/102350968-9c528080-3f9d-11eb-9901-341f30f6d281.png)


#### Production:
##### Lighthouse report:
![image](https://user-images.githubusercontent.com/6058151/102352964-61058100-3fa0-11eb-83b6-83b8d4a53e5f.png)

##### Home load time:
![image](https://user-images.githubusercontent.com/6058151/102352908-4b905700-3fa0-11eb-879d-4e3cc465c598.png)

---

### Conclusions

* Overall, the page has doubled loading speed in a below average internet connection, tripled when using a fast connection.
* Bundle size was 7.49MB, and is now 5.12MB, a 31% reduction.
* Resources loaded in the home page were 3MB, and are now 1MB, a 66% reduction.
* We have jumped from a 66 performance score in lighthouse, to 94. Now the meter is green! :)

### Things to do:

* A second version of `d3` is being loaded in the home, this could be removed or lazy loaded too.
* Change old tables using `OtTableRF` to the new component and drop the old one.
* Consider using only two versions of inter font, dropping either `light` or `medium.
