### ISSUE TITLE
Resolve bug in Safari causing disease page to crash

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1302]
The bug happens to occur sometimes, but it causes the whole page to crash.
More details soon

**Comment by d0choa** [comment]
I've been browsing the site all day and I believe this problem has gone away with the recent changes in the javascript bundle. I'll reopen if necessary

**Comment by d0choa** [comment]
Yep it's still happening

**Comment by mirandaio** [comment]
The disease page was crashing due to a race condition introduced by the driver rework. That's why it happened some times and not other times. This PR https://github.com/opentargets/platform-app/pull/273 fixes that race condition.

@d0choa let me know if it is still happening on beta. I'm keeping this issue open in the meantime.
