### ISSUE TITLE
Create static /variants page in rewrite version

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1311]
In the Angular version of the Platform, we have a static /variants page - https://www.targetvalidation.org/variants - that displays definitions of variants and their functional consequence score. The page is well-indexed by Google and has a click-through rate of 10-25% depending on the variant term.

Can we please import the content of the /variant page into the React version of the Platform and serve at the same /variant URL?

The content is currently raw HTML in a table - see the [variants.html file in the webapp repo](https://github.com/opentargets/webapp/blob/master/app/src/pages/static/variants.html). Would it be easier to transform the content into a static JSON file and have the React application consume the data in JSON format?

**Comment by LucaFumis** [comment]
I've created the variants page: the table data is stored in the page js file (i.e. not separate external json file) which should be easier to update than the current static html.

In the angular app, the variants page is actually linked to from the common diseases table (column headers: "variant" and "variant types") in the evidence page.
Do we want to replicate the same in the react app? 
Otherwise the page can only be reached by typing the url...

**Comment by andrewhercules** [comment]
Thanks @LucaFumis! For now, we can leave the page as it is and not link to it. Because of changes to the score, I don't want to link to the page and confuse users. Instead, I will link from the documentation. 👍

**Comment by LucaFumis** [comment]
This is now done and merged in beta.

**Comment by andrewhercules** [comment]
Ticket closed as work merged into `beta`
