### ISSUE TITLE
Target Step rewrite EPIC

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1313]
EPIC to rewrite the gene step in the new ETL pipeline

Details TBC.

**Comment by JarrodBaker** [comment]
Overview of Target re-write. There are two broad things that need to be done:
- Finish Target/Target Safety and API
- Update all related steps

### Target

Outstanding:
 - bug with duplicate results see opentargets/platform#1537
 - API
 - target safety

### Target Safety

This was previously part of target-DP. It will be it's own data set in the ETL, with it's own index and 
API entries. 

See branch `split-target-safety`

### Update downstream steps

| Step | Estimated effort | 
|---|---| 
|Associations | No change | 
|AssociationsOTF | Difficult | 
|Cancer Biomarkers | Difficult | 
|Drug | Easy | 
|Evidence | Medium |  
|Known Drugs| Easy | 
|Interactions| Medium | 
|Mouse Phenotypes| Difficult | 
| Reactome | No change | 

### Associations 

Does not appear to actually have any dependency on target. 

Running `egrep -rn 'targets|configuration' Association.scala` results in: 

```
1:package io.opentargets.etl.backend
7:import io.opentargets.etl.backend.spark.Helpers.mkRandomPrefix
8:import io.opentargets.etl.backend.spark.{Helpers => H}
9:import io.opentargets.etl.backend.spark.IoHelpers.IOResources
10:import io.opentargets.etl.backend.spark.{IOResource, IoHelpers}
97:         by configuration file application.conf when the known datasource is specified
118:        * join weight per datasource from configuration section `otc`
119:        * @param otc from ETL configuration section
146:        val associationsSec = context.configuration.associations
169:    val associationsSec = context.configuration.associations
172:      "evidences" -> context.configuration.associations.inputs.evidences,
173:      "diseases" -> context.configuration.associations.inputs.diseases
208:    val outputs = context.configuration.associations.outputs
226:    val outputs = context.configuration.associations.outputs
246:    val associationsSec = context.configuration.associations
278:    val associationsSec = context.configuration.associations
```
It looks like the input dataframe is never actually read. 

### AssociationsOTF

- This needs to be updated. Columns used:

```
    val targetColumns = Seq(
      "id as target_id",
      "concat(id, ' ', approvedName, ' ', approvedSymbol) as target_data",
      "proteinAnnotations.classes as facet_classes",
      "reactome",
      "tractability"
    )
```

- reactome is not a field on Target-ETL.
- proteinAnnotations has changed structure.
- possible changes in tractability: need to dig into the RDF more. 

### Cancer Biomarkers

### Drug

- called `geneDf` in Drug step (targetDF refers to ChEMBL target). 
- uses fields:
  - `id`
  - `proteinAnnotations.id`
- To update: 
  - use fields `id` and `proteinIds.id`

### Evidence

- Used in `resolveTargets` and `excludeByBiotype` methods
- resolveTargets:
  - used to create `lut` (ln 440) created by calling `generateTargetsLUT`
  - Uses fields:
    - id
    - proteinAnnotations.id
    - proteinAnnotations.accessions
    - approvedSymbol
    - symbolSynonyms
    - targetSymbol << no idea there this comes from
    - targetName << ditto
  - To fix need to use fields approvedSymbol, proteinIds, synonyms, id

- exlcudebybiotype uses only biotype and id (see ln: 376) 


### Known Drugs

- Used fields:
  - id
  - approvedSymbol
  - approvedName
  - proteinAnnotations.classes.l1.label
- To update
  - proteinAnnotations is now proteinIds and is now 'targetClass'. Filter by level and then take label.

### Interactions

- used in generateMapping (ln 67). 
- fields used: 
  - proteinAnnotations.accessions
  - id
  - hgncId
- to update:
  - `hgncId` is now is `dbXrefs`
  - `proteinAnnotations` is now in `proteinIds`

### Mouse Phenotypes

This is generated as part of the target step in the data pipeline. 

Using the output of the DP, we extract the ENSG and MP into a new json document using:

```
cat 20.04_gene-data.json | jq -r '{"id":.id,"phenotypes": [.mouse_phenotypes[]?] }|@json' > mousephenotype.json
```

This has the output format 

```
root
 |-- id: string (nullable = true)
 |-- phenotypes: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- mouse_gene_id: string (nullable = true)
 |    |    |-- mouse_gene_symbol: string (nullable = true)
 |    |    |-- phenotypes: array (nullable = true)
 |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |-- category_mp_identifier: string (nullable = true)
 |    |    |    |    |-- category_mp_label: string (nullable = true)
 |    |    |    |    |-- genotype_phenotype: array (nullable = true)
 |    |    |    |    |    |-- element: struct (containsNull = true)
 |    |    |    |    |    |    |-- mp_identifier: string (nullable = true)
 |    |    |    |    |    |    |-- mp_label: string (nullable = true)
 |    |    |    |    |    |    |-- pmid: string (nullable = true)
 |    |    |    |    |    |    |-- subject_allelic_composition: string (nullable = true)
 |    |    |    |    |    |    |-- subject_background: string (nullable = true)
```

The ETL reads in this json file, and writes out the result without further manipulation. 

This needs to be completed implemented in the ETL. The DP is processing RDF files for some of it, so those transformations might be better in PIS since we already have that set up for dealing with ontology files. 

### Reactome

Reactome-ETL has no dependencies.

When the Target-DP is run, Reactome-DP is a requirement.

**Comment by ktsirigos** [comment]
@JarrodBaker you can close this now :)
