### ISSUE TITLE
Reactome: Link out to Open targets

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#134]
Reactome have confirmed that they plan to get this in place for their Dec2018 release.

Once question posed by them:
Currently, they will probably be using the associations files to create the data for the link-outs. The only question I have at this point is: the file names (here: https://www.targetvalidation.org/downloads/data) all contain the date the files were released. Is there a link somewhere that will always point to the most recent associations file?

@MichaelaEBI to meet with them whilst in CA to confirm best approach to get this in place.

- FE team can be consulted from there on what may be required from our side to automate.

**Comment by MichaelaEBI** [comment]
Update: I met Solomon in Toronto in early October. We agreed that OT would make a file available with UniProt and Ensembl IDs for all proteins that have disease associations so that they can link to our target association page from reactome. They would be happy to eventually also link out to our disease association pages. Links from reactome to Open Targets should be ready for their December release.

Action for OT: Generate a file with UniProt Accession numbers and Ensembl IDs for all targets that have associations. Always store the latest version of the list in a google bucket - file and bucket names should not change. This might be useful for other platforms that might want to link out to OT target association pages.

**Comment by MichaelaEBI** [comment]
Done: Link to Open Targets in the cross references section https://reactome.org/content/detail/R-HSA-167224

I emailed Solomon to change 'OpenTargets' to 'Open Targets'. We will have to make sure to provide an updated target list to them. They might link out to our disease profile pages in the future.
