### ISSUE TITLE
Disease profile page: Mouse over similar disease does not work on IE11

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/platform#137]
e.g. https://www.targetvalidation.org/disease/EFO_0003898
Mouse over on a node will generate a JS error on IE11. 
Note that it works for similar targets.

**Comment by LucaFumis** [comment]
Done brief initial investigation with @gkos-bio: the mouse events are triggered correctly, but the functions call seem to fail. Have one more quick test to try.

**Comment by ElaineMcA** [comment]
Will be investigated with 19.02 in mind.  Ticket will be updated accordingly.

**Comment by peatroot** [comment]
The issue seems to be in a third party library, [venn.js](https://github.com/benfred/venn.js), which conditionally uses `node.getComputedTextLength()` to see if text needs to be wrapped for long labels in the Venn diagram (that appears in the pop-up on hover). This method is [not guaranteed to work in IE11](https://stackoverflow.com/questions/19122753/getcomputedtextlength-throws-an-error-in-ie10).

The conditionality below explains why it's not a problem for targets (they have short names, so the second boolean is never calculated):
```
if (joined.length > minChars && tspan.node().getComputedTextLength() > width) {
  // ... wrap the text
}
```

**Comment by peatroot** [comment]
Suggested resolutions:
A: The target profile page proof-of-concept contains a different design for related targets, which may or may not use venn.js, so we could ignore this problem until the proof-of-concept is live.
B: It might be possible to solve this by forking and tweaking the venn.js library, then switching to that version, though this feels like overkill, given the small number of users affected and the possibility of (A).

Thoughts, @LucaFumis @ElaineMcA ?

**Comment by ElaineMcA** [comment]
@peatroot I agree that we should resolve things via moving to new framework where at all possible i.e. via option A.  Can you please outline for me the key steps and estimate of effort required for each step to push POC to production post Integration.  Happy to sit down and plan that more together - high level outline is a start.

**Comment by ElaineMcA** [comment]
POC planning discussed at FE meeting 09Jan2019, minutes for which are here: https://docs.google.com/document/d/1eZH0PAsHKLWJgdn3ZNX0OPfzFut_KkWVwmREzenVXgs/edit

**Comment by ElaineMcA** [comment]
#246

**Comment by d0choa** [comment]
Closing as no action is expected in the angular app
