### ISSUE TITLE
Resolve "duplicate" entries in pharmacovigilance data 

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1382]
Currently, the pharmacovigilance data adverse event labels are mapped to MedDRA IDs. However, some of the terms have  multiple IDs and we expand/duplicate the data for each entry.

This leads to the appearance of duplicated entries, although each row has a different MedDRA ID. For example, [CHEMBL122 - rofecoxib](https://www.targetvalidation.org/summary?drug=CHEMBL122) has 43 entries for "acute myocardial infarction", each with a different MedDRA ID.

![Screenshot 2021-02-08 at 17 40 23](https://user-images.githubusercontent.com/7490258/107259298-bdcb6800-6a34-11eb-8a10-eb72b99bf07c.png)

Instead, can we please update how we process the raw data so that a single row in the pharmacovigilance data can have an array of MedDRA IDs? 

We can then adjust the front-end to make use of the drawer component to show multiple IDs.

**Comment by d0choa** [comment]
Apologies because I originally thought exploding them wouldn't be an issue. However, some one2many relationship between meddra labels - ids are too much. Adding the meddra ids as a nested array sounds like the best solution

**Comment by JarrodBaker** [comment]
@d0choa This turned out to be a data generation issue, and the original duplication problem was solved a while ago. I've regenerated the index and things appear to be working as they should. The 'bug' looks to be in how we run the FAERS pipeline. Because it's separate from the ETL it's a bit trickier to make sure that we use the correct code version and data. I'll update the documentation to try and make sure things work better in future.
