### ISSUE TITLE
Create recombinantMolecule / naturalGene lookup table

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#1417]
After discussion on #1406, we concluded that creating a mapping file between recombinant molecules (drugs) and naturally occurring genes/proteins would be the best approach, due to the lack of appropriate references between the different resources: ChEMBL, Uniprot and DrugBank.

Starting from all the ChEMBL molecules in which `drugType == "Protein"` (n = 455), we want to obtain the corresponding Ensembl Gene Id of the naturally occurring protein. Only a fraction of the peptide drugs will be recombinants of naturally occurring proteins. While some drugs and genes have the same name (e.g. Insulin) others don't (e.g. Albumin vs Albumin Human). DrugBank can also be used as proxy to confirm some of the mappings.

**Comment by ireneisdoomed** [comment]
A large proportion of the drugs tagged as `protein` or `enzyme` (n=531) can be linked to their endogenous equivalent, either human or from another species. 

To do the annotation work I have consulted various resources such as DrugBank, Wikipedia and other bibliography to find the name of the naturally occurring peptide for each drug and its ID in Ensembl or UniProt. 

Here is the link with the WIP annotation: https://docs.google.com/spreadsheets/d/1OuY4dDAQZLp2_CyYD5-hXGgZ3dyvZUMyHpRvpL--nBo/edit?usp=sharing

We want to incorporate this dataset into the new target object under the `recombinantMolecules` field. Please note that this field is an array of Ensembl or UniProt IDs when the target is non-human.

**Comment by ireneisdoomed** [comment]
All peptide and enzyme drugs have been annotated and uploaded to the spreadsheet.
https://docs.google.com/spreadsheets/d/1OuY4dDAQZLp2_CyYD5-hXGgZ3dyvZUMyHpRvpL--nBo/edit?usp=sharing

**Comment by ireneisdoomed** [comment]
In order to incorporate this annotation in the target object (under recombinantMolecules) I have generated a static table with the available curation here `gs://ot-snapshots/recombinantMolecules/recombinantMolecules/recombinantMolecules.tsv`.

Reading from a spreadsheet is a messier process and the annotation is not expected to undergo major changes anyway.

The spreadsheet is available in the Data Shared Drive and will be checked every 6 months for any outstanding drugs to be annotated.
