### ISSUE TITLE
Change tooltip styling

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1430]
Based on feedback about the `Beta` release, users are unaware that the `?` is a tooltip with on-hover functionality that shows relevant information (e.g. reported disease/phenotype).

![Screenshot 2021-03-15 at 09 29 05](https://user-images.githubusercontent.com/7490258/111132556-69eefa00-8571-11eb-87fc-49b303aac928.png)

Can we please adjust the styling and add a `bottom-border: 1px dotted #5a5fef` style to provide users with a visual cue that the element can be interacted with?

![Screenshot 2021-03-15 at 09 32 43](https://user-images.githubusercontent.com/7490258/111132708-9440b780-8571-11eb-933a-d6ecbad2ce6b.png)

**Comment by d0choa** [comment]
This was an issue on the first place. We moved from the bubble with the question mark to the pure `?` character because it was not clear. Also the underlining is not a very clean solution. I tried in one of the evidence pages and it puts way too much focus on the question mark. It's a tricky problem.

We could try to do some simple A/B testing with the rest of the team to ask which one they prefer.

**Comment by andrewhercules** [comment]
Removed from 21.09 release and re-scoped for 20.11 release

**Comment by andrewhercules** [comment]
After reviewing stats and user feedback, we have decided to keep the `?` tooltip style. If we receive additional feedback, we can consider redesigning the tooltip.
