### ISSUE TITLE
ranking of the targets on the disease associations page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#147]
We tend to get this question a lot:

"Why is target A ranked before target B if both have the same overall score of 1".

I thought target A would have a slightly higher overall score than B, which puts A before B in that table. This raw and "real" score would be accessible via the API, so A could be 1.005 and B would be 1.002, hence A before B.

Using this example: https://www.targetvalidation.org/disease/EFO_0000305/associations I can see that my understanding was wrong: both A and B (now BRCA2 and BRCA1) have the same overall score even when the data is obtained via the API. The overall score is 1 for BRCA2, BRCA1 and 178 other targets:

https://api.opentargets.io/v3/platform/public/association/filter?&disease=EFO_0000305&scorevalue_min=0.999

How can a user understand our ranking?
What makes BRCA2 "more relevant" than BRCA1? Is it the GWAS score of 1 for BRCA2, and zero for BRCA1? But BRCA1 has higher scores for Europe PMC, EVA somatic, PhenoDigm, SLAPenrich.

[ranking_targets sheet 1.pdf](https://github.com/opentargets/platform/files/2442408/ranking_targets.sheet.1.pdf)

As soon this is clearer, I will write a FAQ or/and provide the answer in more details on the docs.

**Comment by d0choa** [comment]
Whereas the score displayed in the UI is capped to 1, the truth is that the underlying score might go above that number. In the above example, BRCA2 might have an harmonic sum of 1.5, whereas BRCA1 might have a score of 1.2. Both are displayed as a score of 1, but the underlying score is used for sorting.

This behaviour is not ideal as it's very opaque for users. For this reason, the new associations back-end will work to normalise these scores so that both BRCA1 and BRCA2 have a score between 0 and 1 and are displayed appropriately.

We might want to write a more extense documentation for the new behaviour when the time comes.
