### ISSUE TITLE
Multiple rows for the same toxicity class

### ISSUE THREAD

**Issue by ireneisdoomed** [opentargets/platform#1506]
Fiona from ChEMBL has made us aware of the presence of multiple records describing the same toxicity class in the drug warnings widget, see `Misuse` and `Respiratory toxicity` for [OXYCODONE](https://platform.opentargets.org/drug/CHEMBL656).

![image.png](https://images.zenhubusercontent.com/5f75e0f36450e0760fe97777/e3a870b9-b2fc-4784-aa3a-88e9e44f24bb)

As noted by @andrewhercules, this is due to the fact that one of the records is coming from the parent molecule and the other from the child:
- [Oxycodone hydrochloride](https://platform.opentargets.org/drug/CHEMBL1200890) has 4 FDA entries for both respiratory toxicity and misuse
- [Oxycodone](https://platform.opentargets.org/drug/CHEMBL656) only has one FDA entry for respiratory toxicity and one for misuse

This granularity is not apparent when viewing the page, giving the impression that the data is duplicated. We have two options:
1. Group the data according to toxicity class so that everything is on the same level, which is what ChEMBL has implemented on its website - see [CHEMBL656](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL656/).
2. Add a column identifying the molecule to which the warning refers. While making use of this granularity seems the most logical alternative, I am not sure whether the solution would be to obtain the warning-molecule corresponde from the warnings dataset or whether the logic has to come from the FE. @andrewhercules was suggesting something like changing the schema and adding a flag like `inheritedFromChild` or `inheritedFromParent` so that the front-end could flag warnings where they have been inherited.

**Comment by JarrodBaker** [comment]
Option 1 is very simple to implement as it can be done in the API. 

Option 2 would require much more significant changes. It also raises the question of whether this should be the default behaviour for other fields in which we hide inheritance relationships such as mechanism of action.

**Comment by DSuveges** [comment]
My two cents are on option 1 too. In this case I'm not sure if it worth capturing the full complexity. It seems option would make the UI more crowded as well making the data harder to interpret by the user.

**Comment by d0choa** [comment]
If we go for option 1, we also loose the granularity of which references report one molecule or another. 

In terms of consistency, I see no ideal solution here. We have different types of implementations already. For example, we go for Option 1 for MoAs but we go for option 2 for ontology propagation of evidence.

Tricky

**Comment by andrewhercules** [comment]
As noted in the conversation above, we will proceed with option 1 for two key reasons:

1. It follows the same approach we take with indications and mechanisms of action
2. The data can be resolved at the API level, giving us the flexibility to change our approach at a later date (if needed)

@JarrodBaker for 21.06, can you please adjust the API so that data is aggregated by the toxicity class and warning code? And so if we take the example above — CHEMBL656 —  there would only be 4 rows in the table (1 x withdrawn warning, 1 x misuse, 1 x respiratory toxicity, 1 x cardiotoxicity).

This may cause some duplication with the external links and references as both the parent and child molecule may use the same FDA entry. However, this should be discussed upstream with ChEMBL.
