### ISSUE TITLE
Automatically generate ElasticSearch image

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1514]
As someone responsible for DevOps at Open Targets, I want an automated, repeatable way to create an Elasticsearch image of a data release so that I can create the infrastructure necessary for a release. 

Given the ETL has run and generated files in _my\_bucket\_of\_dinosaurs_, 
When I execute the command `pos create elasticsearch --data=_my\_bucket\_of\_dinosaurs_`
Then I expect I can navigate to `GCP > compute instance > instance template` menu, I see a new instance template configured with Elasticsearch and pre-populated with the data from _my\_bucket\_of\_dinosaurs_

**Comment by cmalangone** [comment]
What about `pos create elasticsearch --data=_my\_bucket\_of\_unicorns_ ` ?

**Comment by JarrodBaker** [comment]
@cmalangone I was thinking that we typically run the ETL and write to some output directory which the ES scripts we have now use as a 'base' to find the data. We could use a `reference.conf` file in POS or arguments to configure the necessary data parameters (or both). Is that what you mean?

**Comment by cmalangone** [comment]
@JarrodBaker  :We could use the reference.conf or any conf file used during the creation of the release.

I pushed a first draft for this task:
https://github.com/opentargets/platform-output-support
This is just the code for using terraform in order to create the elasticsearch.

The best way to create the ES is using a docker image. 
Google Cloud offers a specific cos-stable version for running docker image.

Cos-stable image has a limitation about what you can install inside the vm.
https://cloud.google.com/container-optimized-os/docs/concepts/features-and-benefits

The insertion of the data will be done by another VM that can have a generic use inside the POS processes.

@JarrodBaker @mkarmona @mbdebian

**Comment by mbdebian** [comment]
In fact, we can create an attachable compute storage volume where to store the processed data, and use the binaries from Docker for running the services.
This storage volume can be used as template, I think, for new storage volumes that will get attached to new machines.

**Comment by cmalangone** [comment]
This task is completed.
Available in platform-output-support.
