### ISSUE TITLE
Target object iteration 7 review

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1537]
Objective is to be able to provide feedback to @JarrodBaker on potential issues on the latest target iteration and also on diagnosing remaining tasks.

**Comment by d0choa** [comment]
Pasting my findings here as I notice things worth following up:

- [ ] Less TEPs??
```
>>> new.filter(F.col("tep").isNotNull()).select("id", "tep.*").count()
30
>>> old.filter(F.col("tep").isNotNull()).select("id", "tep.*").count()
39
>>> 
```

**Comment by andrewhercules** [comment]
I agree with @d0choa about removing the `value` column and only keeping rows where `value` == `true`. The underlying dataset is quite sparse and returning all rows will make the API response larger than it needs to be.

**Comment by JarrodBaker** [comment]
The only argument I can see for adding a source to `transcriptIds` is if we expect there is a high likelihood of further sources being added in the future. Overall the flatter the structure the easier it is to work with so I'd vote for ditching it for now (using an array as David suggested) and add it back in later should it become necessary.

**Comment by JarrodBaker** [comment]
I've updated the Target step with the following changes:
  - flattened `geneticConstraint` so that fields `upperBin`, `upperBin6` and `upperRank` are at the same level as the other fields and have values when `constraintType` is `lof` and is otherwise `null`. 
  - updated `transcriptId` so that there is no longer a listed source. If we wish to revert this in future revert commit `2d9a8730447653fe6ee87b4e010bdef6ae65da9a`
  - tractability no longer has a `value` field I threw away all the `false` ones.

The issue with TEP was a bad input file and is now fixed.

In relation to GO we will create a separate index like HPO. I've created a [ticket](https://app.zenhub.com/workspaces/open-targets-issue-tracker-58a421fd8c85e652659a1486/issues/opentargets/platform/1547) which I'll polish this week.

As far as I know the safety liabilities structure is as requested from the data team, so I haven't made any changes there. 

The outputs can be found at `gs://ot-team/jarrod/target-outputs/v8`.

I'm now moving onto updating the API to serve the new schema, and identifying which of the downstream steps in the ETL require updating (hint ~ basically all of them)

If there is no more feedback on this ticket I'll close it on Friday.

**Comment by DSuveges** [comment]
My comments on the changes:

* Removing `transcriptId.source` is a good idea: I think it is absolutely unlikely we would import transcripts from anywhere else but Ensembl.
* On Hallmarks fusion proteins mentioned by @d0choa: yes, absolutely we should reference them. That would allow users the traverse across our target pages. I want to check two things before that: 1) do all fusion partners identified with their approved symbol 2) is the hallmark annotation symetric: if protein A has a hallmark annotation and is fused with protein B, the same hallmark annotation is available for protein B as well.

I have one question/comment about alternative identifiers: some genes are seemingly split into separate target entries with no link between them. Eg. * CCL4L2*. If we look up this symbol we have the following entires:

```
+---------------+----------------------------------+------------------------------------+--------------+--------------------------------------------+
|id             |alternativeGenes                  |approvedName                        |approvedSymbol|genomicLocation                             |
+---------------+----------------------------------+------------------------------------+--------------+--------------------------------------------+
|ENSG00000275313|[ENSG00000276125, ENSG00000282604]|C-C motif chemokine ligand 4 like 2 |CCL4L2        |[CHR_HSCHR17_10_CTG4, 36314484, 36312669, 1]|
|ENSG00000276070|null                              |C-C motif chemokine ligand 4 like 2 |CCL4L2        |[17, 36212878, 36210924, 1]                 |
+---------------+----------------------------------+------------------------------------+--------------+--------------------------------------------+
```
I think this gene is probably split into two entries because the genes on the alternative locations have reviewed protein products (as on ticket #1381 ), however I don't know why there's no link between them: the `alternativeGene` field is set for the first one, listing two alternative gene identifiers, however all three are alternatives for the fourth (`ENSG00000276070`)  gene ID (as also shown on the [Ensembl search results](http://www.ensembl.org/Multi/Search/Results?q=CCL4L2;site=ensembl)). Also when looking at targets with `alternativeGenes`, the location is always a scaffold, not a canonical chromosome. I think it would make sense to somehow link all the "alternative" gene IDs to the gene on the canonical chromosome as we are supporting target search by ensembl gene identifier. (This might cause confusion on the search though when the same gene symbol is listed twice without an further information provided, but such cases already exist eg. for U6, U2 etc)

**Comment by d0choa** [comment]
My understanding is the same as @DSuveges. That these 2 entries should indeed be 1 entry in which all the others become `alternativeGenes` of `ENSG00000276070`. Sorry because I might not have been very clear in my previous specifications.

1. All genes in 1-23, X, Y, MT stay
1. For the ones in other assemblies:
   1. Discard if they don't encode for a Uniprot swissprot ("reviewed") protein
   1. If they encode for a reviewed protein
      1. if they have the same approvedSymbol as an already accepted target include them as `alternativeGenes` of the first one
      1. if they contain a novel `approvedSymbol`
         1. Take the longest gene as reference entry
         1. Include all the rest as `alternativeGenes`


How does it sound @JarrodBaker and @DSuveges ?

**Comment by DSuveges** [comment]
@d0choa sounds about right, I only see one caveat though: if a gene on an alternative location has approved protein product, that protein product might get separate annotations potentially conflicting with the one located on the canonical chromosomes (2.ii.a). But it would surely have marginal impact.

I see no problem if all gene IDs on alternative assemblies would be added to `alternativeGenes` if the `approvedSymbol` matches with a gene on canonical chromosomes.

**Comment by ireneisdoomed** [comment]
The target safety schema has a new version ([iter 4](https://docs.google.com/spreadsheets/d/1W_KJoozote06h3-mrVeHZN02VVXrpwG42nhGjUR-0Gk/edit?ts=606ecf7d#gid=1514939258)):

1. safetyLiabilities shall be a separate dataset from the target object, so in addition to the evidence object, we shall specify the `id` of the target.
2. `effects` is no longer an aggregation of effect direction and dosing. For each event, we want to show how the target is modulated in an array of objects. 
3. If `effects.dosing` or `effects.direction` are not specified in the source, this field will not be present. This is the case for example for Bowes et al. (2012), where we never have dosing information.
- For the adverse effects dataset we did not take into account these fields could be unspecified, therefore they were not captured. 
- The events for Bowes et al. (2012) are not captured, probably as a consequence of the last point. The ones we are capturing are the ones for Lynch et al. (2017) for the same gene (cell E62 and I62). [Spreadsheet here](https://docs.google.com/spreadsheets/d/1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0/edit#gid=1760619926).
```
(v6
	.filter(col("id") == "ENSG00000133019")
	.filter(col("evidence.datasource") == "Bowes et al. (2012)")
	.select("evidence.event").distinct()
	.show(100,truncate=False))

+------------------------------------------+
|event                                     |
+------------------------------------------+
|decreased pupil diameter                  |
|liver failure                             |
|centrilobular liver congestion            |
|muscle cramps                             |
|increased pupil diameter                  |
|lacrimation                               |
|bronchospasm                              |
|blurred vision                            |
|abdominal cramps                          |
|irritability                              |
|bronchorrhea                              |
|acidosis                                  |
|bronchoconstriction                       |
|decreased intestinal transit              |
|ptosis                                    |
|constipation                              |
|exhaustion                                |
|decreased gastric emptying                |
|increased salivation                      |
|diarrhea                                  |
|increased respiratory rate                |
|decreased salivation                      |
|increased/decreased blood pressure        |
|pleural effusions                         |
|increased body temperature                |
|dry mouth                                 |
|frothing                                  |
|increased/decreased heart rate            |
|neutrophil collection within the sinusoids|
|sweating                                  |
|cough                                     |
+------------------------------------------+
```
4. New array of structs `assay`. For Tox21 we can have several assay results supporting the same event.
5. New dataset for the Tox21 source. The current input file is pulled by PIS. The new file containing the new fields that were missing in the data for the last iter is located in this bucket: `otar001-core/ExperimentalToxicity`
6. We are losing associations that were present in the production index for Bowes et al. (2012) (23), HeCaToS (25) and Urban et al. (2012) (25). This is probably related to the issue mentioned above. Some examples: 

```
# Bowes et al. (2012)
(v6
	.filter(col("id") == "ENSG00000181072")
	.filter(col("evidence.datasource") == "Bowes et al. (2012)")
	.select("evidence")
	.show(100,truncate=False)) --> None

# Urban et al. (2012)
(v6
	.filter(col("id") == "ENSG00000180210")
	.filter(col("evidence.datasource") == "Urban et al. (2012)")
	.select("evidence")
	.show(100,truncate=False)) --> None

# Hecatos
(v6
	.filter(col("id") == "ENSG00000006638")
	.filter(col("evidence.datasource") == "HeCaToS")
	.select("evidence")
	.show(100,truncate=False)) --> None
```

**Comment by ireneisdoomed** [comment]
Another point, in `Lynch et al. (2017)` "Developmental Toxicity" is described as an additional case in terms of dosage besides acute and chronic. 

Although developmental toxicity assays can occur over a range of doses, this is a particular scenario of this data source, so we won't do any distinction and reflect these cases in the `dosing` field.

Therefore, `effects.dosing` will collect 3 different possibilities: _"chronic", "acute"_, and _"Developmental toxicity"_.
