### ISSUE TITLE
Review evidence source parsers to check the need for potential changes in order to include unmapped evidence

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1538]

**Comment by DSuveges** [comment]
We asked our providers to include all disease/target evidence regardless if the disease term could not be mapped to EFO ontology. This practice should be expanded to our in-house maintained data sources as well. The scope of this ticket is to review all the  parsers and schedule the updates if required.

**Comment by DSuveges** [comment]
**Parsers:**
- [ ] CRISPR.py
- [ ] EPMC.py
- [ ] GeneticsPortal.py
- [ ] IntOGen.py
- [ ] PROGENY.py
- [ ] SLAPEnrich.py
- [ ] SystemsBiology_old.py
- [ ] ClinGen.py
- [ ] Gene2Phenotype.py
- [ ] GenomicsEnglandPanelApp.py
- [ ] MouseModels.py
- [ ] PheWAS.py
- [ ] SystemsBiology.py
- [ ] UKBiobank.py

**Comment by ireneisdoomed** [comment]
Both Gene2Phenotype and Clingen parsers now have a function to write to a file those disease labels that could not be mapped during the process.
Given that all evidence will be processed in the ETL and that these cases will be tagged as invalid evidence due to unresolved disease, it looks like we can drop this extra logic and do the analysis later on as part of the work covered in [#1553](https://github.com/opentargets/platform/issues/1553).

Any concerns?

**Comment by DSuveges** [comment]
### Status:

- [x] **PanelApp**: 
  - [x] Number of evidence: 18019, evidence without disease mapping: 742
  - [x] Upload to bucket.


- [x] **ClinGen**:
  - [x] Number of evidence: 1328, evidence without disease mapping: 17. 
  - [x] Upload to bucket.


- [x] **IntOGen.py**:
  - [x] Number of evidence: 3333, evidence without disease mapping: 158. 
  - [x] Upload to bucket.


- [x] **PROGENY.py**:
  - [x] Number of evidence: 406, evidence without disease mapping: 158. 
  - [x] Upload to bucket.


- [x] **SLAPEnrich.py**:
  - [x] Number of evidence: 74632, evidence without disease mapping: 0. 
  - [x] Upload to bucket.


- [x] **Gene2Phenotype.py**:
  - [x] Number of evidence: 3804, evidence without disease mapping: 1190. 
  - [x] Upload to bucket.

- [x] **PheWAS.py**:
  - [x] Number of evidence: 189971, evidence without disease mapping: 0. 
  - [x] Upload to bucket.


- [x] **Crisr.py**:
  - [x] Number of evidence: 1845, evidence without disease mapping: 0. 
  - [x] Upload to bucket.



- [x] **SystemsBiology.py**: not updated as no mapping happens. However it has many things to update in the future.

**Comment by DSuveges** [comment]
Further fixes were needed:

**SLAPEnrich**:
- [ ] Instead of a right join, a left join was needed. This bug introduced 49 invalid evidence. It is due to the fact that the `cancer2EFO_mappings.tsv` has more cancer cell lines than the `slapenrich_opentargets-21-12-2017.tsv` input file. This issue is now fixed, in the 21.06 release won't introduce bad data.
