### ISSUE TITLE
Add OpenGraph <meta> tags

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1543]
In the [classic Platform webapp](https://github.com/opentargets/webapp/search?q=canonical_url), we included Open Graph <meta> tags to support social sharing of the main Platform URL. These tags are optimised to work with multiple social media platforms and allow us to control the content for `platform.opentargets.org` URL sharing. For more information on these tags, please see the [Ahrefs blog post on Open Graph meta tags](https://ahrefs.com/blog/open-graph-meta-tags/).

Can we please implement similar tags with the new next-generation Platform?

```
<meta property="og:title" content="Open Targets Platform" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://platform.opentargets.org/" />
<meta property="og:description" content="The Open Targets Platform integrates publicly available datasets to support systematic identification and prioritisation of drug targets." />
<meta property="og:image" content="https://platform.opentargets.org/assets/img/xxxxxxx.png" />
```

Please note that these tags should be visible with the <head> section of every page.

@HelenaCornu can you please review the `og:description` tag and make any suggested updates? Also, is there a preferred image that you would like to use? Or just the helix logo and wordmark?

**Comment by HelenaCornu** [comment]
I'm happy with the `og:description` tag. For the image, I would suggest a screenshot of the Platform homepage, since it has the helix wordmark and logo, but will be more eye-catching and recognisable. The one attached here is the recommended dimensions in the Ahrefs blog post. 

<img width="1200" alt="Open Targets Platfrom 1200x630" src="https://user-images.githubusercontent.com/73692302/118468146-62c4a380-b6fc-11eb-9bf3-1006849bca33.png">

**Comment by andrewhercules** [comment]
Thank you @HelenaCornu - I will ask the front-end team to add to the codebase in order to display the homepage image

**Comment by ktsirigos** [comment]
closing issue as work done.
