### ISSUE TITLE
downloads page: 18.06 names on the files for both Aug and Jun releases.

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#155]
https://www.targetvalidation.org/downloads/data

![screen shot 2018-10-09 at 10 03 04](https://user-images.githubusercontent.com/6472381/46658445-a4872800-cbaa-11e8-8aa6-8551edb821e5.png)

I'm assuming the files are different judging from their sizes (202MB versus 189MB for associations;  2.44Gb versus 2.3Gb for evidence).

Btw, why do we have MB and Gb? When we are talking about bytes, shouldn't the "b" be always capitalised?

https://en.wikipedia.org/wiki/Byte

**Comment by afaulconbridge** [comment]
That URL is for all downloads, not just a specific version. So it lists 18.08 and 18.06. I think there was an issue with the filenames that @LucaFumis fixed too.

Capital B vs lowercase b is if its counted in multiples of 1000 or 1024 - so while having them different is less beautify, it is technically not wrong.

Since it is unclear if further work is needed, I'm closing this ticket. Feel free to re-open any specific new tickets if appropriate.

**Comment by deniseOme** [comment]
Thanks @afaulconbridge. Good to know it's not technically wrong having capital or not (B)...

At some point we used to have the size of both files described as B. For consistency, I'd vote on having all files (from Dec 2016 onwards) as MB and GB, but I understand the team has more precious things to focus on.

<img width="698" alt="screen shot 2018-10-21 at 10 48 16" src="https://user-images.githubusercontent.com/6472381/47265362-da1f0000-d51e-11e8-98ab-6ad8ed970b09.png">

As per the filenames, yep, @LucaFumis has fixed this. Thanks a lot Luca!

(test @deniseOme )
