### ISSUE TITLE
Searching for Disease Code returns no results and displays White Screen

### ISSUE THREAD

**Issue by bhandaris4** [opentargets/platform#1561]
Searching for certain desease-codes will not produce any result. A white screen appears and the page is unresponsive. 

Disease Codes having the issue are : 

UBERON_0000982

ZFA_0000541

CL_0002001

Steps to reproduce : 

In https://platform.opentargets.org/ , Search for the given disease codes from Home-page or the search bar( while being in any other pages). 
Try to navigate back/forth. 

The issue, however, does not exist with all the disease-codes. Compare the search result to HP_0000857, HP_0001892 or DOID_7551. 

![DRUG_Search_No Results Returned](https://user-images.githubusercontent.com/84523825/119023087-5f851e00-b96f-11eb-991b-68919990c884.jpg)

**Comment by d0choa** [comment]
Thanks for reporting @bhandaris4.

The EFO ontology used by the Platform has a few modifications over the EFO, as described in our [documentation](https://platform-docs.opentargets.org/disease-or-phenotype). The EFO OTAR profile can be found for every [EFO release](https://github.com/EBISPOT/efo/releases)).

The terms you are trying to find are not currently within scope at the moment as we aim to capture diseases, phenotypes or processes but not body parts or disease locations. That's why they are not part of the ontology profile the Platform uses.

This absence of information does not justify why we return a white page and we will aim to handle that more nicely.

**Comment by andrewhercules** [comment]
@mirandaio can we please update the logic for the 404 not found page so that it appears if a user either searches for an unknown ID or manually enters an ID into the URL?

**Comment by bhandaris4** [comment]
The codes I have used for testing are from the OT platform download section. Is there any way to figure out in-scope (or out-of-scope ) items so that I can focus on the correct test data.

**Comment by andrewhercules** [comment]
@bhandaris4, I believe that those codes are available within the `diseases` dataset as they provide annotation for a given disease or phenotype (e.g. location).

For testing purposes, I would recommend taking a random sample of entries from the `disease.id` field. This is the primary key used for the disease object and will identify disease/phenotypes found in the Platform.

**Comment by ireneisdoomed** [comment]
Funny enough I ran into the same issue yesterday when I wanted to look for digestive system diseases in the platform. You get the same blank page when you search for `digestive system` because this is also a label contained in the disease dataset.

```
In [14]: dis.filter(col("name") == "digestive system").show(5, vertical=True)
-RECORD 0-----------------------------------
 id                  | UBERON_0001007
 code                | http://purl.oboli...
 dbXRefs             | [BILA:0000082, MI...
 description         | Anatomical system...
 name                | digestive system
 directLocationIds   | null
 obsoleteTerms       | [EFO_0000793]
 parents             | [UBERON_0000467]
 sko                 | null
 synonyms            | [,,, [gut, alimen...
 ancestors           | [UBERON_0000061, ...
 descendants         | []
 children            | []
 therapeuticAreas    | []
 indirectLocationIds | null
 ontology            | [false, true, [ht...
```

On the other hand, if you query `digestive system disease` the behaviour is the expected one.

**Comment by d0choa** [comment]
After a preliminary conversation with @cmalangone and @mkarmona, we identified the issue is related with the fact that some terms are included in the EFO slim, despite them not falling in any of the therapeutic areas. These terms are outside the scope of associations, as no therapeutic interventions is expected against these terms.

The first thought is to exclude the terms with no therapeutic area from the disease dataset. That would make sense as they are not `diseases` as such. The only caveat we have to consider is that some of these terms are currently used to resolve disease locations.

```python
>>> disease.select("id", "name", F.explode("indirectLocationIds").alias("locations")).filter(F.col("locations") == "UBERON_0000982").show()
+---------------+--------------------+--------------+
|             id|                name|     locations|
+---------------+--------------------+--------------+
|  MONDO_0002614|bone inflammation...|UBERON_0000982|
|  MONDO_0023603|hereditary connec...|UBERON_0000982|
|    EFO_0000618|nervous system di...|UBERON_0000982|
|    EFO_0001958|     joint component|UBERON_0000982|
|    EFO_0002461|skeletal system d...|UBERON_0000982|
|  MONDO_0004670| lupus erythematosus|UBERON_0000982|
|    EFO_0000508|    genetic disorder|UBERON_0000982|
|  MONDO_0015939|systemic autoimmu...|UBERON_0000982|
| UBERON_0000061|anatomical structure|UBERON_0000982|
|  MONDO_0019724|secondary glomeru...|UBERON_0000982|
|    EFO_0000540|immune system dis...|UBERON_0000982|
|    EFO_0003086|      kidney disease|UBERON_0000982|
|  MONDO_0000589|autoimmune diseas...|UBERON_0000982|
|   OTAR_0000006|musculoskeletal o...|UBERON_0000982|
|   OTAR_0000018|genetic, familial...|UBERON_0000982|
|    EFO_0005140|  autoimmune disease|UBERON_0000982|
|    EFO_0004280|   movement disorder|UBERON_0000982|
|    EFO_0005856|           arthritis|UBERON_0000982|
| Orphanet_71859|Rare genetic neur...|UBERON_0000982|
|Orphanet_307061|Rare genetic trem...|UBERON_0000982|
+---------------+--------------------+--------------+
only showing top 20 rows
```

**Comment by d0choa** [comment]
All anatomical structures have been removed from the diseases or phenotype dataset. This change fixes the bugs reported here.

This change is effective in the development version of the Platform (aka `xyz`) and will be effective in the upcoming platform release.
