### ISSUE TITLE
Filter : Child-list items sum exceed the Parent List-item total

### ISSUE THREAD

**Issue by bhandaris4** [opentargets/platform#1564]
The total value of the parent item is less than the sum of all children items added together.

The numbers of the total results seem to fluctuate as we make changes to selection on the child items. When selecting multiple sub-list items for data filter purpose, the sum of individual total do not match to the total search results. 

Steps to Reproduce : 

In OpenTarget Platform, search for any Disease, Drug or Target. (I searched for 
schizophrenia or EFO_0000692)
In Associates Tab, go to Filter by Target Specific Filters > Target Classes
Select Epigenetic Regulator. Verify the total target associated is 61. 
Expand the Epigenetic Regulator and add the Target Associations of each sub-item. 
Verify the Target Association total is more than Epigenetic Regulator total. 

![Error on EpigeneticRegulator Total Count_TargetClasses](https://user-images.githubusercontent.com/84523825/119027268-2602e180-b974-11eb-953c-53321a5b1af4.jpg)

**Comment by DSuveges** [comment]
Thanks for using our service! It's always great to hear from our users.

Said discrepancy is due to the nature of target annotation: target classes are assigned based on [Gene Ontology](http://geneontology.org/) terms. Out of all targets associated with schizophrenia 61 has epigenetic regulator annotation. However, as the following list shows, one gene might have multiple annotations making the sum of the subcategories higher than the total.

```
EP300: Writer,Reader
KMT2D: Writer,Reader
CREBBP: Writer,Reader
DNMT3B: Writer,Reader
DNMT3A: Writer,Reader
KAT5: Writer,Reader
SETDB1: Writer,Reader
PRDM9: Writer,Reader
KMT2A: Writer,Reader
KAT8: Writer,Reader
KMT2C: Writer,Reader
KAT2B: Writer,Reader
JMJD1C: Reader,Eraser
KDM4A: Reader,Eraser
PHF8: Reader,Eraser
KDM4C: Reader,Eraser
```

Please don't hesitate contacting us in the future if you have any comments or concerns about the tool or the underlying data. Also, I would highly encourage you to join our community space where you can also ask questions related to our services and found useful use cases on accessing and analysing our data in various ways: [https://community.opentargets.org/](https://community.opentargets.org/)

**Comment by bhandaris4** [comment]
Thank You for the details. We, in our team, have discussed about the possibility of multiple annotations that might lead to the higher individual sum as compared to the total header sum. Where do I find the information about multiple annotations applied to the gene? That would be helpful in future tests as well.

**Comment by bhandaris4** [comment]
Thank You for the details. We, in our team, have discussed about the possibility of multiple annotations that might lead to the higher individual sum as compared to the total header sum. Where do I find the information about multiple annotations applied to the gene? That would be helpful in future tests as well.
