### ISSUE TITLE
LUMASIRAN misses HAO1 target information from its MOA

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1575]
[the profile of HAO1](https://platform.opentargets.org/target/ENSG00000101323/associations) does not list any drugs targeting it, but in the [evidence page](https://platform.opentargets.org/evidence/ENSG00000101323/Orphanet_93598), is linked to a rare disease that has a drug targeting HAO1.
![hao1_evidence](https://user-images.githubusercontent.com/5394232/119975057-51f21880-bfad-11eb-9043-25d5c963b23e.png)

<img width="1489" alt="hao1_assocs" src="https://user-images.githubusercontent.com/5394232/119975072-56b6cc80-bfad-11eb-8cd7-7ff70edd61c6.png">

From ETL the known-drugs dataset is joint [at this point](https://github.com/opentargets/platform-etl-backend/blob/d3fb49da23a09dc5bb09ebc2189f97b58fa3e7c5/src/main/scala/io/opentargets/etl/backend/KnownDrugs.scala#L98) in _inner mode_ so if the drug dataset for that drug does not contain any target the row will be dropped. Exploring further at the ES doesn't give further hints:

```json
GET mechanism_of_action/_search
{
  "query": {
"match": {
      "chemblIds.keyword": "CHEMBL4297779"
    }
  }
}
```

```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 7.5951056,
    "hits" : [
      {
        "_index" : "mechanism_of_action",
        "_type" : "_doc",
        "_id" : "ho3dN3kBkyafTmZUEEr1",
        "_score" : 7.5951056,
        "_source" : {
          "actionType" : "RNAI INHIBITOR",
          "mechanismOfAction" : "Hydroxyacid oxidase 1 mRNA RNAi inhibitor",
          "chemblIds" : [
            "CHEMBL4297779"
          ],
          "targetName" : "Hydroxyacid oxidase 1 mRNA",
          "targetType" : "nucleic-acid",
          "targets" : [ ],
          "references" : [
            {
              "source" : "FDA",
              "ids" : [
                "label/2020/214103lbl.pdf"
              ],
              "urls" : [
                "http://www.accessdata.fda.gov/drugsatfda_docs/label/2020/214103lbl.pdf"
              ]
            }
          ]
        }
      }
    ]
  }
}
```
The API query did not break either when queried so it pointed me to a data problem related either to our ETL drug step or Chembl desynchronised data.

```graphql
query CHEMBL4297779 {
  drug(chemblId:"CHEMBL4297779") {
    name
    mechanismsOfAction {
      uniqueTargetTypes 
      uniqueActionTypes
      rows {
        mechanismOfAction
        targetName
        targets {
          id
          approvedSymbol
        }
      }
    }
  }
}
```
```json
{
  "data": {
    "drug": {
      "name": "LUMASIRAN",
      "mechanismsOfAction": {
        "uniqueTargetTypes": [
          "nucleic-acid"
        ],
        "uniqueActionTypes": [
          "RNAI INHIBITOR"
        ],
        "rows": [
          {
            "mechanismOfAction": "Hydroxyacid oxidase 1 mRNA RNAi inhibitor",
            "targetName": "Hydroxyacid oxidase 1 mRNA",
            "targets": []
          }
        ]
      }
    }
  }
}
```

**Comment by d0choa** [comment]
ok this is what’s happening… We all know we get evidence (ChEMBL OTAR pipeline) and MoAs by 2 separate methods. This is an eternal cause of problems because it’s a source of inconsistencies.

What’s going on here is that the mRNA targets of drugs like LUMASIRAN or NUSINERSEN are not resolved to an id in the ChEMBL mechanism of action data. When @JarrodBaker builds the dataset there is no way to know what the actual ENSG id of the target is because they don’t store that internally (apparently). However, in the evidence pipeline, they are annotating the ENSG for these targets and they are providing them as evidence. It’s good in the sense we are getting extra coverage for associations and valuable information but it lacks consistency.

```
>>> evidence.filter(F.col("drugId") == "CHEMBL4297779").select("targetSymbol", "diseaseLabel", "drugId", "urls.url").show(vertical = True)
-RECORD 0----------------------------                                           
 targetSymbol | HAO1                 
 diseaseLabel | Primary hyperoxal... 
 drugId       | CHEMBL4297779        
 url          | [https://clinical... 
-RECORD 1----------------------------
 targetSymbol | HAO1                 
 diseaseLabel | Primary hyperoxal... 
 drugId       | CHEMBL4297779        
 url          | [https://clinical... 
-RECORD 2----------------------------
 targetSymbol | HAO1                 
 diseaseLabel | Primary hyperoxal... 
 drugId       | CHEMBL4297779        
 url          | [https://clinical... 
-RECORD 3----------------------------
 targetSymbol | HAO1                 
 diseaseLabel | Primary hyperoxal... 
 drugId       | CHEMBL4297779        
 url          | [https://clinical... 
-RECORD 4----------------------------
 targetSymbol | HAO1                 
 diseaseLabel | Primary hyperoxal... 
 drugId       | CHEMBL4297779        
 url          | [https://clinical... 
 ```

Now, how is this affecting us:

- Associations - great coverage - all good there
- Evidence page - there is a caveat in our FE. In order not to duplicate information and to show there are more targets than the actual one, @mirandaio  pulls the MoA from the drug itself and not from the evidence. Because they are not consistent is causing a problem with the missing label.
- Known drugs - Known drugs pulls most of the info from Evidence but it also completes it with MoAs. Again, because of the inconsistency this is probably causing problems in some of the joins.

Actions:
- @ireneisdoomed - I would try to get from Paula et al. whether they keep the list of oligonucleotide targets somewhere. If they are not planning to make that available in ChEMBL we should do it on our side.
- @mkarmona @jarrodbaker. I believe known drugs should work. There might be an inner join that is dropping rows based on the assumption that all MoAs have targets (which is not true)
- @andrewhercules @mirandaio - We need a fallback condition that uses the evidence target if no target was found in the MoA - HAO1 for example
Thanks @mak for reporting!

**Comment by ktsirigos** [comment]
@mkarmona is this ticket resolved?

**Comment by d0choa** [comment]
@JarrodBaker work on #1787 fixed this problem:

<img width="386" alt="Screenshot 2021-12-09 at 11 30 36" src="https://user-images.githubusercontent.com/5097586/145388836-70546bc2-c6f1-4eb9-9af0-46ebf606960c.png">
