### ISSUE TITLE
Create 'latest' directory at our FTP

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1579]

**Comment by ktsirigos** [comment]
to be expanded

**Comment by ktsirigos** [comment]
add metadata file in the directory for cross-check purposes

**Comment by ktsirigos** [comment]
After talking to EBI search, it became (even more) clear that we need a 'latest' directory in our FTP site, which can be used to programmatically access the data, without the need to specify the release version.

What we need is to have this link:

[http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest](url)

that will contain:
* all the files from the most recent release
* a metadata file that lists the files that should be there, for cross-checking purposes.

Thank you!

**Comment by JarrodBaker** [comment]
Are we sure this is a good idea? I see two problems:

1. As far as I can recall, every release since I've been here the data model has changed in some way. If we expose a 'latest' directory, that is what people are going to point to (out of laziness and an assumption that being up to date is always better). It won't be uncommon for them to realise that following a new Open Targets release their client application no longer works as expected.
2. Anyone using the data for tasks that need to be reproducible (academic publications say) should be using versioned data.

**Comment by d0choa** [comment]
There are pros and cons, it's not a straight-forward call.

In my opinion, this is as an additional feature that won't clash with current functionalities. Users will still be able to access a fixed release (and they probably should for most of the applications). Our recurrent changes in schema are of course a liability for people relying on `latest`, but for others accessing only a subset of inmutable schema might not be an issue. In fact, it's a way to ensure users or downstream applications are up-to-date, instead of pointing to an old version and never updating it.

After a quick look at the EBI ftp is a relatively common practice:
- /ebi/ftp/pub/databases/uniprot/current_release
- /ebi/ftp/pub/databases/intact/current
- /ebi/ftp/pub/databases/gwas/releases/latest

**Comment by ktsirigos** [comment]
Ok, @JarrodBaker this is a 'go' as discussed also with Miguel this morning.

We can proceed with the creation of the 'latest' directory :)

**Comment by JarrodBaker** [comment]
For this release we're going to do this manually as the current technology used in POS does not support symbolic linking. We'll automate this as part of 21.09.

**Comment by ktsirigos** [comment]
Thanks @JarrodBaker. 
Will you be using:

http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest ?

**Comment by JarrodBaker** [comment]
@cmalangone has kindly volunteered to do the honours, so she will be able to confirm the final location when it's done.

**Comment by ktsirigos** [comment]
closing this as work completed
