### ISSUE TITLE
NAT8 evidence page has Fabry's disease and associated phenotypes as associations based on genetic evidence

### ISSUE THREAD

**Issue by mohdkarim** [opentargets/platform#1598]
_NAT8_ (located in chr 2) is linked to Fabry’s disease (FD) (X-linked disorder) and FD-linked phenotypes (e.g. cardiomyopathy) via genetic evidence from panelapp and gene2phenotype. 

https://platform.opentargets.org/target/ENSG00000144035/associations

This may have been caused due to ‘_GLA’_ which is an alias/synonym for _NAT8_ but also represents a completely different gene **galactosidase alpha**, which is on the X-chr and (correctly) linked to Fabry’s and displayed in PanelApp.

https://panelapp.genomicsengland.co.uk/panels/75/gene/GLA/

**Comment by d0choa** [comment]
We just want to remove `symbolSynonyms` from the `resolveTargets` function in the ETL [code line here](https://github.com/opentargets/platform-etl-backend/blob/cf939c0951ae32ef2a309cfacae721538eaea6db/src/main/scala/io/opentargets/etl/backend/Evidence.scala#L120).

When mapping from evidence we want to be more strict and only allow approved gene symbols to be mapped to Ensembl Gene Ids. Otherwise, we will generate false positives like the following one. Also, our providers are all expected to provide approved symbols (ignoring the epmc case which is a different story). 

```
>>> target.filter(F.array_contains("symbolSynonyms", "GLA") | (F.col("approvedSymbol") == "GLA")).select("id", "approvedSymbol", "symbolSynonyms").show(vertical = True, truncate = False)
-RECORD 0--------------------------------------------
 id             | ENSG00000102393                    
 approvedSymbol | GLA                                
 symbolSynonyms | [GALA]                             
-RECORD 1--------------------------------------------
 id             | ENSG00000144035                    
 approvedSymbol | NAT8                               
 symbolSynonyms | [Hcml1, TSC501, GLA, ATase2, CML1] 
 ```
