### ISSUE TITLE
the endpoint associationDatasources needs to incorporate datasource configuration

### ISSUE THREAD

**Issue by mkarmona** [opentargets/platform#1643]
- The associationDatasources needs to include the data source configurations as weight and propagate.
- The endpoint associatedTargets and associatedDiseases need to return the full list of configurations, not just the modified ones

**Comment by ktsirigos** [comment]
@mkarmona @mirandaio is this done? Can I close it?

**Comment by andrewhercules** [comment]
Ticket closed.

The work on this ticket would be relevant for an associations-on-the-fly heat map that would allow users to set individual data source weights and recalculate the overall score. Such a heat map is not currently on our short- or medium-term roadmaps due to other strategic priorities and current capacity.
