### ISSUE TITLE
Update Chemical Probes summary widget and detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1677]
See comment below for full design specification — https://github.com/opentargets/platform/issues/1677#issuecomment-896677359

**Comment by JarrodBaker** [comment]
Steps required to unblock from BE:

- [ ] Update PIS to transfer chemical probes raw data file
- [ ] Incorporate new dataset into ETL
- [ ] Expose data via API

**Comment by andrewhercules** [comment]
With the new `target` ETL pipeline and API response, we have new Chemical Probe insights that we can display on the target profile page.

```
query targetInfo {
  target(ensemblId: "ENSG00000204256") {
    id
    approvedSymbol
    chemicalProbes{
      id
      control
      drugId
      inchiKey
      mechanismOfAction
      origin
      probeMinerScore
      probesDrugScore
      scoreInCells
      scoreInOrganisms
      targetFromSourceId
      urls{
        niceName
        url
      }
    }
  }
}
```
Sample query: [BRD2 (ENSG00000204256)](https://api-beta-dot-open-targets-eu-dev.ew.r.appspot.com/api/v4/graphql/browser?query=query%20targetInfo%20%7B%0A%20%20target%28ensemblId%3A%20%22ENSG00000204256%22%29%20%7B%0A%20%20%20%20id%0A%20%20%20%20approvedSymbol%0A%20%20%20%20chemicalProbes%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20control%0A%20%20%20%20%20%20drugId%0A%20%20%20%20%20%20inchiKey%0A%20%20%20%20%20%20mechanismOfAction%0A%20%20%20%20%20%20origin%0A%20%20%20%20%20%20probeMinerScore%0A%20%20%20%20%20%20probesDrugScore%0A%20%20%20%20%20%20scoreInCells%0A%20%20%20%20%20%20scoreInOrganisms%0A%20%20%20%20%20%20targetFromSourceId%0A%20%20%20%20%20%20urls%20%7B%0A%20%20%20%20%20%20%20%20niceName%0A%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)

Can we please update the Chemical Probes summary widget and detail view to show the new data?

### Summary widget

In the current production Platform, we display the sources of the chemical probes data, separated by a bullet:

![Screenshot 2021-08-11 at 10 13 38](https://user-images.githubusercontent.com/7490258/129003144-c38dbc4e-84c5-4e5a-89ca-63f25e05c1c2.png)

Instead, can we please show the total number of chemical probes returned in the `chemicalProbes` array?

![Screenshot 2021-08-11 at 10 15 32](https://user-images.githubusercontent.com/7490258/129003297-f86f62b5-39be-4283-986b-65f5eb17de6f.png)

### Detail view

The new Chemical Probes detail view will only have one data table, showing data for all different sources.

- [ ] Please remove the section and logic that shows the "Potential chemical probes can be explored with ProbeMiner." string

- [ ] Please create a new data table:

| Probe ID | Control | Reported target | Mechanism of action | Probe origin  | Probe Miner | Drug | Cell | Organism | Source 
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| `id` | `control` | `targetFromSourceId` | `mechanismOfAction` | `origin` | `probeMinerScore` | `probesDrugScore` | `scoreInCells` | `scoreInOrganisms` | 2 sources |

Above the "Probe Miner", "Drug", "Cell", and "Organism" columns, please have a parent column heading that spans all four columns called "Reported score". The parent column heading style can be similar to the "Clinical trials information" heading we display in the Known Drugs table. 

In the "Probe ID" column, please link the `id` to the drug profile page if `drugId` is not `null`.

In the "Reported target" column, please link to UniProt using identifiers.org - `https://identifiers.org/uniprot:` + `targetFromSourceId`.

In the "Source" column, please use the publications drawer component and show the `niceName` of each of the elements in the `urls` list and link using the `url` value.

**Comment by d0choa** [comment]
Looks great. Only one minor comment. The score columns: `Probe Miner`, `Drug`, `Cell` and `Organism`  have a lot of `nulls`. Each row very rarely have more than one non-null and often they are all `nulls`. I feel they might do the table unnecessarily wide.

An alternative could be to have a single column with the header "Scores" and have chips or other element that say `Probeminer: 20` `Drug Score: 70`, etc. Sort of what we did for intogen.

We should also have on-hover interactions to explain what each score means. @ireneisdoomed can you come out with labels for each of the 4?

On a different note, the control column is very strange. It can have names `DDR-TRK-1N` but also integers `1`. It's secondary information and also very frequently `null`. We could make it a tooltip of Probe ID that says `Control: DDR-TRK-1N`.

**Comment by andrewhercules** [comment]
Good idea @d0choa! I have created a [design mockup](https://docs.google.com/presentation/d/103QGo1Od75-9Lmo4YO2k_p3cZLY6Y_ZXhwoLJpWzzZg) and updated the ticket

**Comment by ireneisdoomed** [comment]
The mock-ups look awesome @andrewhercules!  

Proposed labels for the chips:
Probe Miner (`probeMinerScore`): "The Probe Miner score is the sum of 6 parameters: target potency, target selectivity, cell potency, structure-activity relationships (SAR), inactive analogs and pan-assay interference (PAINS)."
Probes&Drugs ('probesDrugScore'): "The P&D probe-likeness score is the sum of 6 parameters: target potency, target selectivity, cell potency, potency-selectivity synergy, presence of a control compound and presence of an orthogonal probe."
Cells (`scoreInCells`): "The organism score ranks the chemical probe for its use in model cells."
Organisms (`scoreInOrganisms`): "The organism score ranks the chemical probe for its use in model organisms."


`probesDrugsScore`: The P&D probe-likeness score consists of the sum of 6 parameters_

**Comment by d0choa** [comment]
Looks great @LucaFumis. After discussion with @ireneisdoomed, we have a few minor suggestions:

- [ ] Update Source in the description to Probes & Drugs as specified by @andrewhercules  in [mock design](https://docs.google.com/presentation/d/103QGo1Od75-9Lmo4YO2k_p3cZLY6Y_ZXhwoLJpWzzZg).
- [ ] Remove `Reported target` column. After exploring the data, it does look highly redundant and it adds very little information.
- [ ] On the position of the removed column, please add another column titled `Quality`. Using the output of the `isHighQuality` [endpoint](https://api-beta-dot-open-targets-eu-dev.appspot.com/api/v4/graphql/browser?query=query%20vers%20{%20%20%20target(ensemblId:%20"ENSG00000100030")%20{%20%20%20%20%20id%20%20%20%20%20chemicalProbes{%20%20%20%20%20%20%20id%20%20%20%20%20%20%20isHighQuality%20%20%20%20%20}%20%20%20}%20}), add a star (like the one used in [clinvar evidence](https://deploy-preview-437--platform-app.netlify.app/evidence/ENSG00000001626/Orphanet_586)) colored in `primaryColor` if `true` or with the alternative style if `false`.
- [ ] We would like to reorder the rows so that all `isHighQuality == true` are on top and `isHighQuality == false` records appear at the bottom of the table. We might need a second layer of ordering if still not clear but let's see how it looks in a first pass.

@ireneisdoomed is looking at how to make the URLs more specific/useful from the data side and also removing the label ` (suitable probes)` from the Probe Miner reference `niceNames`. None of these changes will impact FE

**Comment by LucaFumis** [comment]
Front end work done.
