### ISSUE TITLE
Decide on future status of `targets`, `diseases`, and `drugs` endpoints

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1692]
As we have been encouraging users to utilise BigQuery and our dataset downloads for more comprehensive and systematic queries, we should decide the future status of the `targets`, `diseases`, and `drugs` endpoints.

Should these endpoints be officially deprecated?

**Comment by andrewhercules** [comment]
For context, we have already had a user try the `targets` endpoint to return Known Drugs data for a list of targets.

See https://community.opentargets.org/t/graphql-interface-failing-to-fetch-knowndrugs/306 for the original post and my recommendation that they use BigQuery or the `knownDrugsAggregated` dataset.

**Comment by d0choa** [comment]
I agree this requires some discussions. I wouldn't say deprecate is the way as it might be more performant to have 1 query of 10 targets than 10 individual GQL queries. There is clearly a tradeoff and a use case when this endpoints are reasonable and when they are not

**Comment by JarrodBaker** [comment]
I don't think that we want to deprecate them. I use them to quickly pull up several results, and from memory they are used in the FE. That said, there is a way to query multiple items in a single query using 'aliases': 
```
query targets {
  t1: target(ensemblId: "ENSG00000168143") {
    id
    tep {
      uri
      name
    }
  }
  t2: target(ensemblId: "ENSG00000002745") {
    id
    tep {
      uri
      name
    }
  }
}
```
The above returns just about the same thing as the `targets` endpoint. 

I saw the community discussion @andrewhercules and I think you're response is the only possible one. People wanting to pull comprehensive data sets need to use another service. GraphQL is a courtesy to provide programmatic _querying_ rather than a data dump.   

There is a more general issue however, which is we need to stop changing the GraphQL interface at some point. Beyond that properly deprecate old fields rather than just deleting/renaming things.

**Comment by andrewhercules** [comment]
Ticket closed as endpoints will remain as they are useful for debugging and small queries. We will continue to recommend that more comprehensive and systematic use cases utilise either the dataset downloads or BigQuery.
