### ISSUE TITLE
Fix OTAR CRISPR evidence data

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1713]
Based on a review of the API deployed today, can we please fix the following?

OTAR2054
- [x] Data is not returned by the API — could it be due to the values in the `targetFromSourceId` field?

OTAR036
- [ ] One of the mapped diseases is "Pick disease" (EFO_0003096) — is that correct?

OTAR033
- [x] Fix spelling in `studyOverview` field ("differentiated")

**Comment by DSuveges** [comment]
All target identifiers in the `OTAR2054` were following the `ENGS\d+_.+` pattern. That was the only datafile with such gene identifiers and were all filtered out by the ETL, as such strings could not be mapped to ensembl gene identifiers. Now it has been fixed in [this commit](https://github.com/opentargets/evidence_datasource_parsers/pull/91/commits/5a8f0c060289f56d118a13ce5d3ac7d4f4d5f627).

**Comment by DSuveges** [comment]
* Spelling is fixed.
* Lewis has added Pick's disease to the list of studied diseases.

**Comment by DSuveges** [comment]
@andrewhercules, please reopen this ticket if you found any other issues.
