### ISSUE TITLE
Change how BigQuery instance is created in `platform-output-support`

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#1754]
Currently, our BigQuery `open-targets-prod` instance has versioned tables for each release (e.g. `platform_21_04`).

However, for the Google Marketplace public dataset listing programme, our tables should be consistent from release to release and archives stored in GCP buckets. 

Can we please update `platform-output-support` so that our `open-targets-prod` instance no longer has the data version?

**Comment by mkarmona** [comment]
@cmalangone translating this into a set of actions so you can activate this

1. after each data release we create in BQ with the Open Targets versioned dataset as we are currently doing but in another project because the Google Marketplace policy needs
2. clean the open-targets-prod BQ database and always recreate the same datasets without versioning in the name so it will always be one DB with the same datasets and same tables in it

Questions you might have?

- what if the schema changes? They don't mind really, they just want the dataset naming the same as they can publish it through their channels
- what if we create a new table inside? It is ok as long as the project and the dataset remains the same

**Comment by cmalangone** [comment]
@andrewhercules provides us the list of tables that must be listed
https://github.com/opentargets/platform-app/blob/main/src/pages/DownloadsPage/dataset-mappings.json

**Comment by andrewhercules** [comment]
BigQuery updated, ticket closed

**Comment by cmalangone** [comment]
@andrewhercules I am finishing to add the code to POS :)

**Comment by andrewhercules** [comment]
No worries - I was too quick with closing! 😅 

If possible, can you please also delete the `platform_21_06`, `platform_21_09`, and `targval_quicksearches` datasets? 

I'm not sure how the Google public dataset pipeline works, but I figure it would be best if `open-targets-prod` only contains the one `platform` dataset.

That being said, I also understand if we use BigQuery to keep a copy of the two most recent releases — just please let me know so I can liaise with Google.

**Comment by cmalangone** [comment]
I deleted the old bigquery datasets.
We will talk about it for shaping the POS output in a better way next release.

**Comment by andrewhercules** [comment]
A user has contacted the helpdesk about the `knownDrugsAggregated` data from our `21.11` release. The data is not available in Google BigQuery.

@cmalangone can you please check if POS is also adding that dataset to our `open-targets-prod.platform` BigQuery instance? If not, is this something we can manually do for this release?

**Comment by cmalangone** [comment]
I've created the dataset manually.
The issue was that the file dataset-mappings.json has the dataset filtered as include_in_bq == false
@andrewhercules can you please create a ticket?

**Comment by andrewhercules** [comment]
Thank you @cmalangone! 😄 

I have updated #1790 and will adjust the mapping file for the `22.02` release.

**Comment by andrewhercules** [comment]
Ticket closed as datasets generated for BigQuery.

Additional work will be captured in #1790.
