### ISSUE TITLE
Clean up SafetyLiabilities on Target

### ISSUE THREAD

**Issue by JarrodBaker** [opentargets/platform#1756]
The Safety Liabilities data that is used in the `Target` step of the ETL is provided by three data files. 

- `ae.json`
- `sr.json`
- `ToxCast`

The first two files from deprecating the manually curated [spreadsheet](https://docs.google.com/spreadsheets/d/1EvpcnUkDASUNoBU5PzQPGD5YtZxh7cgotr2MqClJ7t0/edit#gid=568107671) which was used in the now defunct data pipeline. `ae.json` and `sr.json` were generated using a [script](https://github.com/opentargets/platform-etl-backend/blob/master/scripts/deprecate_target_safety_spreadsheet.sc) and capture a snapshot of the spreadsheet in flat file format. These files are not yet versioned, but are used in the 21_06 release. 

Tasks

- [x] Create a permanent home for these 'seed' files (probably same place as ToxCast) and add versioning information. The files would look something like `ae-2021-09-20.json`

- [ ] Update PIS to select the most recent of these for each release
- [x] Update `sr.json` to include event information and ID introduced to ETL though opentargets/platform#1745 
  - This will change the schema of `sr.json` to include those columns
- [x] Remove 'HeCaTos' entries from `sr.json`
- [ ] Update ETL to remove 'HeCaTos' filtering and manual adding of event entries.
  - Hint: see commit `dc9864b29c881a9ea76f7f128c3cf893615b703a`

**Comment by ireneisdoomed** [comment]
The Safety Liabilities datasets have been relocated and restructured so that their maintenance is the responsibility of the data team.

**PIS updates**
3 files need to be picked, all from` gs://otar001-core/TargetSafety/data_files` :
- Adverse events: latest file in `gs://otar001-core/TargetSafety/data_files/adverse_events/`
- Safety risk information: latest file in `gs://otar001-core/TargetSafety/data_files/safety_risk/`
- ToxCast annotation: latest file in  `gs://otar001-core/TargetSafety/data_files/toxcast/`

**ETL&API updates**
- All HeCaToS records have been dropped - this logic can be removed from the ETL.
- We want to include in the dump and expose in the API the link outs to the different sources instead of handling them in the FE (see [#1797](https://github.com/opentargets/platform/issues/1797) for more context).
For those references without a PMID, a URL must be present.
1. When `ref == Urban et al. (2012)`, `url == https://doi.org/10.1002/9781118098141.ch2`
2. When `ref == ToxCast`, `url == https://www.epa.gov/chemical-research/exploring-toxcast-data-downloadable-data`

**Question**
@JarrodBaker Since the versioning and the generation is on the data team's side, do you have an objection to moving [the ETL's bits of logic](https://github.com/opentargets/platform-etl-backend/blob/master/src/main/scala/io/opentargets/etl/backend/target/Safety.scala) of grouping the 3 files, and adapt the data to the schema model to our codebase? For instance, requests like the one related to the URL above could be maintained by us and is coherent to what we do with other annotation like mouse phenotypes.

**Comment by JarrodBaker** [comment]
Thanks for the update @ireneisdoomed. 

@cmalangone: please note the location of the new files for PIS. 

@ireneisdoomed: we're notionally freezing the ETL from tomorrow according to opentargets/platform#1834 so we can't do to much. 

If I'm understanding you correctly, your proposing that you'll provide the backend with a 'finished' file so to speak which is ready to go and just needs to be linked to a target? If you want to keep it in-house in the data-team I'm not going to stand in your way. :)

For this release I'd propose that I add in some logic to handle the URLs for Urban and Toxcast. 

How does that sound?

**Comment by ireneisdoomed** [comment]
It sounds perfectly fine @JarrodBaker! Thanks! 

> your proposing that you'll provide the backend with a 'finished' file so to speak which is ready to go and just needs to be linked to a target? 
That is it, yes. I'll scope it for 22.02.

**Comment by ireneisdoomed** [comment]
Work completed and included in `21.11`
