### ISSUE TITLE
Bubbles visualisations: EFO3 migration issues, datatype checkbox selection adjustment

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#183]
@andrewhercules commented on [Wed Jul 11 2018](https://github.com/opentargets/data_pipeline/issues/296)

@deniseOme commented on [Tue May 15 2018](https://github.com/opentargets/webapp/issues/276)

### Observed behaviour
User from Biogen reported that when searching for DPYSL2, navigating to its associated diseases and selecting Genetic associations only, there was no change in the Bubbles view or Tree view.

The Table view works as expected: when Genetic associations filter is applied, the number of rows change accordingly.

Note: the other Data types behaviour is as expected: reduces the number of diseases displayed as bubbles and lines in the tree

### Expected behaviour
There is one disease associated with DPYSL2 when associations are filtered based on the Genetic asssociations only. So we would expect one bubble only (or one line only in the Tree view).

### Environment
[How did you see the bug?]
* Version: [3.6.1]
* Browser: Google Chrome and Firefox

![screen shot 2018-05-15 at 13 54 28](https://user-images.githubusercontent.com/6472381/40057924-8893807a-5847-11e8-9419-30618e73421c.png)

---

@emepyc commented on [Tue May 15 2018](https://github.com/opentargets/webapp/issues/276#issuecomment-389170701)

It seems a data problem (or API, if the API has been changed recently).
The API response is expected to include a top level `therapeutic_areas` property:

https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000092964&size=10&direct=true&facets=false

but when selecting the `genetics_associations`, in the response to the resulting API call that property is missing:

https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000092964&size=10&direct=true&facets=false&datatype=genetic_association

@mkarmona?

---

@andrewhercules commented on [Tue May 15 2018](https://github.com/opentargets/webapp/issues/276#issuecomment-389176555)

Question for @emepyc, @peatroot, or @LucaFumis ... is the Bubbles view able to render a therapeutic area where there are no child elements to be rendered? In other words, an empty circle? 

In the case of DPYSL2, when filtering by `Data Type --> Genetic Associations`, the associated disease is `genetic disorder`, which is a parent therapeutic area. So in theory, the Bubbles View should show a white circle with a black border with a `genetic disorder` label, but no children - see below for a low-fidelity mockup. Is this possible? 

![genetics-assoc](https://user-images.githubusercontent.com/7490258/40061169-3ac7a6ba-5850-11e8-8c24-5224395d937d.png)

---

@emepyc commented on [Tue May 15 2018](https://github.com/opentargets/webapp/issues/276#issuecomment-389178560)

The widget expects always at least a disease and a therapeutic area.
Even in cases where the disease == therapeutic area, the expectation is that the API response includes "genetic disorder" as the disease and "genetic_disorder" as the therapeutic area, which _should_ result in a therapeutic area outer circle and a disease inner circle, both having the same name.

---

@LucaFumis commented on [Thu Jul 05 2018](https://github.com/opentargets/webapp/issues/276#issuecomment-402692026)

Marking as "won't fix" as it appears to be a data issue.

---

@andrewhercules commented on [Wed Jul 11 2018](https://github.com/opentargets/webapp/issues/276#issuecomment-404142522)

Issue moved to data_pipeline repository as API returns `disease` and `therapeutic_areas` attributes for other associations.

**Comment by ElaineMcA** [comment]
Raised via 19.04 candidate (EFO3) QC reviews on 12Apr2019:

Bubbles view IL3: 
All diseases are prefixed with disease in the therapeutic area column it makes them hard to read easily in the table view and I think makes the interpretation of the bubbles pretty hard as they’re all in one giant bubble for disease.

- also need to check the downloads facilities (for bubbles and tree).


![image](https://user-images.githubusercontent.com/40168275/56890717-2751d080-6a72-11e9-8c04-f3a6dbbfaf80.png)

**Comment by LucaFumis** [comment]
Looking at the comments by Miguel P about a year ago, I can see that the field `therapeutic_areas` is now returned by the API **for those examples**.
I've now come across other examples where the `therapeutic_areas` field is missing even without facets being applied; for instance GPR1-AS:
https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000279220&outputstructure=flat&size=1000&direct=true&facets=false
For other targets (e.g. BRAF) the response is correct.

**Comment by LucaFumis** [comment]
Following further investigation, I noticed other discrepancies.
Looking at target EPOP https://www.targetvalidation.org/target/ENSG00000273604/associations the `thrapeutic_areas` returned in the associations are different than those returned in the facets call:
4 in the associations call: https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000273604&outputstructure=flat&size=1000&direct=true&facets=false
9 in the facets call: https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000273604&outputstructure=flat&size=1000&direct=true&facets=true

So it appears there are a number of data issues...

**Comment by andrewhercules** [comment]
@LucaFumis, are these issues also seen in the EFO3 branch data?

Many of the targets that have issues with the bubbles view in production using EFO2 - ADAM33, EPOP, DPYSL2, etc. - have a bubbles view in the EFO3 branch using the ``disease`` root node. (e.g. [EPOP](https://efo3.targetvalidation.org/target/ENSG00000273604/associations?view=t:bubbles))

**Comment by LucaFumis** [comment]
@andrewhercules from what I've seen, there are issues in both EFO2 and EFO3 data, although the problems appear to be different. Short summary:

EFO2:
 - top level `therapeutic_areas` field missing for some targets
 - top level `therapeutic_areas` entries not matching `therapeutic_areas` in facets
 - occasionally `labels` and `codes` of `disease.efo_info.therapeutic_area` shows empty
 - first element of a `path` not found in top level `therapeutic_areas`

EFO3:
 - in `disease.efo_info.path` the first elements of each path don't account for all therapeutic areas in `disease.efo_info.therapeutic_area`, which causes bubbles to only show few therapeutic areas. E.g. In EPOP-psoriasis the disease is in 4 therapeutic areas, but all the paths lead to only one ('disease').
 
I delved further into Miguel P's code: while complex and not trivial to follow at first, it has it reasons behind it.
It uses the `path` field because the same output data is used to generate the tree view as well (and flatten for the bubbles). Perhaps the `disease.efo_info.therapeutic_area` codes were not reliable.

This unfortunately is not "hackable" in the front end - data would need to be addressed first...

**Comment by andrewhercules** [comment]
Thanks @LucaFumis for investigating this :-)

@ElaineMcA, should we schedule a meeting to discuss with the backend team and come up with a plan for 19.06 and/or 19.08?

**Comment by ElaineMcA** [comment]
Yes  - additional examples IDed by David H noted here also live in 19.04 production...

https://www.targetvalidation.org/target/ENSG00000145335/associations?view=t:bubbles

https://www.targetvalidation.org/target/ENSG00000064692/associations?view=t:bubbles

**Comment by deniseOme** [comment]
One user via support email has noticed bubbles/tree view for SIK1 renders no bubbles: https://www.targetvalidation.org/target/ENSG00000142178/associations?view=t:bubbles

It does seem to work on the EFO3 branch:
https://efo3.targetvalidation.org/target/ENSG00000142178/associations?view=t:bubbles

@LucaFumis @ElaineMcA @d0choa, would we be fixing these examples on production (19.04) or would we leave the fix for when EFO3 is out?

**Comment by d0choa** [comment]
Yes we'll cover this issue as well as some others on Friday. There are reasons to think this problem will persist in EFO3, despite displaying in our internal EFO3 branch. 

The issue with SIK1 and others (i.e. ILR36RN) is that some therapeutic areas have no score, but they contain descendants with scores. In fact, if you use the correct facets you can see the bubbles/trees displayed. In previous versions, having TAs without score was not possible because evidence was propagated in the graph up to the therapeutic area. Since the inclusion of data sources (i.e. ExpressionAtlas) that are not propagated in the graph, TA nodes with no score are possible. Unfortunately, the API and the UI were not expecting this scenario.

**Comment by andrewhercules** [comment]
Issue closed as it has been resolved in the 19.11 release with the migration to EFO3
