### ISSUE TITLE
Target tractability emergence

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#1843]
Is it possible with the current tractability pipeline (presumably [tractability_pipeline_v2](https://github.com/chembl/tractability_pipeline_v2)) to identify when the evidence for a particular type of tractability first emerged?  It would be useful, for example, to know if the discovery of a ligand was recent vs very old.

**Comment by ireneisdoomed** [comment]
Hi @eric-czech!

At the moment the tractability pipeline, unfortunately, does not allow for this. The assessments you can see in the Platform or in our target annotation dataset do not include the supporting data determining the analysis.

However, to support further research into the suitability, we make the data file generated by the tractability pipeline ([tractability_pipeline_v2](https://github.com/chembl/tractability_pipeline_v2), indeed) available for download — see [tractability_buckets_new_version.tsv](http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/input/target-inputs/tractability/).

For instance, you could extract which drugs support [AR](https://platform.opentargets.org/target/ENSG00000169083)'s clinical precedence from the tractability output and combine this dataset with the drug annotations dataset, which includes the year where the drug was first approved:

```python
import pandas as pd
import ast

drugs = (
    # Read OT's drug annotation
    # Download here: http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/21.09/output/etl/parquet/molecule/
    pd.read_parquet('/Users/irene/Documents/dev/pyspark/21.09.5/molecule')

    # Narrow down variables of interest
        .filter(items=['id', 'yearOfFirstApproval'])
)

AR_clinical_precedence = (
    # Read tractability pipeline's output
    # Download here: http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/latest/input/target-inputs/tractability/
    pd.read_csv('/Users/irene/Downloads/tractability_buckets_new_version.tsv', sep='\t')

    # Filter target: AR
    .query("ensembl_gene_id == 'ENSG00000169083'").reset_index()

    # Parse drugs supporting the clinical precedence
    # Drugs come in a form of a stringified array - literal_eval is used to convert it back to an array
    # Note: eval() could be used as well, but literal_eval is a safer method
    ['drug_chembl_ids_sm']
    .apply(lambda X: ast.literal_eval(X))
    .explode('drug_chembl_ids_sm')
    .to_frame()

    # Bring approval date from the drug annotation
    .merge(drugs, left_on='drug_chembl_ids_sm', right_on='id', how='left').drop('id', axis=1)

)
```

The result would look like this:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/45119610/141117226-c52d7ba8-6b05-42cc-be02-d1561f147fdb.png">

However, it is not always possible to easily enrich the data. For example, you can’t see when the specific PDBe ligand was made available.

---

Thank you very much for your comment. I hope this was useful! We will certainly have it into account for future developments of the pipeline.

I invite you to use our Community Space (https://community.opentargets.org) for this type of question so that other users can also benefit from the discussion!
