### ISSUE TITLE
Platform infrastructure 21.11 : Bug and improvements

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#1854]
During the generation of the release we found out the following issues.

- [ ] Clickhouse should write on the standard output and the log should collect the output
- [ ] GraphQL API should write on standard output and the log should collect the output
- [ ] Bring brotli process on nginx

**Expected behaviour**
- [ ] Clickhouse log available in cloud log
- [ ] GraphQL API log available in cloud log
- [x] Web app should work properly and https://platform.XXX.opentargets.xyz/config.js visible with the all parameters

**Comment by cmalangone** [comment]
@mbdebian it might be better to move the log from ES to GraphQL.

**Comment by mbdebian** [comment]
It depends on the logging capabilities offered by ES.
But I think at the API layer we have a very good opportunity for timing requests and do some logging of interest for us.

**Comment by JarrodBaker** [comment]
What do you mean that the API should write to standard output? It already does that in the container. If you run `docker logs -f <container_name>` you'll see the logs from the API.

**Comment by mbdebian** [comment]
Yes, we get the logs from the API.
On the data backend, we need to configure ES to use stdout as the output for its logs

**Comment by mbdebian** [comment]
Clickhouse as well

**Comment by cmalangone** [comment]
If we get the log from GraphQL, does make sense to retrieve/store the log from ES?

**Comment by mbdebian** [comment]
I guess ES would offer logs on things related to itself that we can't collect from anywhere else, e.g. memory usage

**Comment by mbdebian** [comment]
This came up when we were having a computational burst / deadlock due to certain type of traffic from China, but it has never happened again.
@ktsirigos , I think we should close this issue, @JarrodBaker extended the logging information produced by the API, and the infrastructure where everything is running implements the right service accounts for log collection.
There is no point on keeping this alive any more.
Please, let me know your view on this.
