### ISSUE TITLE
Error in progeny evidence

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#188]
The first line of http://storage.googleapis.com/ot-releases/18.08/progeny-23-07-2018.json.gz is "Parsed all HGNC genes - source: http://ftp.ebi.ac.uk/pub/databases/genenames/new/json/hgnc_complete_set.json" this is not a valid evidence string and should be removed and prevented from being added to future evidence generation runs.

**Comment by MichaelaEBI** [comment]
There are 196 lines in the progeny_normalVStumor_opentargets.txt file which are converted into a JSON file with 407 lines. 392 of these lines are in the validated-data-progeny ES index. Of the 15 lines that do not make it into the ES index, 14 are duplicates and 1 is the first line mentioned by @afaulconbridge above.

Of the 392 lines, only 308 are deemed valid meaning that 84 evidence strings do not pass validation. All 84 invalid strings have a disease error because their disease ID is ID EFO_0000000:
```
GET 18.08_validated-data-progeny/_search
{
  "query": {
    "bool": {
      "must": [
        {"match": {
          "disease_id": "http://www.ebi.ac.uk/efo/EFO_0000000"
        }},
        {"match": {
          "explanation.disease_error": "true"
        }}
      ]
    }
  }
}
```
Checking the JSON file reveals that EFO_0000000 appears in 87 evidence strings (29 times each for the 3 cancer types below) which means that of the 84 dropped evidence strings one each is a duplicate indicating that the 14 dropped evidence strings that do not make it into the ES index correspond to one replicate per cancer type. Looking at the cancer type mappings, it appears that for this pathway 'PI3K'     : ['PIK3CA', 'PI3K(Class1)'], both genes are mapped to PIK3CA resulting in replicate entries for each cancer. I will find out which protein PI3K(Class1) should refer to.

Affected evidence strings | JSON data
-- | --
29 | "disease": {"id": "http://www.ebi.ac.uk/efo/EFO_0000000", "name": "colorectoral adenoma"}
29 | "disease": {"id": "http://www.ebi.ac.uk/efo/EFO_0000000", "name": "kidney renal papillary cell carcinoma"}
29 | "disease": {"id": "http://www.ebi.ac.uk/efo/EFO_0000000", "name": "kidney chromophobe"}

These three cancer types have been added after the publication came out. I will check whether it is ok to include these three cancer types now.

**Comment by MichaelaEBI** [comment]
@afaulconbridge I cannot see where the first line is written into the PROGENy JSON file. The code for SLAPEnrich is nearly identical and the SLAPEnrich file does not have that line.

**Comment by afaulconbridge** [comment]
I think it came from the HGNCParser indirectly, but I agree as long as the 18.08 file isn't used directly and this line isn't in a newly generated file, this ticket can be closed.

**Comment by ElaineMcA** [comment]
Will be addressed post EFO 3 release.  Moved to 19.04.

**Comment by MichaelaEBI** [comment]
The line from the HGNC parser is not written into the JSON file anymore and the three missing cancer type mappings have been updated:

```
'KICH': {'uri': 'http://www.ebi.ac.uk/efo/EFO_0000335', 'label': 'kidney chromophobe'}, # EFO label: chromophobe renal cell carcinoma
'KIRP': {'uri': 'http://www.ebi.ac.uk/efo/EFO_0000640', 'label': 'kidney renal papillary cell carcinoma'}, # EFO label: papillary renal cell carcinoma
'COREAD': {'uri': 'http://www.ebi.ac.uk/efo/EFO_0005406', 'label': 'colorectoral adenoma'} # EFO label: colorectal adenoma
```

The 'PI3K' pathway question will be addressed tomorrow.

**Comment by MichaelaEBI** [comment]
**Update**: The extra line at the beginning of the PROGENy evidence file `Parsed all HGNC genes - source: http://ftp.ebi.ac.uk/pub/databases/genenames/new/json/hgnc_complete_set.json` was there because the last PROGENy evidence file has been generated by saving `print` output to the screen as a JSON file because the proper writing method does something funky - for all genes of a pathway-disease combo the evidence string for the last gene in the pathway gene set is repeated for each member of the pathway even though the evidence strings are generated correctly.

**Comment by MichaelaEBI** [comment]
Closing this ticket because the 'PI3K' pathway question is covered in this ticket #713
