### ISSUE TITLE
Reviewing the updated Gene2Phenotype data

### ISSUE THREAD

**Issue by DSuveges** [opentargets/platform#1880]
Following up the recent updated of the Gene2Phenotype dataset, we have to take a look and see if there are any substantial changes that:

- [x] **Yes** - Requires updates in the evidence parsers
- [x] **No** - Requires updates in the evidence schema
- [x] **Yes** - Requires updates in the ETL configuration eg. score calculation.
- [x] **No** - Requires updates in the front-end.

Based on the above answers the required changes needs to be communicated to the relevant teams and scoped for the 22.02 release.

**Comment by DSuveges** [comment]
### Comparing the fields in the new dataset with existing data:

| Old | New | Description |
|:----|:----|:------------|
|gene symbol | gene symbol | HGNC gene symbol | 
|gene mim | gene mim | gene identifier in the OMIM database |
|disease name | disease name| disease name in the OMIM database |
|disease mim | disease mim | disease identifier in the OMIM database |
|DDD category | **confidence category** | confidence category of the annotation |
|allelic requirement | allelic requirement | allelic requirement | 
|mutation consequence | mutation consequence | consequence |
|phenotypes | phenotypes | list of phenotype annotations in the human phenotypes onotology |
|organ specificity list| organ specificity list| |
|pmids | pmids | list of pmids |
| panel | panel | |
|prev symbols | prev symbols | |
|hgnc id | hgnc id | gene identifier in the hgnc database |
|gene disease pair entry date | gene disease pair entry date ||
| | cross cutting modifier |
| | mutation consequence flag |

### Values in `confidence category` changed

* `confirmed` =>  `definitive`
* `possible` => `limited`
* `probable` => `strong`

### Required changes:

- [ ] Updating data source parser script to map correct column names.
- [ ] As the list of available fields in confidence category has changed, the ETL configuration needs to be updated to calculate score.
- [ ] The new fields `cross cutting modifier` and `mutation consequence flag` are too sparse and bares limited information on the evidence, rather not capture. See [documentation](https://www.ebi.ac.uk/gene2phenotype/terminology) for details.
- [ ] No update on fronted is required.

**Comment by ireneisdoomed** [comment]
As for the `confidence` values that need to be changed in the [config](https://github.com/opentargets/platform-etl-backend/blob/master/src/main/resources/reference.conf), these are all the possibilities and their proposed scores:

| Confidence                  | Score following prev G2P's approach | Score following GenCC's approach  |
|-----------------------------|-------------------------------------|-----------------------------------|
| limited                     | 0.25                                | 0.01                              |
| moderate (newly introduced) | ? Between limited and strong                                   | 0.5                               |
| strong                      | 0.5                                 | 1.0                               |
| definitive                  | 1.0                                 | 1.0                               |
| both RD and IF              | 1.0                                 | 1.0                               |


By looking at how [GenCC defines the different levels of confidence](https://clinicalgenome.org/site/assets/files/3349/distefano_gencc_ccg_2019.pdf) you can see that for example `strong` means unequivocal t/d evidence. Given this, I'm in favor of using the second approach so that scores are harmonized with those of ClinGen.
