### ISSUE TITLE
Include single cell RNA seq in platform

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#193]
Open Targets is planning to include single cell RNAseq data into the platform. Like the other expression data, single cell RNAseq data fits into the platform in two ways: disease-related differential expression experiments as evidence and baseline expression data as target annotation for target prioritisation.

This forms a further stage of an existing OTAR project - where a widget is under development by Atlas.

**Baseline Expression Data**
Baseline expression data is likely to be the first type of single cell RNAseq data to be included into the Open Targets Platform. Pancreas is the first tissue with single cell RNAseq data with one or two other tissues to follow soon.

 - [ ] [Specification](https://docs.google.com/presentation/d/1IM-HZg_YQ_dfDB7KSLzrNaezO-BNunFC1d2GVau_qd4/edit#slide=id.p) for how to include or link to single cell RNAseq results from the Open Targets Platform
- [x] If Open Targets is planning to use the Expression Atlas widget for single cell RNAseq data, provide specs to Atlas

**Single cell RNAseq data as evidence**
Discussed plans for inclusion of single cell RNA seq in brief with Suhaib and Pablo on 01Oct2018: Currently only 4 experiments have a disease link. Single cell RNAseq data will be held under different site in short-term so the file would be provided separately to existing submissions; plan is to merge this site with main Atlas site in 6 months.

@MichaelaEBI to confirm w/ Ian if any other data providers plan to provide this data type.
@MichaelaEBI to confirm schema change that may be needed?

**Comment by AsierGonzalez** [comment]
**Update: Baseline t-SNE widget**
OT team (@MichaelaEBI, @andrewhercules, @peatroot and @AsierGonzalez) and Atlas developers (Alfonso Muñoz-Pomer and Haider Iqbal) have met twice to discuss the t-SNE widget:

- The widget will replicate the two t-SNE plots that Atlast show in their website (e.g. [pancreas scRNA-seq](https://www.ebi.ac.uk/gxa/sc/experiments/E-GEOD-81547/Results)).

- The widget will be accessible from the target profile page (more information in the Specification file linked above) and it will allow the user to choose the colouring rule of the left-hand side plot.

- The widget will be called with an Ensembl gene id (fixed in the target profile page) and an experiment id. After discussions with @mkarmona, we need to ask a curator in the Atlas team to provide a file (tsv or json) containing experiment ids and uberon codes that can then be used to call the widget. Something like:
 ``E-GEOD-81547              UBERON_0001264```

**Comment by AsierGonzalez** [comment]
**Update: Baseline t-SNE widget**

I have been in touch with Haider in Atlas team to track progress on t-SNE widget. They were expeting to have it ready by mid May but this has been delayed and now they have pointed us to a [repo](https://github.com/ebi-gene-expression-group/scxa-tsne-widget) that still lacks the full functionality. In Haider's words: 

> It contains the latest code. At the moment you won't be able to see the plots and metadata options because backend code for widget is still under review. [...] For now please explore the code and let me know if you have any questions regarding it.

Considering the summer holidays the new expected date to have a functional widget is **August**.

In the interim, there is also an ongoing effort together with Nancy in the Atlast team to curate scRNA-seq experiment. In the March Single Cell Expression Atlas relesease there were 24 human studies and 6 of them had been flagged as interesting (more info can be found in this [spreadsheet](https://docs.google.com/spreadsheets/d/1bDNSaKDb1U9ky6asis9e5Xec-uDUN89pWuNiBByU2Pc/edit#gid=0l)) but it is expected that in the next release the amount of studies will double .

**Comment by d0choa** [comment]
Further scoping is required for this task together with the ExpressionAtlas team. Closing as there is no action attached to it.
