### ISSUE TITLE
Ensuring that the FTP buckets are properly named

### ISSUE THREAD

**Issue by ktsirigos** [opentargets/platform#1981]
We noticed that in the latest release (22.02), the folder on the FTP site was accidentally name 22.02.04 (=using the version of the release that was used).

Can we check POS to make sure that, moving forward, the final naming of the folder remains consistent, i.e. XX.ZZ?

On the same note, do we need these two folders to be present at the FTP?

http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/18.04_DEV/
http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/19.04.4/

It seems they should be removed as well?

**Comment by mbdebian** [comment]
The FTP has already been renamed, but this issue is actually on us, rather than POS, because Platform Output Support will use whatever bucket we tell it to use.
We don't do patch releases, so we should probably stick to the Major.Minor release instead of going on with patch numbering when processing a release.
Regarding [18.04_DEV](http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/18.04_DEV/) and [19.04.4](http://ftp.ebi.ac.uk/pub/databases/opentargets/platform/19.04.4/), they've been out in the community for so long that we should probably leave them there, it's just a matter of doing the future ones in the way we want them to be.
I think we can probably close this issue, right @ktsirigos ?

**Comment by d0choa** [comment]
19.04.4 was the first when I joined the team. That was an actual patch on a previously attempted release.

**Comment by d0choa** [comment]
At the moment, the FE assumes the releases are in the format XX.XX

**Comment by mbdebian** [comment]
That's fine @d0choa , PIS takes an input parameter that tells the software where to upload the collected data, and POS takes in the release number in its [config file](https://github.com/opentargets/platform-output-support/blob/main/config_platform.tfvars), neither PIS nor POS create the folders
I think it is safe to close this issue, as it's not really a technical issue, but a "human practice" when creating a release.
