### ISSUE TITLE
JSON validation requires one object per line, breaks on pretty-printed JSON

### ISSUE THREAD

**Issue by Docproc** [opentargets/platform#211]
The command-line validation tool in opentargets/validator gives errors when a syntactically and semantically valid JSON file with "pretty" line breaks and whitespace is passed to it. The same file with the line breaks and whitespace removed validates without errors.

This is because the tool requires a single JSON object per line. Hence it is specific to the file format required by Open Targets for the evidence submission, it is not a general-purpose JSON validator.

Examples of files that are valid and invalid (according to the validator) are below. (Note that they are JSON files but had to be renamed to `.txt` to allow them to be attached)

[eva_single.txt](https://github.com/opentargets/platform/files/2500848/eva_single.txt)
[eva_single_pretty.txt](https://github.com/opentargets/platform/files/2500849/eva_single_pretty.txt)

Suggested improvement: have the validator detect this and explicitly warn about it.

**Comment by afaulconbridge** [comment]
I don't think this can be implemented in practice, without lots of additional pre-processing. The readme now documents this, and hopefully the error messages are clearer (see opentargets/platform#401 ), so that should minimize the impact of this issue.

I'm going to close this - but it can be re-opened if there is a good rational for the effort.
