### ISSUE TITLE
Remove unused fields from /private/target/<geneId> endpoint

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#215]
The following fields are used by the front-end:

```
approved_name
approved_symbol
biotype
cancerbiomarkers
chemicalprobes
chromosome
dbxrefs
drugs
ensembl_description
ensembl_external_name
ensembl_gene_id
gene_end
gene_start
go
hallmarks
id
mouse_phenotypes
name_synonyms
ortholog
pdb
previous_symbols
reactome
status
strand
symbol_synonyms
uniprot_accessions
uniprot_function
uniprot_keywords
uniprot_id
uniprot_subcellular_location
uniprot_subunit
```

The following fields are not and could therefore be removed entirely from the REST API to reduce bloat. Many take the value `null`, `[]` or `{}` seemingly all the time. They may be useful within the back-end codebase, but could be removed from the API at least.

```
alias_name
alias_symbol
ccds_ids
chembl
cytobands
data_release
drugbank
ensembl_assembly_name
ensembl_gene_version
ensembl_release
entrez_gene_id
enzyme_ids
gene_family_description
gene_family_tag
hgnc_id
interpro
is_active_in_ensembl
is_ensembl_reference
is_in_swissprot
locus_group
pfam
previous_names
protein_classification
pubmed_ids
refseq_ids
uniprot_mapping_date
uniprot_pathway
uniprot_similarity
vega_ids
```

**Comment by andrewhercules** [comment]
I'm all in favour of reducing the size of the REST API response from the `/private/target/<geneId>` endpoint. 

One suggestion I have is that the endpoint could only serve summary statistics that we need for a dashboard view. That would ensure that the dashboard loads quickly and isn't slowed down by unnecessary data. When a user clicks a widget and is taken to a detail view, we could run another request to a new (?) endpoint that takes the geneId and widgetId and returns only the relevant data. For example, if a user clicks the drugs widget on the BRAF dashboard, we could run a call to an endpoint like `/private/target/ENSG00000157764&data=drugsWidget`.

This isn't all that different from the current architecture as for many of the accordion tabs, we run another call already. Instead, the change would be to the endpoint that would only return the relevant data in an effort to improve the Platform's speed and responsiveness.

But maybe instead of building another endpoint, this is something we could implement with a GraphQL interface server in front of the current API?

**Comment by emepyc** [comment]
@andrewhercules bear in mind that not all the information that is displayed in the target profile page is stored in the ot backend and served by the api.
Specifically, information for the gene tree, protein structure, gtex expression data, protein interactions, etc are external

**Comment by d0choa** [comment]
@mkarmona looking at this to start implementation of the graphQL schema

**Comment by d0choa** [comment]
Closing as the new graphQL API will provide a new set of agreed fields
