### ISSUE TITLE
wrong python example in documentation for POST query for list of targets (rest api doc)

### ISSUE THREAD

**Issue by emepyc** [opentargets/platform#217]
In the documentation of the rest api, in the section describing how to get information about a list of targets:
http://api.opentargets.io/v3/platform/docs#operation/postTargetByENSGID

the python example is using a `GET` request rather than a `POST` request.

**Comment by deniseOme** [comment]
@emepyc I believe this is now fixed in both URLs containing our API doc. See screenshots below.

![screen shot 2019-01-28 at 10 45 13](https://user-images.githubusercontent.com/6472381/51831368-dce17c00-22e9-11e9-9ab3-9747d8f2b6df.png)

![screen shot 2019-01-28 at 10 47 07](https://user-images.githubusercontent.com/6472381/51831477-1a460980-22ea-11e9-966e-1a9414b87cc1.png)

**Comment by AsierGonzalez** [comment]
Hi @deniseOme,

I'm afraid it is not, the python code still uses `requests.get()`:
 
<img width="445" alt="screenshot 2019-01-28 at 10 51 52" src="https://user-images.githubusercontent.com/11410715/51831751-d0115800-22ea-11e9-850a-f831a5167204.png">
 
I'm reopening the issue.

**Comment by AsierGonzalez** [comment]
As suggested by @emepyc in #219, the body of the request seems to be incorrect as well and the key for targets should be "id" instead of "target":
 ```
{
  "id":["target1", "target2"],
  "facets" = "true"
}
```

**Comment by AsierGonzalez** [comment]
The API documentation is no longer at http://api.opentargets.io/v3/platform/docs and the [new documentation](https://docs.targetvalidation.org/programmatic-access/rest-api) does not seem to include example code so that part of the ticket is not relevant any more.
The second part, is still problematic as it is shown in [swagger](https://platform-api.opentargets.io/v3/platform/docs/swagger-ui#/private/postTargetByENSGID) and it needs to be fixed.

**Comment by d0choa** [comment]
No work is expected in swagger for the previous API
