### ISSUE TITLE
Benefit of having Target column (plus others) in the Target profile page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#222]
Following users' requests in the past, we have added a a column called "Target" in the Drugs table in the Disease profile page.

![screen shot 2018-10-25 at 11 52 42](https://user-images.githubusercontent.com/6472381/47495678-9c86e380-d84c-11e8-9778-d7e0a0e3ba59.png)

The same column is available in the Drugs table in the Target profile page and I wonder what the benefit of that is as 

1) It's redundant information: I'm on the profile page of CD86, and in the table all the rows have the same target in the Target column i.e. CD86

2) CD86 in the Target column is hyperlinked but it leads to the same page I'm already at.

![screen shot 2018-10-25 at 11 56 05](https://user-images.githubusercontent.com/6472381/47495796-fdaeb700-d84c-11e8-8ed7-4ffc1309cd84.png)

I can't seem the added value with this column.  Is there one?
Notice that when the table is downloaded in .CSV the sheet does get named as CD86--known_drugs.csv.

Note that many other columns in this table on the Target profile page are redundant. Perhaps something to keep in mind when redesigning the Drugs table, @andrewhercules?

**Comment by MichaelaEBI** [comment]
The drug tables on the Target, Disease and Evidence pages have the same format and that's why the target column shows up on in Target profile page drug table. @andrewhercules would know best what the status of the drug table re-design is.

**Comment by andrewhercules** [comment]
With the current app architecture, the drugs table directive used on the disease profile page, the target profile page, and the evidence page is the same. And so some of the columns are redundant, depending on the page you are on. With the target column, because it provides relevant information for users on the disease profile and evidence pages, it was included at the request of multiple users - even though it is redundant for the target profile page.

We will consider this when we redesign the drugs table - although the primary focus is aggregating the data by phase and status so that we can show a more complete list of drugs and compounds. However, if the same table component is reused across multiple pages within the Platform, there may be redundant columns as the table will need to be flexible to meet various use cases.

**Comment by MichaelaEBI** [comment]
Closing this ticket since we are aware of this issue and it will be addressed when we redesign the drugs table.
