### ISSUE TITLE
Update info on wikis in the different repositories

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#230]
There is a lot of information distributed across wikis for different repositories. Some information is outdated and some has been replaced by google sheets and others.

The goal of this issue is to:
- [ ] Generate an inventory of repositories that have wikis with information and what information they provide
- [ ] Specify what information we should provide and where
- [ ] Update the wikis

**Comment by d0choa** [comment]
@andrewhercules I'm inclined to let this go. I don't think wikis are regularly used, but they might have some legacy information that might eventually become relevant.

If you think there is value on improving their organisation please comment here. Otherwise, we could close this ticket

**Comment by andrewhercules** [comment]
I'll check the wikis listed in the [wiki spreadsheet](https://docs.google.com/spreadsheets/d/1uYEPtEP6f6XLRuy2PkxYtYiNIu4Um5JjA0TguKZO27A) but I suspect many are out-dated and no longer used.

**Comment by andrewhercules** [comment]
Ticket closed as wiki in [data_release](https://github.com/opentargets/data_release) repo reviewed and because content is outdated and superseded by recent updates, wiki has been hidden and repo archived.

Other GitHub repos have wikis with historical content that can be reviewed and archived as needed.
