### ISSUE TITLE
OTAR015 - CRISPR data: Define how the data should be included in the platform

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#276]
**_The options for inclusion of the CRISPR data from OTAR015 currently are:_**
1. Create a new datatype.
2. Add it as a new data source to an existing data type.
3. Add it to Affected Pathways which will be changed to Pathways & Systems Biology soon.
4. Other?

We need to think about the use cases and implications (changes to association and evidence pages for example) of each option. 

Some relevant information can also be found in this ticket: https://github.com/opentargets/platform/issues/78

**Use cases**

**Comment by andrewhercules** [comment]
Take my thoughts with a grain of salt ...

But would the best option be 3 - adding it to the pathways and systems bio data? Reason being that if the underlying benefit of the data is showing if a particular gene is essential in a cancer cell, its sort of like saying "this gene is involved in a cancer-causing pathway"?

Alternatively, because we have other CRISPR projects ongoing, is now the time to open up a new datatype to accommodate future growth?

Also, I think we need to consider adding summary data to the target profile page as their website will have a target page that we can link to. I'll follow up with Miguel P. to see if I can get updated screenshots.

**Comment by iandunham** [comment]
We also need to think of this in the light of other potential CRISPR data we will get, and whether we want to give that sort of data it's own data type. The Affected pathways type is an underused slot, so putting more data into that makes sense, but we need to get the naming right.

**Comment by deniseOme** [comment]
Worth taking into account that some users may not expand the data types to select individual data sources. So some users may miss out finding this new and cool CRISPR data.

One comment from user: 
* make clear the CRISPR data comes from Open Targets (as they will assume it's better quality than other data sources).

Potential UX design sessions with Talisman Therapeutics staff on how to display CRISPR data in the Platform:
Martin Crossley and Tom Campbell

**Comment by andrewhercules** [comment]
Updated screenshots for the CRISPR portal have been provided by Miguel P. and are available on the [OT Platform Team Google Drive].(https://drive.google.com/drive/folders/1OJqYKMYnI6tODMWjBkQslaUAEwQ1XEDP)

**Comment by MichaelaEBI** [comment]
It was decided to move this data into the Pathways & SysBio data type. Progress can be followed here: #163.
