### ISSUE TITLE
Slapenrich evidence with pvalue of zero

### ISSUE THREAD

**Issue by afaulconbridge** [opentargets/platform#289]
For 762 out of 90431 evidence strings, the pvalue is reported as "0" which means they do not pass validation and are not used.

The generation should be checked to confirm if this is the correct value, and if not it should be fixed. If it is correct, then we should avoid generating these as they are not used.

**Comment by AsierGonzalez** [comment]
Why is 0 not an acceptable value? I don't know how slapenrich works in detail but, generally, a 0 pvalue is not a problem.

**Comment by MichaelaEBI** [comment]
I will look at SLAPenrich for 18.12 (I do not have a ticket yet, but it is on my list!) because ~16,000 SLAPenrich evidence strings have a p-value > 1e-4 which means that we deem them non-significant (score=0) and these evidence strings are not used. I will also look at data with p-value = 0 when I filter out data with p-value > 1e-4.

**Comment by MichaelaEBI** [comment]
The '0' p-values are very small p-values. I am closing this issue since these p-values will be addressed in issue #292.
