### ISSUE TITLE
Update API Documentation (including python client)

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#291]
A summary of currently available documentation and tutorials can be found in [this document](https://docs.google.com/document/d/1_GFRiEYMBSkDTFjolCA0EWu_IOSgBPRiW6GSCgPkYkg/edit#heading=h.mkkjfpfxhd73).

**Plan for API documentation:**
- From API on OT homepage link to 'Documentation' and 'Python client'
- Swagger doc for the API doc & read-the-docs for the python client

**API Documentation**
- [ ] Read through the website and make sure it is up-to-date and correct (ie., remove link to this very same page)
- [ ] Make it look like OT documentation (similar to this one: https://api.opentargets.io/v3/platform/docs)
- [ ] The interactive section: all ‘actions’ are visible when the website is loaded making it hard to get an overview of what is in this section (filter, retrieve, search, public, private, utils)
- [ ] Make sure all queries work
- [ ] Add more links to tutorials and examples, make sure these are up-to-date, especially the ‘Getting started’ blog post
- [ ] Introduce the python client and link to its documentation

**API Python client documentation**
- [ ] Check whether pip install works
- [ ] First link to Open Targets API should link to the swagger API documentation, not the platform home page
- [ ] Go through documentation and make sure everything works
- [ ] Find out what there is left ‘To Do’ for Utility & Connection
- [ ] Clearly link to the github repository
- [ ] Make sure the readme on the github repository is up to date
- [ ] Eventually combine readme & read-the-docs to minimise maintenance?

**Other items**
- [ ] Move tutorials from OT platform docs
- [ ] Re-release an updated version of 'Open Targets API Tutorial: Getting Started' blog post
- [ ] Add the use cases in the document above to both docs

Other tickets that will be looked at: #217, #219, #221

**Comment by deniseOme** [comment]
I consider the more pressing items in this ticket to be largely addressed now e.g.

- [ ] From API on OT homepage link to 'Documentation' and 'Python client'
- [ ] Introduce the python client and link to its documentation

in addition to modifications to the original list above e.g.

- [ ]  Re-release an updated version of 'Open Targets API Tutorial: Getting Started' blog post

is no longer applicable as we have decided to move this to a new [tutorials page](https://docs.targetvalidation.org/programmatic-access/api-tutorials).

Any new tutorials would go in the docs page rather than blog for the Open Targets Platform.
