### ISSUE TITLE
Tractability heat map on target profile page not highlighting correct cells

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#309]
### Observed Behaviour ###

On the [target profile page for VCP](https://www.targetvalidation.org/target/ENSG00000165280?view=sec:tractability), the tractability heat map shows that the target hits the following buckets:

![screen shot 2018-11-19 at 5 48 38 pm](https://user-images.githubusercontent.com/7490258/48722038-63f7e100-ec23-11e8-8e72-667377524ec1.png)

In the image, it looks like the target hits buckets 5, 6, and 8. However, according to the .TSV file from Chris and [the API response](https://api.opentargets.io/v3/platform/private/target/ENSG00000165280), it should hit buckets 4, 5, 7, 8.

### Expected Behaviour ###

The heat map should correctly render the data from the API response and in this case, highlight the `PDB targets with ligands`, `Active compounds in ChEMBL`, `DrugEBIlity score 0 to 0.7`, and `Druggable Genome` cells.

**Comment by LucaFumis** [comment]
Hi Andrew, yes the bucket-column mapping there is incorrect.
This is fixed for the new release (i.e. v2 of prioritisation view + batch search) but I can cherry-pick the commits and push that with next mini-release:

![screen shot 2018-11-19 at 17 10 31](https://user-images.githubusercontent.com/8592363/48723619-02ce0e80-ec1f-11e8-941c-838bd0a28446.png)

**Comment by LucaFumis** [comment]
Pushed mini-release with the fix.

**Comment by deniseOme** [comment]
I've come across another example of inconsistency between [UI](https://www.targetvalidation.org/target/ENSG00000142192) and [API response](https://api.opentargets.io/v3/platform/private/target/ENSG00000142192) for small molecules:

API response:
* SM: 4, 5, 7, 8

UI rendering:
* SM: 4, 5, 6, 8

**Comment by deniseOme** [comment]
It turned out this is not a bug. Thanks @andrewhercules for the explanation.
The correspondence between buckets and cells highlighted in purple in the UI is a weird one and confusing when compared to the API response.

The order of the cells in the table is 
bucket 1
bucket 2
bucket 3
bucket 4
bucket 7
bucket 5
bucket 6
bucket 8

We will convey this into our docs/Chris' blog post as users may assume the order of the cells in the UI is bucket 1, 2, 3, 4, 5, 6, 7, 8.

It may be worth showing in the UI which cell corresponds to which bucket.

Also, buckets 9 and 10 from the original paper have been either dropped or are not shown.
