### ISSUE TITLE
tractability buckets in the API response

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#348]
We need to make the API response below more intelligible and change the bucket numbers (e.g. 4, 5, 7, 8) to something else or at least add an explanation following the numbers.

https://api.opentargets.io/v3/platform/private/target/ENSG00000142192

We could use the explanation that is available below (or a modified version of it):
https://docs.targetvalidation.org/getting-started/target-tractability

e.g. 

Buckets | Small molecule | Monoclonal antibody
1 | Targets with drugs in phase IV | Targets with drugs in phase IV

etc...

<img width="553" alt="screen shot 2018-12-05 at 10 44 50" src="https://user-images.githubusercontent.com/6472381/49508614-0ac2bb00-f87b-11e8-80ea-8e60bffcd7a6.png">

**Comment by mkarmona** [comment]
@deniseOme APIs are not meant for human consumption but rather machine consumption whether the method is in a systematic way or not. Although, I agree that sometimes the contained information may be a bit cryptic. So, would it be good having an entry on Gitbook talking about tractability information and its meaning?

**Comment by deniseOme** [comment]
Bucket numbers are really really cryptic and can lead to confusion and frustration from the users as it has been observed at Healx last week.

Not sure what you mean by entry on gitbook. Isn't the link I pasted above (our docs) in gitbook?

**Comment by mkarmona** [comment]
@deniseOme true. the doc entry seems to be good. But are you suggesting changing the API 
response?

**Comment by andrewhercules** [comment]
In principle, I agree 100% that we should change the API response to include more information about tractability data and buckets. It's good practice to have an API that works for the end-user - in this case, an engineer or bioinformatician or data scientist looking to do further analysis. And recently I've seen more articles talking about UX-ing APIs - for example, [Keras' blog](https://blog.keras.io/user-experience-design-for-apis.html) and [Cisco's blog ](https://blogs.cisco.com/developer/design-your-apis).

But in the case of the Platform, I would strongly recommend that we refrain from adding more data to the response as it will make an already large response even larger. Let's say we added 5 more lines to each target object in the response. For a disease like `Alzheimer's disease`, we could be looking at another 25,000 lines in the response. More concerning is that for a disease like `breast carcinoma`, it would be more than 60,000 lines added to the response. 

In reality, we are likely looking at more than 5 lines per target because each modality has at least 8 buckets. And once the pipeline is expanded to cover additional modalities, we could be faced with even more buckets and more lines. And because I rely on the response from the `/private/associations` object to build the Prioritisation view, any additional data added to the tractability section of each target object could take away space and processing power for other key target attribute data (e.g. mouse models, safety flags, etc.).

And so I would recommend that we either:

1. Point users to the documentation
2. Creating a separate `buckets.csv` file that users can download and use for mapping

Alternatively, we could consider expanding the API documentation to cover each data source contained in the Platform, how to access it, and how to understand the response? And then a link to that documentation page is put front-and-centre at the top of the API response?

**Comment by ElaineMcA** [comment]
@deniseOme I expect that this one may have been discussed as part of the API meeting last week so assigning to you.  Please link/ update master tickets detailing actions from the meeting as needed.  

Thanks, E

**Comment by deniseOme** [comment]
@ElaineMcA, I'm sorry this was not discussed last week as it's not part of API documentation. Details on the agenda/outcomes of last week's meeting is [elsewhere](https://docs.google.com/document/d/1y2DmsA2pHYawIc1h3FHxvRvIGQi4FTqxzySwSkxxs_k/edit).

**Comment by deniseOme** [comment]
Will point users to the documentation on [target tractability](https://docs.targetvalidation.org/getting-started/target-tractability) for more info on the different buckets and aggregation into the 3 major categories highlighted in the UI.
