### ISSUE TITLE
Missing documentation for score method

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#370]
See https://github.com/opentargets/association_score_methods/blob/master/CTTV008_ChEMBL/description.md . This is linked as the method description in Chembl data.

**Comment by afaulconbridge** [comment]
I suspect we should remove that opentargets/association_score_methods repository, or at least make it private. Last commit was two years ago, so it seems like it is so out of date as to be unhelpful at best.

**Comment by MichaelaEBI** [comment]
Some folders are empty, but there is some information in there which I will pull out. Also, it will be good to know what links to this repository.

**Comment by pieterlukasse** [comment]
@MichaelaEBI the .json strings in chembl data point to this here:
```
"target2drug": {
 ...
            "resource_score": {
                "method": {
                    "url": "https://github.com/CTTV/association_score_methods/blob/master/CTTV008_ChEMBL/description.md"
                },
                "type": "probability",
                "value": 1
            },
```

**Comment by MichaelaEBI** [comment]
@pieterlukasse as described [here](https://github.com/opentargets/platform/issues/374), the `association_score_methods` repository is not updated anymore because we now have the [Open Targets documentation](https://docs.targetvalidation.org/getting-started/scoring) and we will get ChEMBL and UniProt to remove these links from their evidence strings.
