### ISSUE TITLE
Genomics England data does not have required publication field

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#38]
@elipapa commented on [Mon Jan 08 2018](https://github.com/opentargets/evidence_datasource_parsers/issues/3)

@emepyc commented on [Fri Dec 01 2017](https://github.com/opentargets/data_pipeline/issues/220)

The genomics evidence schema needs a non-empty publications array but the Genomics England PanelApp data doesn't provide one always.
In the December release, to make the schema happy, a _dummy_ publication has been added in the form: 

```
      "evidence": {
        "provenance_type": {
          "literature": {
            "references": [
              {
                "lit_id": "NA"
              }
            ]
          },

```
If the field is not mandatory it should not be required in the schema instead of bypassing the validation by including a "NA" value. Having these hacks undermine the benefits of having an schema in the first place.
As a side effect this requires including weak code in the webapp or any other consumer of the data.

**Comment by MichaelaEBI** [comment]
This issue is still valid. Of 11,079 Genomics England evidence strings, 6,059 contain 'NA' as literature ID. Examples [with literature](https://www.targetvalidation.org/evidence/ENSG00000166401/Orphanet_289586) and [without literature](https://www.targetvalidation.org/evidence/ENSG00000139618/EFO_0000311) ID.

For Genomics England evidence, the actual gene panel is listed in the `Evidence source` column - I wonder whether it makes sense to say `Genomics England` in the `Evidence source` column and list the specific gene panel in `Publications` column and if a publication is available, that would also be listed there.

**Comment by andrewhercules** [comment]
Reassigned to 20.11 pending further conversations with Genomics England

**Comment by ireneisdoomed** [comment]
After conversations with GEL (see #38) the API querying has been optimized - being able to get all the Publications terms without any raised errors.

This issue no longer applies.
