### ISSUE TITLE
mAB associated to 3 targets

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/platform#408]
Hello,

I believe the association to IL2A, IL2B and IL23A are correct.
https://www.targetvalidation.org/summary?drug=CHEMBL1201835

However, because I'm not sure on the mechanism of action, can you please check that the MoA is correct for Interleukin-23 inhibitor, please?
It indicates that the mAB connects to IL12B and IL23A. Might be correct but surprising.

**Comment by gkos-bio** [comment]
Looking at ChEMBL, I think there is a noticeable difference between our representation and ChEMBL representation of the targets. Maybe we should indicate that it's a protein complex?

**Comment by ElaineMcA** [comment]
@MichaelaEBI  - does this relate to protein complex discussions underway already with ChEMBL?

**Comment by MichaelaEBI** [comment]
@gkos-bio I am currently working with Paula from ChEMBL on evidence for drugs that target protein complexes. I agree that we should indicate whether a drug targets a protein complex. At the moment we have an evidence for each subunit of a protein complex, even if only one subunit is bound and it is known which subunit is bound. We want to change that so that if the binding subunit is known, we only have an evidence string for that subunit (the JSON schema needs to be changed for that). In this context I thought that we indicate protein complexes that are drug targets. I will create a detailed ticket later today and keep you updated.
