### ISSUE TITLE
Implement front-end changes for version 1 of the target safety data on the target profile page

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#460]
### Use case(s)

1. As a user, I want to know about the potential safety information for a given target - specifically the organs/systems effected and the individual effect

### Mockup ([Full size version](https://drive.google.com/open?id=1iQrHuADQGWXQjAx8O1FmjHMvki9I9J6g))

![safety_data_mockup_target_profile_page_gh](https://user-images.githubusercontent.com/7490258/53641709-addf6280-3c27-11e9-8aa9-d8071a4be691.png)

### Data, design, and interaction notes

* Data made available via target index object
* If target index object does not include any safety data (e.g. for a target like ESR1), the `Target safety` accordion tab will not be displayed
* If target index object does include safety data (e.g. for a target like ACHE), the `Target safety` accordion tab will be displayed and on page load, the tab will be open automatically, similar to how the `Classification` tab is open by default on the disease profile page
* Data to be displayed in a basic data table with the following headings: `Main organs & systems affected`, `Agonism or activation effects`, `Antagonism or inhibition effects`, `Reference`
* Within the `Agonism or activation effects`, `Antagonism or inhibition effects` columns, individual effect should be as an unordered list underneath the parent term (`Acute dosing`, `Chronic dosing`, `General`, and `Developmental toxicity`), although not all parent terms will be present (e.g. some might only have `General` and `Acute dosing`)
* Within the data table, some terms will include a link to either the disease profile page or an external link (e.g. UBERON) - the full link will be provided by API response for initial version, but can be discussed/changed for subsequent versions
* For the `Reference` table column, link will direct users to EuropePMC page for relevant article

### Design assets

1. A full-size of the mockup is available on the [OT Core Platform Team Google drive]((https://drive.google.com/open?id=1iQrHuADQGWXQjAx8O1FmjHMvki9I9J6g)
2. An interactive prototype, showing proposed interaction on page load, is available [online](http://bit.ly/ot-safety-centre)
3. If possible, please include the alert icon in the accordion tab name. The icon is [the exclamation-triangle icon from FontAwesome](https://fontawesome.com/icons/exclamation-triangle?style=solid) (e.g. `<i class="class="fa fa-exclamation-triangle fa-lg""></i>`) in pure yellow (`#FFCC00`)

**Comment by EPetsalaki** [comment]
Hi @LucaFumis! I've just finished with the QA for the target safety and I just have two minor changes I'd like us to make if you can. 
1) Let's remove all term mappings for 19_04 (except the PMID links for the references), because they are very sparse for now. By the next release in June the terms I requested from EFO should be there, so we will be able to reinstate the links. 
2) The sentence above the safety table should change from "The following safety effects have been observed and noted in two publications by Lynch et. al., 2017 and Bowes et. al., 2002." to "The following effects have been observed and noted in one or more publications on drug target safety assessment." (because we have 3 publications right now and we'll have even more on the next release).

**Comment by andrewhercules** [comment]
@LucaFumis, can you please change the last column name from ``Reference`` to ``Publications``
