### ISSUE TITLE
--gen step hangs at the end when index is already existing

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#500]
The --gen step seems to hang after `INFO - join workers` if the --gen step is executed without first removing the `.._gene-data` index.

**Comment by pieterlukasse** [comment]
@afaulconbridge is the `--gen` step supposed to work if the index already exists? Or should it actually raise an error in this case?

**Comment by afaulconbridge** [comment]
It should work fine, regardless of the index existing or not. I suspect this is another instance of opentargets/platform#177 causing problems. 

For 19.04 and onwards, the multiprocessing on the `--gen` step has been removed, since in practice it didn't give a performance increase. This makes it more robust, since there is less opportunity for deadlock.

**Comment by pieterlukasse** [comment]
Ok, will close it for now since it is unlikely to return after 19.04

**Comment by pieterlukasse** [comment]
Actually, one question: what is it supposed to do if the index already exists? Should it drop the index and recreate it?

**Comment by afaulconbridge** [comment]
Yes, if it exists its designed to drop and recreate it. This ensures that it is created according to the appropriate configuration. Theres separate tickets to document and externaltise that configurations opentargets/platform#367 and opentargets/platform#504
