### ISSUE TITLE
Target profile page rewrite: Create Protein Interactions detail view

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#526]
### Use Cases

1. As a user of the Platform, I want to see an interactive visualisation showing the different interactions involving my target of interest and have the ability to filter the visualisation by interaction type. 

2. As a user of the Platform, I want to be see the publications supporting a particular interaction between my target of interest and another target so that I can explore an individual interaction in more detail.

3. As a user of the Platform, I want to be able to download the visualisation of interaction data so that I can include it in my reports about a specific target.

4. As a user of the Platform, I want to be able to run a batch search between two targets that I have identified from the protein interactions visualisation.

### Detail Views

_View when user first loads visualisation_
![protein_interactions_detail_view_on_load](https://user-images.githubusercontent.com/7490258/55174465-650ec100-5175-11e9-8c52-02376ec7a57c.png)
**[Full-size version](https://drive.google.com/open?id=1gBCy8iXWx4g1WpcS4agX9SbK30JcmHcr)**

_View when user clicks a target to look at a specific interaction_
![protein_interactions_detail_view_two_targets_selected](https://user-images.githubusercontent.com/7490258/55175134-a358b000-5176-11e9-90b9-eeca4b4ae59e.png)
**[Full-size view](https://drive.google.com/open?id=1_hCbQvBXAs0hMv8lSTAVsWlux8kVvEJ5)**

### Design and Interaction Notes

1. For the detail view description, please use the following text:

``Summary of interactions for GENE-SYMBOL based on OmniPath DB data. When 2 targets are selected, details on the interaction (including publications) are shown.``

Please replace ``GENE-SYMBOL`` with the HGNC gene symbol value.

2. Please integrate the existing interactions viewer library used in the current Platform.

3. Please update the API call to OmniPath DB to obtain the publication references. In the existing call, please append the ``fields=references`` parameter as noted in the [OmniPath DB API documentation](https://github.com/saezlab/pypath/blob/master/webservice.rst).

4. Using the list of PubMed IDs returned by the call to the OmniPath DB API, please construct a link to EuropePMC passing through the IDs as parameters. Please display this link within the pop-up that appears when a user has selected two targets. 

5. In the pop-up that appears when a user has selected two targets, please create a button that takes users to the batch search page for the two targets. Please style the button in Open Targets Corporate Blue - ``#3489ca``.

### Design Assets

1. [Open Targets brand palette colour codes](https://drive.google.com/open?id=1d0JDmCznInsANZoQC77gadTf9jO0UDOo)
2. [Full-size versions of mockups](https://drive.google.com/drive/folders/1GEltZ8Dc8oKW9V7T8NZf-Q1t5WI7c8Gr)

**Comment by peatroot** [comment]
@andrewhercules, following discussions with @d0choa, I have reimplemented the interactions viewer, rather than insert the version in the live site.

The main differences (some of which you can see) are:
* it is now possible to select multiple proteins (and will therefore be possible to batch search them also)
* interactions are displayed in a table, broken down by source, with references
* interaction counts now update depending on filtering
* avoidance of depending on an old version of d3
* colours for interaction types come from your palette

Thoughts welcome.

<img width="1506" alt="Screenshot 2019-05-21 at 16 31 05" src="https://user-images.githubusercontent.com/7376272/58109645-eae34180-7be5-11e9-96e1-8dba5d63dfe7.png">

<img width="1508" alt="Screenshot 2019-05-21 at 16 30 05" src="https://user-images.githubusercontent.com/7376272/58109660-f46ca980-7be5-11e9-9e85-85d22f998179.png">

<img width="1507" alt="Screenshot 2019-05-21 at 16 30 26" src="https://user-images.githubusercontent.com/7376272/58109672-f9315d80-7be5-11e9-9aee-a36267c62762.png">

**Comment by d0choa** [comment]
@andrewhercules please have a thorough look to it. We think it's an improved version but we need your pair of eyes to confirm it. It would be nice to spot any lost functionality or strange behaviour.

**Comment by andrewhercules** [comment]
@peatroot - looks great! It's a huge improvement over the current Platform implementation and I think it will scale up well for the OTAR044 data.

A few things:

1. The links under the ``Source`` and ``Target`` columns include an extra Ensembl ID - can we please remove it?

2. I noticed that a given target can appear in both the ``Source`` and ``Target`` columns. Is it worth processing the data to correct that, or should it remain as-is? 

![Screenshot 2019-05-23 at 13 04 40](https://user-images.githubusercontent.com/7490258/58251368-5dc1f900-7d5b-11e9-8a21-5eb1fdadc8ac.png)

3. Can we please add spacing margin between the visualisation and legend block? And can we please align the download SVG button and the legend and visualisation? Just to provide a clearer distinction between the visualisation and the data table.

![Protein_Interactions_v1_notes](https://user-images.githubusercontent.com/7490258/58251308-3c610d00-7d5b-11e9-999f-5a3a1d926526.png)

4. The colours for the different interaction types is a really nice touch - thank you! Although using red and green together causes an accessibility issue, I'm okay with that for now as we may need to further expand for other interaction types that will come through OTAR044.

![Screenshot 2019-05-23 at 13 14 27](https://user-images.githubusercontent.com/7490258/58251882-be056a80-7d5c-11e9-86a1-10a459cc44ec.png)

Also, @d0choa, I don't know much about this - so for my own knowledge - are the column headings of ``Source`` and ``Target`` how they are commonly referred to? I've seen so many different versions so am not sure if there even is an accepted way to denote target A (fixed) and target B (within the network).

**Comment by deniseOme** [comment]
I find confusing having two columns with a very similar name: `Sources` and `Source`.
Can we find another name for `Sources` please? Perhaps use "Resources" as this is how the original authors refer to?

https://www.nature.com/articles/nmeth.4077/figures/1

Is there a dummy page where this widget is available so that I can try it live? Not sure why we see two sets of colours above. Are the chips above clickable? Will they be?

Other points:
1) We refer to "Publications" and point to EPMC elsewhere in the Platform. Do we want to keep that name for consistency throughout? If so, we need to change "Reference" above to "Publications".

2) When we select for a target e.g. ESR1 above, do we really need to show a column showing ESR1 from top to bottom? On the same theme, if I selected ESR1 how come the last figure above sometimes have ESR1 under "Source".

3) Following @andrewhercules comments, can we rename `Source` to `interactors`? The selected entity would be the target e.g. ESR1, and the interactor will be something else.

In the current implementation we refer to selected nodes.

**Comment by d0choa** [comment]
Thanks guys for the feedback. This is really useful

About @andrewhercules comments:
- Regarding the same protein twice in the same entry. This will mean that a protein is interacting with other copies of itself. It's relatively common to see it this way. I don't think it will cause any misunderstanding.
- Source and target are good definitions. @peatroot probably use them because this is the way they are encoded in the api response. Since some of the interactions might be directional and some might not, this is a good generalisation. Target A/B would generate confusion for directional interactions, such as enzyme-substrate interactions.

About @deniseOme comments:
- @peatroot please change "Sources" for "Resources" and "Reference" to "Publications" in the table header.
- I think the 2 sets of colors are because @andrewhercules was playing with an alternative palette without accessibility problems. In general the colors are a legend to know what sort of evidence every resource contains. Since they are very diverse in the nature of the interaction, the interpretation of the evidence might be very different, for example depending if they are a protein-protein interaction or a enzyme-substrate interaction. At the moment they are not clickable and I'm not sure if we want them to be.
- When you search for ESR1, ESR1 can be the source or the target in a particular interaction. The order is important for some types of interactions.

Once the table header and the layout look good, we can close this issue

**Comment by d0choa** [comment]
I'm closing this and generating a different issue for the table headers
