### ISSUE TITLE
consider consistency when displaying publication information on new target safety field

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#568]
Great to see the safety data in the target profile page of TBK1:

https://qa.targetvalidation.org/target/ENSG00000183735

For future iterations and as part of the redesign of the target profile page, it will be worth considering to display publication information in a consistent manner.

When we compare for example target safety and mouse phenotype, the last column is called "Reference" in the former, and "Publications" in the latter.

We also refer to Lamore (2017) but it should be Lamore et al (2017).

Would we consider changing the data in the row for mouse phenotype from "publication" to "Ishii et al (2008).

Whichever route we take, we should try to be consistent throughout.

![Screen Shot 2019-04-16 at 10 38 24](https://user-images.githubusercontent.com/6472381/56199388-bdc6d080-6034-11e9-8a9f-9cb6355c2fef.png)

more details on #460

**Comment by EPetsalaki** [comment]
At the moment we will have one row per publication on the safety data, so it makes sense to display the name of the publication. I will change the name on the input file to include 'et al' on these. On the other hand, I think for the mouse data we can get more than 1 publication. Would it look alright if we had multiple names?

**Comment by andrewhercules** [comment]
@deniseOme, we already use the ``X publication(s)`` as the main design pattern and that continues to be used with the redesign. 

As @EPetsalaki noted, we show the individual publication because of the nature of this data. Also, there are likely to be duplications between the publications in the effects columns and providing the individual reference gives our users a sense of what is different about each row. As this is the first run at adding safety data, we're using it as a pilot to try and address concerns with tables like the known drugs table where it is not immediately clear what differences are between each row. 

But as for the column name, I agree and will update the ticket and ask @LucaFumis to rename ``Reference`` to ``Publications`` - perhaps in a later mini-release we can address changes to the other data tables on the target profile page.

**Comment by deniseOme** [comment]
Thank you both @EPetsalaki and @andrewhercules for the clarification. Perhaps we could consider in alternative for tables where the `X publication(s)` main design does not apply?

In addition to the new target safety, I have just spotted another flavour of showing Publication data: target profile page - cancer hallmarks - table view. PMIDs instead of first author name + et al.
