### ISSUE TITLE
filtering option: missense variant lists twice

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#569]
This is observed both in production and 19.04 QA:

https://qa.targetvalidation.org/evidence/ENSG00000141736/EFO_0001075?view=sec:somatic_mutation

https://www.targetvalidation.org/evidence/ENSG00000141736/EFO_0001075?view=sec:somatic_mutation

"Missense variant" under Mutation type comes up twice.

![Screen Shot 2019-04-16 at 14 31 58](https://user-images.githubusercontent.com/6472381/56213735-836d2b80-6054-11e9-9a8d-6a914189ce74.png)

This should come up once only.

**Comment by LucaFumis** [comment]
Thank you @deniseOme - well spotted!
Had a quick look and it appears that this behaviour is due to an empty trailing space in the data.
`evidence.known_mutations.preferred_name` returns "missense_variant" for some records and as "missense_variant " (with a space) for others.
Trimming spaces should fix it.

**Comment by deniseOme** [comment]
Fab @LucaFumis! 

Thanks for investigating this. 

I think it's harder to spot the empty trailing space than the duplicated "missense variants" in the UI. So well spotted  :) !
