### ISSUE TITLE
Duplicated releases?

### ISSUE THREAD

**Issue by pieterlukasse** [opentargets/platform#577]
All minor releases for 19.04 are pointing to the same commit: 

https://github.com/opentargets/data_pipeline/releases

**Comment by pieterlukasse** [comment]
notify @cmalangone, @afaulconbridge

**Comment by afaulconbridge** [comment]
Yes, this is intentional. We use multiple tags to make sure the same tag can be used consistently over multiple components and over multiple data releases. In this case, we've had a few internal issues with some of the data which needed some additional pipeline runs with the same code but different data files - hence the duplicate tags
