### ISSUE TITLE
a non-coding gene (MALAT1) with missense and frameshift variants?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#580]
ENSG00000251562 is a non-coding gene, therefore it does not give rise to a protein.

However we list some somatic mutations as being either frameshift of missense (consequence terms that involve a change of the amino acid in a protein or change of the open reading frame of a protein).

https://www.targetvalidation.org/evidence/ENSG00000251562/EFO_0000365?view=sec:somatic_mutation

Is this really correct? This was picked up at the STORM Therapeutics workshop this afternoon.

A quick glance at the curated paper does not show this gene (aka MALAT1): https://europepmc.org/backend/ptpmcrender.fcgi?accid=PMC6428276&blobtype=pdf

Looking at COSMIC, they do have the variants indeed as missense:
https://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=MALAT1&mut=substitution_missense#variants

but all their external references point to a non-coding RNA (lincRNA):
https://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=MALAT1&mut=substitution_missense#links

There used to be a protein sequence for this (Q9UHZ2), now obsolete. Haven't the variant annotations been updated since?

COSMIC has a transcript named ENST00000332541 but this no longer exists in Ensembl.

My guess is that in the past the annotation of this gene was protein coding (where the variant annotations from COSMIC come from) but this is no longer the case.

Even in the previous assembly of the human genome, MALAT1 was annotated as non-coding RNA:
http://grch37.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000251562;r=11:65265233-65273940

**Comment by afaulconbridge** [comment]
Ensembl lists these variants as “non coding transcript exon variant” (see http://www.ensembl.org/Homo_sapiens/Location/Variant/Table?r=11:65497688-65506516;g=ENSG00000251562;db=core and then filter by consequences to get counts).

**Comment by AsierGonzalez** [comment]
This doesn't look good. The latest COSMIC file we have is from March this year (cosmic-2019-03-22.json.gz) but you are right, this gene is not protein coding and it hasn't been for a long time:

-  Uniprot deleted Q9UHZ2 in Jan 2017: https://www.uniprot.org/uniprot/Q9UHZ2

- According to Ensembl ENST00000332541 has not been protein coding since release 49 (GRCh36, ~2009??): http://www.ensembl.org/Homo_sapiens/Transcript/Idhistory?t=ENST00000332541

Unless @iandunham or @MichaelaEBI know more about what may be happening here, we will need to ask COSMIC about this.

**Comment by AsierGonzalez** [comment]
I have checked how widespread this issue is in the 19.04 data and it seems that it only affects 3 non-noding genes (out of 723 in COSMIC) and 20 evidence strings (out of 59k):

| Gene ID  | Biotype | Mutation Types in COSMIC | Link |
| ------------- | ------------- | ------------- | ------------- |
| ENSG00000197880  | lincRNA  | Missense | http://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=MDS2 |
| ENSG00000251562  | lincRNA  | Missense, frameshift | http://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=MALAT1 |
| ENSG00000280757  | unprocessed_pseudogene  | Missense, framshift, stop gained, translational product function, gene fusion  |  http://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=DUX4L1 |

**Comment by ElaineMcA** [comment]
@MichaelaEBI  to include in emails on files to COSMIC so can address this and introduce @AsierGonzalez  to team as Data SME.

**Comment by AsierGonzalez** [comment]
This issues was discussed with Zbyslaw from COSMIC who said that it's related to non-coding genes involved in gene fusions and that the old COSMIC schema didn't deal well with those cases. The new COSMIC data schema should be able to deal with it correctly and treat these mutations as non-coding. COSMIC v90 was released the 5th Spetember 2019 and those links don't work any more but they still appear in the evidence strings with the same mutation types.

**Comment by AsierGonzalez** [comment]
The evidence for these three non-coding RNAs have disappeared in the COSMIC evidence file submitted for 19.11. Changing status to fixed and awaiting for COSMIC to confirm that the issue has been fixed.
