### ISSUE TITLE
clinical_significance enum in JSON schema is restrictive

### ISSUE THREAD

**Issue by Docproc** [opentargets/platform#588]
`clinical_significance` is defined in 2 places in the JSON schema, and the enumeration of values is a subset of the [ACMG guidelines](https://www.ncbi.nlm.nih.gov/clinvar/docs/clinsig/). Some of the values (marked in _italics_ below) are not present. 

_Benign_
_Likely benign_
_Uncertain significance_
Likely pathogenic
Pathogenic
drug response
association 
risk factor
protective
Affects
_conflicting data from submitters_
_other_
_not provided_

As far as I can see the value in the index is presented as-is by the web app, so extending the schema shouldn't have knock-on effects:

In `webapp/app/src/components/rare-disease-table/rare-disease-table-directive.js`:

```javascript
// Clinical consequences
var clin = 'N/A';
if (item.evidence.variant2disease && item.evidence.variant2disease.clinical_significance) {
    clin = item.evidence.variant2disease.clinical_significance;
}
row.push(clin);
```

**Comment by deniseOme** [comment]
In the past, we only had "pathogenic" and the list got extended in July 2017 (release blog "[other updates](http://blog.opentargets.org/2017/07/27/the-latest-release-of-open-targets-platform-is-out/#otherupdates)".  

I think it was a deliberate decision to leave _benign etc_ out as we would not be interested in those types of variants. Worth revisiting this @d0choa @iandunham ?

**Comment by iandunham** [comment]
Yes, the idea is that the ones in italics don't contribute anything in terms of saying what the significance of the effect of the mutation on the disease is. Since we effectively treat all evidence as positive in indicating an association between a variant and disease we need to exclude these, otherwise they will act as evidence and contribute to the association. If you want these in order to display that they exist, but not add to the association score you will also need to modify the scoring so that they contribute either 0 or a negative value based on the clinical_significance. Our approach has been to avoid this complication, but one could be more rigorous and calculate significance.

**Comment by Docproc** [comment]
Thank you @iandunham for the additional context. I'll talk to the users about whether the work involved is justified given their other priorities.
