### ISSUE TITLE
Duplicated Evidence from Data Feed

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#60]
@ckongEbi commented on [Mon Jun 11 2018](https://github.com/opentargets/data_release/issues/85)

By checking the combination of `target_id, disease_id & json_doc_hashdig` from the validated JSON of all datasources as of `18.06`, couple of those are still having duplicated evidence.

 EVA - 106 (Despite adding rs_id to `unique_association_field`, probably due to >1 clinvar traits mapping to same EFO terms, needs following up with EVA & @gkos-bio)

GWAS - 784 (Olga has flag this to GWAS curator for checking)

ATLAS - 40459 (Suhaib planned to add probe_id to `unique_association_field` aim this will solve the issue)

EUROPEPMC - 519807 (example sent to them but no feedback yet)

PHEWAS - 117 (check with Eliseo) 

---

@ElaineMcA commented on [Tue Jul 17 2018](https://github.com/opentargets/data_release/issues/85#issuecomment-405525907)

EVA - 106 (Despite adding rs_id to unique_association_field, probably due to >1 clinvar traits mapping to same EFO terms, needs following up with EVA & @gkos-bio)

- Update 17JUL2018: Partially fixed in 18.08.  Ontology mapping required @afaulconbridge and Gautier.

GWAS - 784 (Olga has flag this to GWAS curator for checking)

- Update 17JUL2018- Under investigation.

ATLAS - 40459 (Suhaib planned to add probe_id to unique_association_field aim this will solve the issue)

- Update 17JUL2018: Fixed in 18.08.

EUROPEPMC - 519807 (example sent to them but no feedback yet)

- Update 17JUL2018: Need to follow-up.

PHEWAS - 117 (check with Eliseo)

- Update 17JUL2018: Need to follow-up.

---

@ckongEbi commented on [Tue Jul 17 2018](https://github.com/opentargets/data_release/issues/85#issuecomment-405590742)

Look for rows for counts > 1, which will be duplicates

EVA: [1806_dup_eva_2.txt](https://github.com/opentargets/data_release/files/2201861/1806_dup_eva_2.txt)

GWAS: [1806_dup_gwas_2.txt](https://github.com/opentargets/data_release/files/2201862/1806_dup_gwas_2.txt)

PHEWAS: [18.06_phewas_2.txt](https://github.com/opentargets/data_release/files/2201882/18.06_phewas_2.txt)

EPMC & ATLAS: 
https://drive.google.com/open?id=1levWwb8FgsmGm2bPsbS8ZZGOK1OAPSFv

**Comment by MichaelaEBI** [comment]
**Update from work on the 18.08 Release:** 
For 18.08 the number of evidence strings throughout the pipeline is tracked [here](https://docs.google.com/spreadsheets/d/1qhIm8D5nCSaV6fQgybsYGb6oBb3EZXkq6bHmmfaCecw/edit#gid=0).

Following an analysis of duplicated evidence strings, the following to do's have arisen
- [ ] Check for duplicated evidence strings in the next **Expression Atlas** data file (need to use jq because the order of fields in the evidence string is random)
- [ ] **ChEMBL**: 3 evidence strings are lost between the input file and 18.08_validated-data-chembl - investigate
- [ ] Investigate 226 duplicated evidence strings in **GWAS** input file
- [ ] Check 1 duplicated line in **EVA** input file
- [ ] Check 217 duplicated lines in **IntOgen** input file
- [ ] Check 13 duplicated line in **gene2phenotype** input file
- [ ] Check 1 duplicated line in **EVA** input file
- [ ] **PheWAS**: either check 4,741 duplicated lines in old input file or check processing of evidence strings for new PheWAS file (2/3 of evidence strings get filtered at some point)
- [ ] Check **genomics_england** evidence parser to remove 16,228 duplicated evidence strings
- [ ] **PROGENy**: check 14 duplicated evidence strings and 1 additional line in input file
- [ ] Investigate **EuropePMC** input file for duplicates

**Comment by MichaelaEBI** [comment]
Additional to do: Miguel refactored the validation step. Look at duplicate evidence strings in the files with valid evidence strings [here](https://console.cloud.google.com/storage/browser/ot-snapshots/files/18.10?project=open-targets-eu-dev).

**Comment by d0choa** [comment]
Outdated
