### ISSUE TITLE
Load additional evidences to existing index

### ISSUE THREAD

**Issue by fedde-s** [opentargets/platform#632]
Up to release 19.02, it was possible to configure the `--val` step of the data loading pipeline to add a new evidence source to an index that already contained evidences. In 19.04 (since commit [848dd54](https://github.com/opentargets/data_pipeline/commit/848dd54114daf0eae09e80a8ac1dd87eda907d23) of PR [#455](https://github.com/opentargets/data_pipeline/pull/455), I believe), the step will instead always result in an index that contains _only_ the data listed in the data configuration file for this run.

Adding internal data on top of the more stable public data release snapshots is a use-case we encounter, so I believe that the data loading pipeline should allow that.

**Comment by fedde-s** [comment]
Two ideas on how this could look to the user of the data loading pipeline:
- a `--keep-index` flag, or
- a data.yml file that explicitly specifies adding data to an existing base.

The latter may be more consistent with the expectations raised by the file format, whereas the former facilitates the workflow of iterating on a set of custom data in isolation before integrating it into a more complete platform instance.

**Comment by pieterlukasse** [comment]
To extend the use case a bit: even if we would _not_ be starting from the snapshot but would be loading the public data via the pipeline directly, we would still like to have the option to follow the process below:
1. load only the public data
2. verify public data is loaded correctly by comparing to public portal
3. proceed with loading custom internal evidence data on top of public data

**Comment by afaulconbridge** [comment]
This definitely sounds like the sort of thing we could support without too much extra work. I think this belongs on the "operations" rather than "data" configuration side (since it changes the order things are done in, but not the final result) and @fedde-s 's suggestion of a flag sounds like the best way to do it.

I think it might a `--drop-index` option that defaults to `True` might be best, since it avoids any potential linguistic confusion about double negatives.

**Comment by pieterlukasse** [comment]
@afaulconbridge I made a PR and linked it to this issue (https://github.com/opentargets/data_pipeline/pull/517). I have tested a version of this in 19.04.5 but not yet in `master` (to where the PR is made). Please let me know what you think of this PR. I will wait for your feedback before testing it on `master` (I expect testing could take some time since there seems to be quite some changes between 19.04 and 19.06). Thanks!

**Comment by fedde-s** [comment]
For completeness: I rebased the pull request that [Pieter](https://github.com/opentargets/platform/issues/632#issuecomment-503573635) mentioned to resolve the merge conflicts after several major changes in the `master` branch.

**Comment by fedde-s** [comment]
The patch to fix this has been released in 19.09, this is probably resolved. I haven't had the chance to test it yet, though.
