### ISSUE TITLE
ChEMBL: Target information for BIIB054 not available for drug summary page

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/platform#656]
There are three ChEMBL evidence strings that link SNCA (alpha synuclein) to AD via the antibody BIIB054: https://www.targetvalidation.org/evidence/ENSG00000145335/EFO_0002508?view=sec:known_drug

On the Open Targets Drug Summary page for BIIB054, no target information is shown. The target information on that page is retrieved from ChEMBL. The [ChEMBL Compound Report Card for BIIB054](https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL3833330/) does not show any target information. However, the [ChEMBL SNCA Target Report Card](https://www.ebi.ac.uk/chembl/target_report_card/CHEMBL6152/) shows BIIB054 in the drug section.

It looks like target information is missing in ChEMBL for other antibodies as well:
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL3990025/
https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2109500/

**Comment by MichaelaEBI** [comment]
The ChEMBL team is aware of the missing targets for antibodies in their frontend and this will be corrected soon. However, further investigations with @andrewhercules revealed that the missing mechanism info is actually an Open Targets frontend issue since we do have mechanism info for BIIB054 in the drug index and for the last example above we [show mechanism information in the Open Targets](https://www.targetvalidation.org/summary?drug=CHEMBL2109500) Platform.

**Comment by andrewhercules** [comment]
I believe the issue is due to ``mec.references.map`` on line 82 as it expects a ``references`` array - see below for a screenshot of the console log error.

![Screenshot 2019-07-05 at 15 59 24](https://user-images.githubusercontent.com/7490258/60730798-e1b3f700-9f3d-11e9-90d7-5dfccfd649e4.png)

![Screenshot 2019-07-05 at 15 55 39](https://user-images.githubusercontent.com/7490258/60730640-86820480-9f3d-11e9-8f1a-442bb17fb65c.png)

In this case, the API does not return a ``references`` array - see http://api.opentargets.io/v3/platform/private/drug/CHEMBL3833330 for the response.

@d0choa, given that we may have a similar issue with other drugs, I suggest that we include this fix in our next mini-release.

@Luca, is it possible to wrap the  ``mec.references.map`` line in a check to ensure that the ``references`` array exists in the API response?

**Comment by LucaFumis** [comment]
I missed this - could have included it in 19.09.
Something like this would work:
```
(mec.references || []).map(function (ref) {
```
