### ISSUE TITLE
PDBe mappings on the target profile page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#700]
Following one [tweet](https://twitter.com/targetvalidate/status/1156980173595656192) of ours, PDBe has contacted us to tell that we’ve mapped ENSG00000254647 (P01308) (insulin) to 6b3q, which in fact is human insulin degrading enzyme in complex with insulin.

Looking at the response from the API call (http://platform-api.opentargets.io/v3/platform/private/target/ENSG00000254647), we can see > 200 PDBe structures mapped to ENSG00000254647 including several other 'human insulin degrading enzyme in complex with insulin' such as `6b70`.

To investigate:

* rationale behind picking `6b3q` amongst all the others including the right one

* the list returned in the API call is much longer than UniProt's. 

* some of the fewer PDBe entries returned by UniProt are also wrong

* is this a widespread issue?

**Comment by d0choa** [comment]
From my point of view, the fact that you have other structures in the same pdb structure doesn't make it incorrect, only potentially misleading. I wouldn't consider it a bug.

In any case, we know we have several potential issues with the uniprot->pdb mappings. For example, uniprot is no longer using the pdb files to display the structures as they are sometimes not available. We are hoping the new ProtVista will sort these issues for us, as it provides a combined sequence-structure viewer. We will align with uniprot and we can expect most of the problems gone.

**Comment by deniseOme** [comment]
Ensembl points to the right PDBe structure by mapping via UniProt to 2KQP (note there is no distinction between pro-insulin and the mature, post-translationally cleaved form).

https://www.ensembl.org/Homo_sapiens/Transcript/PDB?db=core;g=ENSG00000254647;r=11:2159779-2161341;t=ENST00000397262 

There may be an Ensembl REST API endpoint that retrieves this although PDBe model viewer in Ensembl is a new-ish feature (Ensembl 95) and may not have an endpoint yet to retrieve the mapping.

**Comment by andrewhercules** [comment]
@deniseOme and @d0choa, the reason why `6b3q` is selected is that it what is returned by the PDBe API when we call their `mappings/best_structure` endpoint.

In the case of [ENSG00000254647](https://www.targetvalidation.org/target/ENSG00000254647), when a user clicks the `Protein structure` tab, we submit a call to:

http://www.ebi.ac.uk/pdbe/api/mappings/best_structures/P01308

We use the `P01308` UniProt accession ID that is returned in [the ENSG00000254647 gene index object](http://platform-api.opentargets.io/v3/platform/private/target/ENSG00000254647). The `ENSG00000254647` to `P01308` is also used by UniProt - see the `Organism-specific database` table on [the P01308 UniProt profile page](https://www.uniprot.org/uniprot/P01308#pathology_and_biotech).

In terms of whether it is a widespread issue, it is difficult to determine because we are relying on PDBe's API to tell us the best structure for a given UniProt ID.

**Comment by iandunham** [comment]
I think get back to PDBe and say that we were told to use the best structures call to get the best structure. 6b3q is the object that pops of the array for this call, it would be better for us if they explained how to ensure we get structures of just the target of interest with the highest coverage.

Looking at that file, an explanation for this is that insulin is a short protein with several structures that have 100% coverage of the protein. These are listed in the first array of the JSON that is returned. 6b3q happens to be the first. However the problem to my eyes is that they include in that list structures that are complexes or co-crystals. Since insulin is short these can easily have 100% coverage of the insulin protein. Hence we get that one. It's not obvious from the file, how one can decide which of the objects in the array is a 'pure' structure of only insulin. We should as them to either suggest how to do this, or maybe think about whether co-crystals should be included.

**Comment by deniseOme** [comment]
Thanks @d0choa @andrewhercules @iandunham! Got back to PDBe and this is their reply:

"The 'best' structures is ordered by maximum coverage of the sequence - which in this case, wrongly contains the signal peptide and also has much of the protein unobserved in the structure. I will pass this on and we can look to improve the call."

I will find out how they can suggest which object in the array = "pure" (or best) structure to represent.

What interests me is that Ensembl does have the right PDBe entry.

**Comment by andrewhercules** [comment]
As of today, [the Protein Structure tab on the INS target profile page](https://www.targetvalidation.org/target/ENSG00000254647) still shows `6b3q` - it is the first ID returned from PDBe's `/best_structures` endpoint.

In the rewrite, we are using the UniProt protein viewer which makes it easy to browse the different structures based on their coverage score. See below for an example for [INS](https://platform-app.netlify.com/target/ENSG00000254647).

![Screenshot 2019-09-30 at 15 40 51](https://user-images.githubusercontent.com/7490258/65889518-4c3bce00-e399-11e9-84ee-37daaab21d44.png)

Because this issue is due to a third-party API, I am closing for now, but it can be re-opened if PDBe change their API to more easily communicate the best structure ID to use.
