### ISSUE TITLE
missing clinical trials

### ISSUE THREAD

**Issue by deniseOme** [opentargets/platform#721]
User reports missing drug-clinical trial data for Fragile X Syndrome (FXS).

Only 33 of the 74 clinical trials associated with FXS currently represented in the Platform leading to the omission of at least 34 drugs/treatments and further targets associated with them. Here they are:

NCT02126995
NCT02747394
NCT02465931
NCT01053156
NCT03697161
NCT01894958
NCT01329770
NCT00858689
NCT00637221
NCT03836300
NCT03510156
NCT00718341
NCT03569631
NCT00823368
NCT02616796
NCT00362843
NCT00054730
NCT01855971
NCT01204151
NCT02942498
NCT00892580
NCT01616589
NCT01711606
NCT03109756
NCT03862950
NCT03479476
NCT00334971
NCT03624556
NCT00768820
NCT02719951
NCT03655223
NCT01364818
NCT01187524
NCT02769949
NCT02936531
NCT02603926
NCT00870974
NCT02532244
NCT00879515
NCT02197104
NCT00584948
NCT03087526
NCT0256735

@iandunham has had a quick glance and noticed the following:

* some of these trials are on antibiotics or targeting non-human targets e.g. citocoline, Minocycline
* some trials do not have a direct target e.g. dietary supplements
* some of these trials do not involve a drug e.g. NCT03510156

We focus on human target selection and integrate drugs with a known mechanism of action, so the above does not meet these criteria.

@iandunham has seem examples from the above list where the "trials seem to be annotated to a different EFO term". 

TODO: look with ChEMBL if there is a good reason for missing these
_(note: are other diseases missing trials as well?)_
User reports: "This missing data error can be systematically identified to other diseases by analyzing the NCTs captured in the Open Targets versus those on the CTgov website.".

**Comment by deniseOme** [comment]
These are the drugs from the NCTs above.

[18F]FPEB
AF056
AFQ056
Allopregnanolone
BPN14770
citocoline
CX516 (Ampalex)
Memantine
MG01CI extended-release tablet
Minocycline
minocycline hydrochloride
NNZ-2566
NPL-2009
OV101
OV101 (gaboxadol)
RO4917523
STX209
sugar pill
ZYN002 - CBD Transdermal Gel
Combination: Dietary Supplement: Ascorbic Acid (Vitamin C) and Alpha-tocopherol (Vitamin E)
Combination: methylphenidate, fluoxetin, risperidone
Combination: Vitamin C 10mg/Kg Vitamin E 10 mg/Kg\|Placebo
Combination: Minocycline, then Minocycline/Lovastatin\|Lovastatin, then Minocycline/Lovastatin
Dietary Supplement: EGCG

**Comment by MichaelaEBI** [comment]
There must be a good reason that these clinical trials have not been curated by ChEMBL because they are working their way through the clinicaltrials.gov website. All of @iandunham's reasons are valid explanation for why these trials are not in Open Targets. It might be a good idea to keep a list of trials from CTgov that are not in ChEMBL/Open Targets together with the reason why they are not suitable for curation. I will get in touch with ChEMBL.

**Comment by MichaelaEBI** [comment]
Paula from ChEMBL has looked into this:

"Of the 43 trials in the list, 28 are studies that we exclude for different reasons: observational studies (no intervention), behavioural, diagnostic, or any trial that doesn’t have a phase assigned (’Not applicable’).

The other 15 trials are missing due to the drug or the mechanism of action not being in ChEMBL, or due to mapping issues (which I’ll try to correct for next release)."

**Comment by MichaelaEBI** [comment]
I will close this ticket since all the info currently available about these trials is given above and ChEMBL will re-curate their data, so some changes will come through in future evidence files from ChEMBL.
