### ISSUE TITLE
ES 7 Docker image failed due request canceled while waiting for connection.

### ISSUE THREAD

**Issue by cmalangone** [opentargets/platform#736]
The startup script runs on gcp and it fails to download the ES docker image.
docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 -e discovery.type=single-node -e bootstrap.memory_lock=true -e 'repositories.url.allowed_urls=https://storage.googleapis.com/*,https://*.amazonaws.com/*' -e thread_pool.write.queue_size=1000 -e cluster.name=platform-190919-150231-19-09-5test-es -e network.host=0.0.0.0 -e search.max_open_scroll_context=5000 -e 'ES_JAVA_OPTS=-Xms6g -Xmx6g' -v esdata:/usr/share/elasticsearch/data -v /var/elasticsearch/cred:/usr/share/elasticsearch/cred --restart unless-stopped docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0

Error
...es startup-script[443]: INFO startup-script: Unable to find image 'docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0' locally
...es startup-script[443]: INFO startup-script: docker: Error response from daemon: Get https://docker.elastic.co/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).

This is closely related with the ticket 733 (https://github.com/opentargets/platform/issues/733)

**Comment by afaulconbridge** [comment]
This might be because the container is created as part of the machine startup script, and it might trigger before GCP has finished setting up all the related networking for the VM.

Can you put a `sleep 60` at the start of the elasticsearch startup and see if it happens again when that is present? I don't think its worth running specific tests for this issue, as its quite rare and unpredictable anyway, but if we add a sleep to your general usage we can see if goes away with it and then commit it in that scenario.

**Comment by andrewhercules** [comment]
Ticket moved to 20.02 release

**Comment by d0choa** [comment]
Done
