### ISSUE TITLE
Include adverse events data in the /drug/ID endpoint response

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#739]
Placeholder - details TBC

**Comment by d0choa** [comment]
The adverse events data has been recalculated using FAERS data provided by OpenFDA. Previously, we were retrieving the top 20 most frequent adverse events directly from the OpenFDA API. However, these events are not necessarily the most informative ones for a particular drug as they might be highly influenced by how frequent they are independently of the drug in question. Therefore, we followed a similar approach to the one implemented in this Shiny [app](http://openfda.shinyapps.io/LRTest/) and in this [paper](https://elifesciences.org/articles/25818) by Novartis.

In order to calculate the log-likelihood ratios, all reports (~10M as today) need to be downloaded every time. The main reason being the json is continuously curated to remove duplicates. We then apply some filters to the reports: only reports by healthcare professionals, removing unspecific events or ignoring reports where there is a deathly outcome, as well as we blacklist some [adverse events](https://github.com/opentargets/platform-etl-openfda-faers/blob/master/blacklisted_events.txt). (more details to come). Finally, the counting and the llr is calculated. Currently, there is a separate script that calculates the critical values for every drug and therefore the significant events.

The output file has been revised by @EPetsalaki, @smnorthen, @mkarmona and @d0choa to make sure the results are appropiate.  

- Analysis [repo](https://github.com/opentargets/platform-etl-openfda-faers) based on FAERS data
- FE specs available in #741 (Angular) and #670 (Rewrite)

Further details will be provided by @EPetsalaki

**Comment by EPetsalaki** [comment]
**Summary for the OT adverse events pipeline:**

1. openFDA FAERS data [download](https://open.fda.gov/apis/drug/event/download/) (~ 900 files)
 
2. Pre-processing of this data using [platformDataProcessFDA.sc](https://github.com/opentargets/platform-etl-openfda-faers/blob/master/platformDataProcessFDA.sc) scala script:
  - Filtering:
    - Only reports submitted by health professionals (*primarysource.qualification* in (1,2,3)).
    - Exclude reports that resulted in death (no entries with *seriousnessdeath*=1).  
    - Only drugs that were considered by the reporter to be the cause of the event (*drugcharacterization*=1).
    - Remove events (but not the whole report which might have multiple events) that are [blacklisted ](https://github.com/opentargets/platform-etl-openfda-faers/blob/master/blacklisted_events.txt)(blacklist curated manually to exclude events that are uninformative for our purposes).
  - Match FDA drug names to Open Targets drug names & then map all these back to their ChEMBL id:
    - Open Targets drug index fields:  *‘chembl_id’, ‘synonyms’, ‘pref_name’, ‘trade_names’*.
    - openFDA adverse event data fields: *‘drug.medicinalproduct’, ‘drug.openfda.generic_name’, ‘drug.openfda.brand_name’, ‘drug.openfda.substance_name’*.
  - Generate table where each row is a unique drug-event pair and count the number of report IDs for each pair, the total number of reports, the total number of reports per drug and the total number of reports per event. Using these calculate the fields required for estimating the significance of each event occuring for each drug, e.g. log-likelihood ratio, (llr) (based on [FDA LRT method](https://openfda.shinyapps.io/LRTest/_w_c5c2d04d/lrtmethod.pdf)).
3. Calculate significance of each event for all drugs based on the FDA LRT method (Monte Carlo simulation) using the [openFDA_MonteCarlo_drugs.R](https://github.com/opentargets/platform-etl-openfda-faers/blob/master/R/openFDA_MonteCarlo_drugs.R) script.

**Comment by afaulconbridge** [comment]
To proceed, I need the data file and an explanation of it (ideally two hours face-to-face with a domain expert, and after having had the data for a few days to pre-analyse). Then I can produce a description of the JSON to be output by the API which I think would be suitable for the visualisation described in #741 

Since @EPetsalaki has left, I am reassigning this ticket to @d0choa to provide this information to me.

**Comment by afaulconbridge** [comment]
The data file is in a bucket on `open-targets` `otar001-core/AdverseEvents/annotation` with date in DD-MM-YYYY format. Source files to regenerate this should go in `otar001-core/AdverseEvents/data_files` for future reproducibility.

**Comment by afaulconbridge** [comment]
@d0choa do you know what the plan is for "child" drugs? Can they have adverse events separately from the parent? If so, should they be included in the drug index and how?

**Comment by afaulconbridge** [comment]
After discussion, we realised its a bit circular. Adverse events is generated using names from the OT Drug index, which flattens child drugs into their parent. So in theory, there should be no adverse events identified for child drugs. We might need this extra granularity in future, but for now this is acceptable.

**Comment by afaulconbridge** [comment]
First version done and committed to branch `af-739-adverse-events`. Need to run pipeline to test properly.

**Comment by afaulconbridge** [comment]
Snippet of expected response for @LucaFumis:
```
          "adverse_events" : {
            "critval" : 8.08981480102966,
            "significant" : [
              {
                "event" : "diabetes mellitus inadequate control",
                "count" : 13,
                "llr" : 26.6784226390737
              }
            ]
          }
```

**Comment by andrewhercules** [comment]
Format looks great @afaulconbridge! :)

**Comment by afaulconbridge** [comment]
Done and deployed to platform-api-qc.opentargets.io awaiting front end integration

**Comment by d0choa** [comment]
The current qa only lists one adverse event per drug instead of the full list. Any idea why this might be happening?

**Comment by afaulconbridge** [comment]
Nope, I'll reopen this and take a look next week. Thanks for the feedback.

**Comment by afaulconbridge** [comment]
Should be fixed in PR https://github.com/opentargets/data_pipeline/pull/551

**Comment by andrewhercules** [comment]
Ticket closed as work has been completed. The `/private/drug` endpoint now returns adverse event details - see below for an example: 

![Screenshot 2019-11-29 at 14 59 21](https://user-images.githubusercontent.com/7490258/69876980-d8467500-12b8-11ea-932f-a913e932f4d0.png)
