### ISSUE TITLE
Cancer hallmarks role in cancer contains duplicates

### ISSUE THREAD

**Issue by peatroot** [opentargets/platform#751]
See the response for eg. [AKT1](https://platform-api.opentargets.io/v3/platform/private/target/ENSG00000142208).

![image](https://user-images.githubusercontent.com/7376272/65959427-dba0ba00-e449-11e9-87bf-ca3c4b98efbf.png)

**Comment by andrewhercules** [comment]
Ticket closed as this is data provider issue for COSMIC.

The COSMIC profile page for AKT1 has both PMIDs listed due to their curation - see below for a screenshot:

![Screenshot 2020-04-29 at 15 55 12](https://user-images.githubusercontent.com/7490258/80611005-f3690c80-8a31-11ea-89c3-19898e42330b.png)
