### ISSUE TITLE
Consolidate the initials in the bubbles

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#761]
Until a better options comes out, we are defaulting to the bubbles view for the cards.
We need to curate the initials, to make sure they are the best options and there are no clashes between pages.

**Comment by LucaFumis** [comment]
It seems that the avatar (bubble) accommodates comfortably max 2 chars/letters.
We can add the option to specify such initials, or otherwise use initial letters of each word.

The "automatic" option (i.e. pick initials of each word) work for most sections.
Problems arise with long named sections, for which we should manually specify the short version:
Variation and Genomic Context
Mechanisms of Action
Pathways and Systems Biology

**Comment by LucaFumis** [comment]
We could map as:
Variation and Genomic Context => **V**
Mechanisms of Action => **MA**
Pathways and Systems Biology => **P** or **Pw** to differentiate from _Phenotypes_?
Phenotypes => **P** or **Ph** or **Pt** to differentiate from _Pathways_ (see above)?
