### ISSUE TITLE
HPA parser bug (in data_pipeline)

### ISSUE THREAD

**Issue by eric-czech** [opentargets/platform#765]
The URL for control tissue in the HPA parser (i.e. ```normal_tissue_url```) is being loaded as an uncompressed URLSource in [HPA.py#L374](https://github.com/opentargets/data_pipeline/blob/4b86e20390a17a9ca0392eabf46d0b696296f135/mrtarget/modules/HPA.py#L374) despite being defined as a zipped file in the data configs -- i.e. [mrtarget.data.19.09.yml](https://storage.googleapis.com/open-targets-data-releases/19.09/input/mrtarget.data.19.09.yml) has the line:

```hpa-normal-tissue: https://storage.googleapis.com/open-targets-data-releases/19.09/input/annotation-files/normal_tissue-2019-08-22.tsv.zip```.

This then results in an error like ```utf-8 codec can't decode byte ...``` when running mrtarget because the compressed stream is not decodable as text.

**Comment by afaulconbridge** [comment]
Hi Eric, thanks for contacting us. The issue you described is intentional for python 3 compatibility in upcoming 19.11 release. For using 19.09 data please use 19.09 tagged code release, not master. Alternatively, make a uncompressed copy available and use an updated data configuration that references it.

In the longer term, it would be useful to rewrite the hpa step as it is the only one that uses a separate ETL library, and at that point we should make sure it accepts both compressed and uncompressed input (like the other inputs already do).

**Comment by eric-czech** [comment]
Makes sense, thanks for the info.
