### ISSUE TITLE
Provide Project Score ID in GraphQL API

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#807]
In the 19.11 release, @LucaFumis updated the logic that constructs a link to the Project Score website based on a bug (#782) reported by @PruMM.

I have contacted the Project Score team and they have provided us with a link to a file that maps Ensembl IDs to the Project Score IDs, which we use to construct links on the target profile page.

https://cog.sanger.ac.uk/cmp/download/gene_identifiers_latest.csv.gz

According to the team, this is a permanent link that will always point to the latest version of the mapping file.

@AsierGonzalez and @cmalangone, can you please review the file and update the pipeline and platform-input-support scripts to process this CSV file and add the Project Score IDs to the gene index object? 

Once the Project Score ID is available in the gene index object, we will update the rewrite GraphQL and/or React app codebase to use the ID from the gene index, rather than the current implementation that uses the Project Score /search endpoint.

**Comment by AsierGonzalez** [comment]
Do we know how we should use this file? I see that Project Score ID (`gene_id`) and Ensembl id (`ensembl_gene_id`) are two of the columns of the file but I have found two issues after a quick look:

1. 5,026 out of the 42,476 rows have an empty `ensembl_gene_id`
2. Not all of the Project Score ids have a valid page in their website, e.g. [SIDG23930-PARP1](https://score.depmap.sanger.ac.uk/gene/SIDG23930). This issue is particularly concerning and we would need that they either only include in the file the genes with informative Project Score pages or that they add another column that contains such information.

**Comment by d0choa** [comment]
According to @AsierGonzalez comment, we will need an extra column referencing whether they have data in ProjectScore or not. PARP1 is a good example of an available mapping with no page available.

**Comment by d0choa** [comment]
A solution doesn't look straight-forward at the moment. We'll wait until Project Score is updated with the Broad screening to get the relevant file.

**Comment by andrewhercules** [comment]
Pushed to next sprint to allow for project team to provide update on interim Project Score release plans

**Comment by d0choa** [comment]
A recent communication between @andrewhercules and Donny suggested that the best strategy would be to  

1. Download gene identifiers file: https://cog.sanger.ac.uk/cmp/download/gene_identifiers_latest.csv.gz

2. Download essentiality matrixes directory:
https://cog.sanger.ac.uk/cmp/download/essentiality_matrices.zip

3. Ingest the `project_score_id` (`gene_id` in gene identifiers file - step 1) in the gene index only when rows in EssentialityMatrices/04_binaryDepScores.tsv (step 2) have at least one "1"  (n=7,469)
