### ISSUE TITLE
Prevent empty disease string in json schema

### ISSUE THREAD

**Issue by AsierGonzalez** [opentargets/platform#860]
1503 evidence strings from the genetics portal are invalid because they lack the disease id:
```
"disease": {
    "reported_trait": "Keratinocyte cancer (MTAG)",
    "id": ""
  }
```
The source of this issue has been identified but raises the question of what the acceptable disease id would look like. In the JSON schema [the disease id is described as “a valid EFO full URI”](https://github.com/opentargets/json_schema/blob/1.6.4/opentargets.json#L113-L120) but it does not have a “URI” format or any other constraints that enforces it [as other strings do](https://github.com/opentargets/json_schema/blob/1.6.4/opentargets.json#L138-L142) so any string is considered valid. In the past a [regex used to specify the format of the accepted ids](https://github.com/opentargets/json_schema/blob/1.2.8/src/bioentity/disease.json#L13-L17). This could be reconsidered or a regex could be used to invalidate empty strings, e.g :
```
"disease": {
      "type": "object",
      "description": "Disease in the EFO ontology",
      "properties": {
            "id": {
                 "type": "string",
                 "description": "A valid EFO full IRI",
                 "pattern": "^[^\u0020]*$",
            }
         }
}

**Comment by d0choa** [comment]
Related to #858

**Comment by DSuveges** [comment]
This bug was introduced at the evidence generation: there are ~750 studies with no disease labels in the [genetics portal study table](gs://genetics-portal-data/v2d/200207/studies.parquet). This issue affects mostly UKBB studies, but there are studies from the GWAS Catalog as well. Luckily most of these studies don't have genome wide significant associations, so the missingness of the disease won't propagate to the evidence level. 

There are only two studies: `GCST008870`, `NEALE2_3761_raw` with 162 GWAS associations below p-val 5e-8 corresponding to the 1503 disease/trait evidences.

For the resolution, see  issue #858

**Comment by AsierGonzalez** [comment]
Still the question is whether the schema should be able to handle this issues. In my opinion it should, as it is simple to enforce in it and the issues would be identified earlier.

**Comment by d0choa** [comment]
I renamed the ticket for clarity

**Comment by AsierGonzalez** [comment]
The json schema has been updated not to accept empty disease ids (see https://github.com/opentargets/json_schema/pull/84)
