### ISSUE TITLE
Drug description based on available data

### ISSUE THREAD

**Issue by d0choa** [opentargets/platform#877]
Build drug description based different available fields based on the next specification from @andrewhercules:
https://docs.google.com/document/d/1BQaax1L769_pMD8RtccHb88dxAY4n8rhnNexoFiezZM/edit#

**Comment by mkarmona** [comment]
The code is dropping out some minimal descriptions.

**Comment by mkarmona** [comment]
Some examples

> CHEMBL471737 Small molecule drug with a maximum clinical trial phase of IV (across all indications) that was first approved in 2015 and is indicated for heart failure and congestive heart failure and has 13 investigational indications.
CHEMBL521851 Small molecule drug with a maximum clinical trial phase of II (across all indications) and has 5 investigational indications.
CHEMBL524 Small molecule drug with a maximum clinical trial phase of IV (across all indications) that was first approved in 1982 and has 3 investigational indications.
CHEMBL604608 Small molecule drug with a maximum clinical trial phase of IV (across all indications) and has 3 investigational indications.
CHEMBL8260 Small molecule drug with a maximum clinical trial phase of II and has 1 investigational indication.
CHEMBL850 Small molecule drug with a maximum clinical trial phase of IV that was first approved in 1996 and has 1 investigational indication. It was withdrawn in United States initially in 2001 due to Cardiotoxicity and Dermatological toxicity.
CHEMBL852 Small molecule drug with a maximum clinical trial phase of IV (across all indications) that was first approved in 1964 and is indicated for multiple myeloma and carcinoma and has 69 investigational indications. This drug has a black box warning from the FDA.
CHEMBL959 Small molecule drug with a maximum clinical trial phase of IV that was first approved in 1993.
CHEMBL1090090 Small molecule drug with a maximum clinical trial phase of II and has 1 investigational indication.
CHEMBL1200656 Small molecule drug with a maximum clinical trial phase of IV (across all indications) that was first approved in 1978 and is indicated for infection and has 5 investigational indications.

**Comment by mkarmona** [comment]
the word `initially` is restricted to having more than one country listed.
> HEMBL1909283 Small molecule drug with a maximum clinical trial phase of IV. It was withdrawn in United Kingdom  in 1975 due to Hepatotoxicity.
