### ISSUE TITLE
Investigate why ACE2 has drug profile page but no evidence strings

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/platform#890]
For [ACE2 ](https://www.targetvalidation.org/target/ENSG00000130234), the tractability assessment includes data that there is a Phase IV compound that targets the gene.

Upon review of the new tractability file, the Phase IV assessment comes from [Cilazapril - CHEMBL515606](https://www.targetvalidation.org/summary?drug=CHEMBL515606). According to ChEMBL, the drug has been indicated for cardiovascular disease based on an ATC record. 

@AsierGonzalez, can you please investigate this?

For reference, below you can find screenshots from the #dev Slack channel:

<img width="1393" alt="Screenshot 2020-03-17 at 15 53 10" src="https://user-images.githubusercontent.com/7490258/76874698-77db4380-6867-11ea-84ac-c451ad131bd4.png">
<img width="1394" alt="Screenshot 2020-03-17 at 15 53 29" src="https://user-images.githubusercontent.com/7490258/76874703-7ad63400-6867-11ea-9245-6e1f88f87a50.png">

**Comment by AsierGonzalez** [comment]
In the ChEMBL evidence file there are two evidence strings for this drug, one for [ACE - P12821](http://identifiers.org/uniprot/P12821) and one for [ACE2 - Q9BYF1](http://identifiers.org/uniprot/Q9BYF1). However. these two evidence strings end up in the invalid evidence index because the disease is invalid. Such disease is [cardiovascular disease - EFO_0000319](http://www.ebi.ac.uk/efo/EFO_0000319) which is removed from the slim EFO version.

We will see whether it is worth recovering that disease term of if the evidence strings annotated with it should be annotated with one of its children.

**Comment by AsierGonzalez** [comment]
@smnorthen says:

> This term was being looked at to be added back into EFO, either as going to both TAs (cardiac and vascular) or as a separate TA with cardiac and vascular being split into 2 groups underneath. Will speak to the spot team and report back.

**Comment by AsierGonzalez** [comment]
Closing issue. A new one will be created regarding the recovery of cardiovascular disease (EFO_0000319) in EFO if needed.
