### ISSUE TITLE
Ontology review: no phenotypes for motor neuron disease

### ISSUE THREAD

**Issue by ElaineMcA** [opentargets/platform#91]
@elipapa commented on [Fri Jan 12 2018](https://github.com/opentargets/roadmap/issues/116)

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_semantic/issues/6)

@elipapa commented on [Mon Feb 20 2017](https://github.com/opentargets/platform_issues_triage/issues/3)

@nikiforosk commented on [Mon Feb 13 2017](https://github.com/opentargets/features/issues/68)

While talking to Shila from Biogen last Friday, I noticed that we don't have any phenotypes for motor neuron disease:
https://www.targetvalidation.org/disease/EFO_0003782

@gkos-bio Is that correct? See e.g. http://www.mndcare.net.au/Overview/Motor-neurone-disease/Phenotypes.aspx 

cc/ @opentargets/efo_mapping 

---

@ElaineMcA commented on [Mon Aug 13 2018](https://github.com/opentargets/roadmap/issues/116#issuecomment-412485703)

Need to identify a new source of phenotypes in disease profile - HPO service no longer exists.

---

@deniseOme commented on [Mon Aug 13 2018](https://github.com/opentargets/roadmap/issues/116#issuecomment-412499569)

https://hpo.jax.org/app/

**Comment by ElaineMcA** [comment]
Check if this is something that EFO can look at post EFO3 release?

**Comment by d0choa** [comment]
After revising this old problem again, the next are the most relevant conclusions:

1. Phenotypes linked to diseases come from a list of old (2015!!) static files included quite a long time ago. Files are listed [here](https://sourceforge.net/p/efo/code/HEAD/tree/trunk/src/efoassociations/). It’s totally outdated and we are looking for a way to replace them.

2. In order to replace the phenotypes we should look to maintainable resources. For this reason, we are currently working with EFO to incorporate phenotype links as alternative axioms in the ontology. SPOT team is on discussions to pull this information directly from MONDO when possible.

3. When the work at EFO is completed, we will look at the best way to benefit from the phenotype annotations. Short term, the benefit will be about disease profile pages. Long term, there might be additional applications on how we prioritise targets based on evidence from recurrent phenotypes.

The body of work on our side will be considered in future user stories. I consider the search for alternative disease phenotype sources completed.
